### ISSUE TITLE
some keys trigger the FN modifier flag for some reason

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/skhd#10]
Events triggered by keys such as all function keys (f*), and the arrow keys have the fn modifier flag set for some reason, even though the fn modifier is not pressed. The same is true even with the mission control option "Use F1, F2, etc keys as standard function keys".

It is tedious to have to manually specify *fn* as a modifier in these binds.
An option is to automatically flag binds using these literals with the *fn* modifier during parsetime,
however this could make it unclear to the users that these literals CAN NOT be used with *fn* as a modifier. e.g:`alt - left` and `fn + alt - left` are equivalent.

**Comment by ArnaudValensi** [comment]
I try too bind `fn + arrow` but skhd also trigger when we just do `arrow`. Is there a way to make it work?

**Comment by koekeishiya** [comment]
fn + arrow is not possible, because the arrow key-event already implicitly has the fn-flag set.
You can see a list of literals that work and don't work with the fn-mod here: https://github.com/koekeishiya/skhd/issues/1

This is a part of macOS keyevents that we can not do anything about, sadly.

**Comment by ArnaudValensi** [comment]
Ok, I got it, thank you!

**Comment by pkieltyka** [comment]
im looking to setup my caps lock key are my primary modifier to control most of chunk via skhd -- 

is it possible to use capslock as a hyper key somehow? perhaps https://github.com/tekezo/Karabiner-Elements can help otherwise..

**Comment by pkieltyka** [comment]
btw, I just tried it and can confirm that Karabiner Elements is a great combo with skhd. I set caps lock to my hyper key via https://gist.github.com/lunelson/69d041356f90bc0974e22d2a1fb0b059 and now, I can control everything with caps lock as my mod key
