### ISSUE TITLE
Option to set a shell for skhd to use

### ISSUE THREAD

**Issue by michaelsong-hz** [koekeishiya/skhd#101]
Is there a way to set a shell for skhd to use, or for it to ignore the $SHELL environment variable and default to /bin/bash? My default shell (fish) is rather sluggish to start up (takes ~2 seconds) due to the various addons I have configured and results in slow performance for skhd, but when I switch my default shell to bash and restart skhd, it performs snappily again.

Maybe there's a way to pass the $SHELL environment variable into brew services? Or failing that, I believe that the relevant code to modify is in `src/hotkey.c` (snippet below), but I'm not exactly sure how as I'm not well versed in C, or what behaviour to change it to as there's probably a reason why skhd defaults to the user's shell instead of bash to execute commands?

```
void init_shell(void)
{
    if (!shell) {
        char *env_shell = getenv("SHELL");
        shell = env_shell ? env_shell : "/bin/bash";
    }
}
```

**Comment by dominiklohmann** [comment]
> My default shell (fish) is rather sluggish to start up (takes ~2 seconds) due to the various addons I have configured and results in slow performance for skhd, but when I switch my default shell to bash and restart skhd, it performs snappily again.

`skhd` spawns a non-interactive shell—if you want to fix this properly, separate your fish env files for interactive and non-interactive shells.

You can also run `brew edit skhd` and edit the shell manually. I suggest searching for "shell" or "fish" or "brew edit" on this issue board, since this has been asked many times before.

**Comment by michaelsong-hz** [comment]
Hey, thanks for taking the time to leave a comment. I searched and it has indeed come up many times before - somehow it didn't occur to me to search through the closed issues and only look through the open ones. Guarding my fish configs behind some interactive shell if statements did the trick for me!
