### ISSUE TITLE
Support for multiple keyboards? 

### ISSUE THREAD

**Issue by kkoscielniak** [koekeishiya/skhd#102]
Hello @koekeishiya, 

does `skhd` support keybindings for different keyboards? 

The context: On a daily basis I'm using Logitech K480 with `fn` next to `ctrl` in the bottom row of keys. However, sometimes I switch to Macbooks keyboard with `ctrl` next to `fn` (they are reversed) and my muscle memory gets in my way. 

I've overcome this problem with Karabiner-Elements, but since it's a desktop app, I cannot keep the config in my repo easily, and I'd like to ditch it in the future.

So, is there any way to have a config that works only with one of the devices?

**Comment by koekeishiya** [comment]
As far as I know the API that skhd uses to hook key events is unable to differentiate between different keyboards: https://developer.apple.com/documentation/coregraphics/quartz_event_services?preferredLanguage=occ

**Comment by kkoscielniak** [comment]
That's a bit lame, but ok :)

**Comment by franco** [comment]
> I've overcome this problem with Karabiner-Elements, but since it's a desktop app, I cannot keep the config in my repo easily, and I'd like to ditch it in the future.

Karabiner elements configuration can be found in `~/.config/karabiner/karabiner.json` and can be versioned with your favourite scm tool.
