### ISSUE TITLE
Best way to avoid collision with other hotkeys

### ISSUE THREAD

**Issue by ranman166** [koekeishiya/skhd#105]
Working off the example rc file for yabai and skhd I am having issues with hotkeys collision within vscode and iterm. 

I started to blacklist the programs, but it ended up removing most of the functionality of yabai. 

What are some strategies to avoid hotkey collision? I think I have seen some people use things like caps lock or windows key, but with skhd I don't know.

**Comment by koekeishiya** [comment]
You could try to configure a modal setup for your skhd usage. See the documentation for modes in the readme or sample config file.

**Comment by SebastienWae** [comment]
For the people who want a real life example of a modal setup you can check @pkazmier [.skhdrc file](https://gist.github.com/pkazmier/213d9dce6b1ea313eaf0a17b017c2b08)
