### ISSUE TITLE
Cannot bind non_us_backslash

### ISSUE THREAD

**Issue by qaisjp** [koekeishiya/skhd#107]
**Description**

I'm trying to bind `§` which is the key to the left of the number `1` on a British Macbook keyboard.

skhd does not accept my config.

**To reproduce**

`skhd -o` recognises this key as:
- `keycode: 0x0A	flags: 00000000000000000000000100000000`,
- but `0x0A - 1 : yabai -m space --focus 1` does not work

Karabiner EventViewer recognises this key as:
- `keycode: 0x64	name: non_us_backslash`
- but `0x64 - 1 : yabai -m space --focus 1` does not work

**Additional information**

Also, when there's a broken line, the entire config stops working and I have to undo the change and `skhd --reload` before I can use my hotkeys again. Reload does not report any error output (to stdout, stderr and always returns errcode 0). And `/usr/local/var/log/skhd` contains no files. Is this intended behavior?

**Comment by koekeishiya** [comment]
You cannot use keys as modifiers, thus `0x0A - 1 : yabai -m space --focus 1` is not a valid syntax.
However, `0x0A : yabai -m space --focus 1` should work just fine.

I don't know how the Karabiner EventViewer works so I can't really comment on the keycode it reports, but the keycode that is printed by skhd in observer mode is the exact same as if it was running in normal mode - the only difference is that in observer mode we don't perform a hotkey-lookup.

If there is a syntax error in the config file the parsing stops and the internal state is reset, such that everything will continue working properly the moment the syntax error is resolved. You don't need to run `skhd --reload` manually, unless you have explicitly disabled the hotloader (using a launch argument). For error output, run as `skhd --verbose`.

Errors are reported to stderr, and debug output is reported to stdout when launched with the `--verbose` flag. IIRC if you installed using brew the logging files are not set in the *.plist file, and so you have to either `brew install skhd --with-logging` or fix it manually.

**Comment by qaisjp** [comment]
Thanks!
