### ISSUE TITLE
Open terminal with program running.

### ISSUE THREAD

**Issue by n0ibe** [koekeishiya/skhd#108]
Is there a way to open a new terminal window with a program already running? For example, to access my file manager (lf), I now have to first open the terminal with `cmd - return: open -na /Applications/Alacritty.app`, and then type `lf`. It would be easier to have a shortcut to combine the two.

**Comment by qaisjp** [comment]
Possibly, but I think that would be a question for [Alacritty](https://github.com/alacritty/alacritty). Maybe there's a command line flag you can pass to Alacritty.

You could also perhaps leverage Automator or AppleScript to automate typing in `lf` or clicking some menu item.

**Comment by koekeishiya** [comment]
This is indeed something that is provided by the terminal application. I know that Kitty supports this in various ways. I don't use Alacritty, so I can't speak for it, but I would be very surprised if they do not have support for that.
