### ISSUE TITLE
.load directive doesn't resolve ~ home expansion

### ISSUE THREAD

**Issue by mstr3336** [koekeishiya/skhd#109]
Hi, 
I noticed that the following line in my `~/.skhdrc` does not work as I expect:

```
.load "~/.config/skhd/yabai/skhdrc"
```

Throwing the following error:

```
skhd: could not open file '/Users/matthew/~/.config/skhd/yabai/skhdrc' from load directive #1:2
```

I understand that this is documented explicitly in the readme as follows:

https://github.com/koekeishiya/skhd/blob/01722fcf49a5826392010504162bc63e2b01c423/README.md#L159-L164

So the program not attempting to expand the tilde, and instead treating it as a relative path component is consistent with the docs. 

I also know that the fix is really, really easy, as I just need to remove the `~/` prefix, however, I do think that tilde expansion is a very common expectation from a user perspective, and may help make certain path bindings more robust (Perhaps).

**Comment by koekeishiya** [comment]
Tilde expansion is a part of the shell syntax, and I prefer to keep all of that separate. If we start supporting tilde expansion, it may be confusing that e.g environment variables are not supported, so I think it is better to have a clear cut.
While it would certainly be possible to implement both tilde expansion, env variables and what not - I don't think the increase in complexity is worth it for something that is a very minor part of skhd and frankly not that useful.

I assume that most users would have something like `~/.config/skhd/<files here>` and simply load files by relative pathing.

**Comment by dominiklohmann** [comment]
For what it's worth, in most shells `~/path/to/file` expands, while `"~/path/to/file"` does not.

**Comment by mstr3336** [comment]
> Tilde expansion is a part of the shell syntax, and I prefer to keep all of that separate. If we start supporting tilde expansion, it may be confusing that e.g environment variables are not supported, so I think it is better to have a clear cut.
> While it would certainly be possible to implement both tilde expansion, env variables and what not - I don't think the increase in complexity is worth it for something that is a very minor part of skhd and frankly not that useful.
> 
> I assume that most users would have something like `~/.config/skhd/<files here>` and simply load files by relative pathing.

Yeah, that's exactly what I do have - A couple of symlinks to some versioned repos (One for my yabai config and one for some cludges to use ctrl+shift shortcuts in vim), and I appreciate that it doesn't really need to be much more complex than that. 
I'll close the issue.
