### ISSUE TITLE
Emit keypresses

### ISSUE THREAD

**Issue by net** [koekeishiya/skhd#11]
It would be nice if skhd could emit keypresses like khd. I know skhd is supposed to be the lightweight version, but at least for me this ability is invaluable.

**Comment by koekeishiya** [comment]
Not likely to be added into skhd itself, but might create an application that deals with synthesizing diff types of events (key events, system key events, mouse events).

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/qes for progress. No ETA for now.

**Comment by koekeishiya** [comment]
*qes* now supports synthesizing of keypresses and text-input.
Only tested on *High Sierra*.

**Comment by crisidev** [comment]
I tested qes on normal Sierra and works fine :)

**Comment by koekeishiya** [comment]
Changed my mind regarding this for a couple of reasons. See #44
