### ISSUE TITLE
how to use caps as hyper?

### ISSUE THREAD

**Issue by Tandolf** [koekeishiya/skhd#112]
installed skhd with brew, started the service, gave it access to accessibillity, restarted the service.

started to add keycommands to skhdrc.

if run the command 
`yabai -m window --space 2; yabai -m space --focus 2` i get an error saying there is no desktop. If a manually create the second desktop, running the command works using ctrl + opt + cmd + shift.

after tinkering, running "skhd -k "hyper - 2" triggers the keycommand.

tried:
`0x39 - 2 : yabai -m window --space 2; yabai -m space --focus 2`

does not work, nothing happens. how do i define the hyper button to be caps? 0x39 doesn't seem to work.

What am i missing?

**Comment by dominiklohmann** [comment]
Caps Lock is not a valid modifier key, you cannot do this with skhd.

**Comment by qaisjp** [comment]
you might have to use [Karabiner Elements](https://pqrs.org/osx/karabiner/) to do this (i.e. skhd will not be able to help here)

**Comment by gerardbosch** [comment]
You can use CapsLock enhancer with Karabiner: https://ke-complex-modifications.pqrs.org/#caps_lock_enhancement
It will transform <kbd>Caps Lock</kbd> into <kbd>Hyper</kbd> key.

But it won't work out-of-the-box with `skhd` as you want, I think for 2 reasons:
* this Hyper key is mapped to right version of modifiers (right shift, right control, right opt, right cmd), while the skhd `hyper` maps to left versions (I think)
* the `Capslock enhancer` comes with default actions for almost all keyboard combinations with hyper - but you can enable just some parts of the mappings in Karabiner.
