### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by n0ibe** [koekeishiya/skhd#113]
Everything is working as expected, except when I run my config file I get this kind of warning:

    /Users/noibe/.config/skhd/skhdrc: line 2: cmd: command not found

in every line where there is a shortcur definition. Again, this doesn't seem to impact any functionality, but it'd be nice to know if I'm doing something wrong. The syntax I use in the config file is, for example

    cmd - b: open -na /Applications/Firefox.app

In a shortcut with multiple modifier keys, for example

    cmd + alt - 1: yabai -m window --space 1 && yabai -m space --focus 1

the warning is

    /Users/noibe/.config/skhd/skhdrc: line 31: alt: command not found

P.s. I'm running `skhd` as a service managed by homebrew, don't know if it has anything to do with it.

**Comment by qaisjp** [comment]
> except when I run my config file

why are you running your config file?

**Comment by n0ibe** [comment]
Oh ok, I'm dumb. I thought it worked like yabai.

**Comment by qaisjp** [comment]
nope! :D
