### ISSUE TITLE
Can't seem to bind comma

### ISSUE THREAD

**Issue by Peeja** [koekeishiya/skhd#117]
```
fn + ctrl + alt + cmd - l : echo "fn + ctrl + alt + cmd - l" > /dev/ttys042
fn + ctrl + alt + cmd - 0x2f : echo "fn + ctrl + alt + cmd - 0x2f" > /dev/ttys042
```

The first binding sends output to my tty; the second one doesn't. I believe the key isn't binding at all. It looks like [someone had this problem a few months ago too](https://github.com/koekeishiya/skhd/issues/1#issuecomment-548275704).

**Comment by somdoron** [comment]
Try to use upper case for the hexadecimal leters: 0x2F, that solved it for me.

**Comment by Peeja** [comment]
Hmm, no dice, I'm afraid:

```
fn + ctrl + alt + cmd - 0x2D : echo "fn + ctrl + alt + cmd - 0x2D" > /dev/ttys005
fn + ctrl + alt + cmd - 0x2F : echo "fn + ctrl + alt + cmd - 0x2F > /dev/ttys005
```

The first one works (`0x2D` is `n`); the second one still doesn't.

**Comment by dominiklohmann** [comment]
Can't reproduce this; on a german keyboard, both of these work:

```
fn + ctrl + alt + cmd - 0x2F : say period
fn + ctrl + alt + cmd - 0x2B : say comma
```

**Comment by somdoron** [comment]
@Peeja you are missing the end quote on the second line

**Comment by Peeja** [comment]
Hoo boy. Apparently I pressed `.` way back when I was using `skhd -o`, and I've had the wrong code ever since. `0x2B` works just fine.

Sorry, folks, and thanks for all the help!
