### ISSUE TITLE
Is it possible to send keys to an application using skhd?

### ISSUE THREAD

**Issue by danijar** [koekeishiya/skhd#118]
My motivation is the following. I'd like to use the <kbd>Cmd</kbd> key for window management. However, this hides shortcuts in some applications. For example, when I assign focusing the window to the right to <kbd>Cmd</kbd>+<kbd>L</kbd>, I cannot jump to the address bar in Chrome using the keyboard anymore.

It would be great if I could define a keybind to <kbd>Ctrl</kbd>+<kbd>L</kbd> that sends the keys <kbd>Cmd</kbd>+<kbd>L</kbd> to the current application. This way, I could continue using shortcuts in all applications just by pressing <kbd>Ctrl</kbd> instead of <kbd>Cmd</kbd>, while handling exceptions using `proc_map_lst`. Is this possible somehow?

So far, I've tried adding this line to skhdrc but it does nothing. The is no error message in `skhd -V` but the same command works when I run it manually in a terminal:

```
ctrl - l : osascript -e 'tell application "System Events" to keystroke "l" using {command down}'
```

**Comment by dominiklohmann** [comment]
You cannot send keys to a specific application, but you can use `skhd --key "cmd - l"` to simulate a <kbd>cmd</kbd> + <kbd>l</kbd> keystroke.

The key event system of macOS does not allow for a keystroke to be sent to a single application reliably, as this would require all applications to use that one specific way of listening for keystrokes for which this works.

**Comment by koekeishiya** [comment]
There are macOS APIs for doing this, but skhd does not utilize them. It is primarily meant to be a hotkey utility, and not a key-remapper/synthesizer.

**Comment by danijar** [comment]
Thanks, this works for me.
