### ISSUE TITLE
Not detecting keys on password fields

### ISSUE THREAD

**Issue by FishCoding** [koekeishiya/skhd#119]
I have Catalina and skhd is not able to capture the input when I am in a password field on a website in Firefox, it captures the modifiers but not the keys. Is it a bug or a limitation of Catalina? 

The binding is: ctrl + alt - p : open ....

Thanks in advance 😄

**Comment by koekeishiya** [comment]
This is a limitation on the Quartz Event Services API that skhd uses for intercepting key events, for security purposes.

Sent from my iPhone



-

On 2 Apr 2020, at 11:27, Mario <notifications@github.com> wrote:

﻿

I have Catalina and skhd is not able to capture the input when I am in a password field on a website in Firefox, it captures the modifiers but not the keys. Is it a bug or a limitation of Catalina?

The binding is: ctrl + alt - p : open ....

Thanks in advance 😄

**Comment by FishCoding** [comment]
Thanks 👍
