### ISSUE TITLE
Can't map the Magic Keyboard Eject key

### ISSUE THREAD

**Issue by kkoscielniak** [koekeishiya/skhd#120]
Is there any way to map the Magic Keyboard Eject ⏏ key? 

It can't be observed via `skhd -o`. 

The Karabiner-EventViewer app says the code for this one would be `0xb8`, however the codes the EventViewer shows don't match the ones used by `skhd`.

This SO thread says it would be `0x92`: https://stackoverflow.com/questions/15008375/which-is-the-virtual-key-in-mac-for-the-eject-key

None of above works. Is there any way we could map this key via `skhd`? I could do it via another app, like Karabiner (map Eject to another key, and then map that key in `skhd`), but I like to keep the config in one place.

**Comment by koekeishiya** [comment]
This is not possible with the API that skhd uses. If I am not mistaken, Karabiner actually takes full control over keyboard devices using the IOHID API in IOKit. This means that it is now responsible for mapping of scancodes to virtual keys and everything based on the device usage pages.
