### ISSUE TITLE
Fast Focusing No Longer Working

### ISSUE THREAD

**Issue by bmw417** [koekeishiya/skhd#122]
I just updated to the Catalina 10.15.4 Supplemental Update a couple days ago, and I suspect that something there is breaking some functionality of skhd, since this issue seems to coincide with when I started observing this behavior.

I have these lines in my .skhdrc:

    cmd - 1 : yabai -m space --focus 1
    cmd - 2 : yabai -m space --focus 2
    cmd - 3 : yabai -m space --focus 3
    cmd - 4 : yabai -m space --focus 4
    cmd - 5 : yabai -m space --focus 5
    cmd - 6 : yabai -m space --focus 6
    cmd - 7 : yabai -m space --focus 7
    cmd - 8 : yabai -m space --focus 8
    cmd - 9 : yabai -m space --focus 9
    cmd - 0 : yabai -m space --focus 10

None of the focusing options seem to be working for me anymore however. I've already restarted the computer and the skhd daemon multiple times to make sure it's not a fluke.

Running `skhd -V` in the terminal just prints out 

    skhd: successfully created pid-file..
    skhd: using config '/Users/bmw417/.skhdrc'

then many more lines of my configuration bindings, and the final 

    skhd: watching files for changes:
	/Users/bmw417/.skhdrc

at the bottom. No mentions of errors anywhere I can see.

**Comment by dominiklohmann** [comment]
This is not an issue with `skhd`, but rather with you running an outdated version of `yabai`. Please install a recent version of yabai and update/reinstall the scripting addition for this to work.

**Comment by bmw417** [comment]
That seemed to have fixed it, thanks. I hadn't realized that there was more to updating yabai than just a semi-frequent "brew update".
