### ISSUE TITLE
skhd: could not lock pid-file! abort..

### ISSUE THREAD

**Issue by VonbatenBach** [koekeishiya/skhd#126]
Hi, I've just installed skhd via homebrew, did everything like it was written in instructions and after running command "skhd" I constantly get error:

skhd: could not lock pid-file! abort..

I tried to do things advised in similar threads but none of them fixes that.

**Comment by dominiklohmann** [comment]
> I tried to do things advised in similar threads

Care to list what you've tried?

**Comment by koekeishiya** [comment]
I don't mean to be rude.. but this is an issue with your understanding of what's going on.
The error message indicates that upon launch, it was unable to lock the pid file, meaning that some other process on your system already acquired an exclusive lock.

Now the only reasonable explanation is that you probably followed the installation instructions without actually understanding what they do, as the final step is to launch skhd and have it managed by brew services. This implies that skhd is already running, and so when you afterwards try to run it a second time, manually, it will fail with the above message.

I suppose the instructions could be more explicit, but I don't think it is my job to educate people in terms of how launch services work on macOS.

**Comment by VonbatenBach** [comment]
Yes, I probably don't fully understand how it works. I suppose, once I start service via brew, skhd runs in background and I should be able to access my key bindings. And that's why I get that 'pid' error, as I try to run second instance of skhd. 
But there is another problem... Once I run service I am not able to access bindings (even after restarting/logout). On the other hand, when I stop brew service and run command 'skhd' everything works. Any ideas?

**Comment by koekeishiya** [comment]
Hmm I wonder if this could be an issue related with the config path. Can you try to run it through brew services with the `--verbose` flag? To set this you need to edit the *.plist* file for the service. I believe it is located in `~/Library/LaunchAgents/homebrew.<something>.skhd.plist`

You probably also need to specify the output files for stdout and stderr, this can be done by adding the following to the .plist:

```
    <key>StandardOutPath</key>
    <string>/tmp/skhd.out</string>
    <key>StandardErrorPath</key>
    <string>/tmp/skhd.err</string>
```

The final plist should look something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.koekeishiya.skhd</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/skhd</string>
        <string>--verbose</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/skhd.out</string>
    <key>StandardErrorPath</key>
    <string>/tmp/skhd.err</string>
</dict>
</plist>
```

**Comment by VonbatenBach** [comment]
Well, it's surprisingly weird but it turns out, that my `plist` file was empty. I copy-pasted the final plist file that you proposed and it works! There must have been something wrong with the brew installation. 

I have one more question. One of my key bindings runs python command. When I press the shortcut through brew service (not command line 'skhd') I get the message: The “python3” command requires the command line developer tools. Would you like to install...
Everything seems to work when I add `source ~/.bash_profile` to my commands in skhdrc. I suppose it may be caused by my python3, which is installed in `/opt/local/bin/`. 

Is there any elegant way to avoid such things? I mean, to make the commands run as they were run from terminal? This problem doesn't occur when using command line skhd.

**Comment by alextremblay** [comment]
what you're asking for (to have commands run from skhd work the same as they do when run from your terminal) is possible, but very complex and beyond the scope of this issue / skhd in general. The reason a solution to your problem is hard has nothing to do with skhd and everything to do with launchd, which is the MacOS init system which runs and manages skhd.

I would suggest you start learning how launchd work, and the execution environment that it runs services in.

The answer to your question lies in the launchd documentation: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html

good luck
