### ISSUE TITLE
Remapping a command to the same command

### ISSUE THREAD

**Issue by andbloch** [koekeishiya/skhd#136]
Using the following remapping Ctrl + C does not stay Ctrl + C in the Terminal:

 ctrl - 0x08 [
     "terminal": skhd -k "ctrl - 0x08"
     *: skhd -k "cmd - 0x08"
]

Might it be that skhd -k "ctrl - 0x08" causes skhd to catch the Ctrl + C event again and thus causes an infinite loop? What can I do to leave Ctrl + C unchanged in the Terminal?

**Comment by dominiklohmann** [comment]
In the example skhdrc there's a comment showing you how to do it.

```
ctrl - c [
  "terminal" ~
  *          : skhd -k 'cmd - c'
]
```

**Comment by andbloch** [comment]
Thank you! That solved the issue!
