### ISSUE TITLE
the screen intermittently freezes for 3-20 sec about half a dozen times a day

### ISSUE THREAD

**Issue by voloshyn** [koekeishiya/skhd#138]
It's hard to say what exactly triggers the freezes, it appears to be random. 
By deleting apps one by one I've determined skhd to be the culprit. Any idea what can cause this?

**Comment by koekeishiya** [comment]
No clue, sorry. I've been using skhd (and other software using the same APIs) for like 4years and never seen this.

**Comment by voloshyn** [comment]
Thanks for your reply. It started freezing when skhd is not running, something else must be going on :(
