### ISSUE TITLE
Firefox failes to launch - Catalina

### ISSUE THREAD

**Issue by jack836** [koekeishiya/skhd#140]
I could launch Firefox from the terminal using `open -a /Applications/Firefox.app` , no problem. It also gets launched properly when invoked from the Launchpad.
But, when I try to invoke it from skhd using  `ctrl + alt - w     : open -a /Applications/Firefox.app` , I always end-up with the following screen. 
![Screen Shot 2020-07-20 at 19 00 48](https://user-images.githubusercontent.com/16317632/87925891-e81aff80-cabb-11ea-97fb-4bc80c12b6c4.png)

Is there a real difference in the way Firefox  gets started from terminal and through skhd? Any help is highly appreciated.  BTW,  I am using Catalina-10.15.4, skhd-0.3.5 and firefox-78.0.2. I disabled all the add-ons, reinstalled Firefox, but the issue prevails.

Please forgive me if it is a Firefox issue and has nothing to do with skhd...

**Comment by koekeishiya** [comment]
I really have no idea, sorry. All skhd does is run the given command through: $(shell) -c "command" IIRC.

**Comment by siversss** [comment]
> I could launch Firefox from the terminal using `open -a /Applications/Firefox.app` , no problem. It also gets launched properly when invoked from the Launchpad.
> But, when I try to invoke it from skhd using `ctrl + alt - w : open -a /Applications/Firefox.app` , I always end-up with the following screen.
> ![Screen Shot 2020-07-20 at 19 00 48](https://user-images.githubusercontent.com/16317632/87925891-e81aff80-cabb-11ea-97fb-4bc80c12b6c4.png)
> 
> Is there a real difference in the way Firefox gets started from terminal and through skhd? Any help is highly appreciated. BTW, I am using Catalina-10.15.4, skhd-0.3.5 and firefox-78.0.2. I disabled all the add-ons, reinstalled Firefox, but the issue prevails.
> 
> Please forgive me if it is a Firefox issue and has nothing to do with skhd...

I was able to make it work using simple shell script bound to key:

#!/bin/zsh -i
open -a Firefox.app

please pay attention to '-i' option

hope it helps

**Comment by jack836** [comment]
@siversss thank you for your kind help. I tried your suggestion, but no luck so far. I also want to mention that,

1. If Firefox is already running, then attempting to focus/un-minimise the Firefox window works with the 'open' command. The above 'Safe Mode' message pops-up only when I attempt to launch Firefox (while it is not running) 

2. It all seemed to have worked well a couple of weeks ago. So I also need to test it in a different machine, if it can be reproduced.

Anyway, thanks for all the suggestion here. I hope I can get it working again.

**Comment by Galactic-Dev** [comment]
I have the same issue, and I found out why it happens. To launch Firefox in safe mode on macOS you have to hold down alt when its launching, this is why it gets triggered since alt is in the keybind. The only workaround I know to this right now is to release the keys very quickly after you press them, or just to not use alt in the keybind.

**Comment by jack836** [comment]
Oh! Yes!! 'the devil was in the details' (as always). I tweaked every other option, except the key-bind. Didn't expect a modifier key in the key-bind can have such an effect. @Galactic-Dev I appreciate your efforts in finding it and posting it here.

**Comment by UnsolvedCypher** [comment]
If you `export MOZ_DISABLE_SAFE_MODE_KEY=1` before running the Firefox command, that disables the trigger for alt to open troubleshooting mode.
