### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by aklsh** [koekeishiya/skhd#143]
Hey,

I was not able to install skhd via brew - it threw an error that some header file was missing. So, I tried building it from source. I cloned the repo and ran `make install` and `make`. The binary is being built in a `bin/` folder in the cloned repo. However, I am not able to install it in `/usr/bin/`. Can someone please help?

**Comment by dominiklohmann** [comment]
On macOS you don't typically install into `/usr/bin`, but rather into `/usr/local/bin`.

If you experience issues with the installation via Homebrew, make sure to take a look at the output of `brew doctor`. It sounds like you might have messed up your system by accident when trying to install/link stuff.

**Comment by aklsh** [comment]
Thanks! The issue was that the compiler used was the gcc included with macOS, not the one I installed through Homebrew. Once I fixed that, everything ran properly.
