### ISSUE TITLE
Shortcuts not working in iTerm2

### ISSUE THREAD

**Issue by Zemelware** [koekeishiya/skhd#148]
I am using skhd with yabai and only in iTerm2 none of the shortcuts are working. They even work in the default terminal, but not iTerm2. Does anyone know the cause of this and how to fix it?

**Comment by dominiklohmann** [comment]
Disable `Secure Keyboard Entry` in `Menu` > `iTerm2`:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/4488655/94475160-fa599e00-01ce-11eb-9a8f-60d44060f1f9.png">

**Comment by Zemelware** [comment]
@dominiklohmann thank you so much! I actually figured this out right before I saw this, but thanks anyway!
