### ISSUE TITLE
Possible to distinguish between tap and hold?

### ISSUE THREAD

**Issue by jamesottaway** [koekeishiya/skhd#149]
I currently use https://github.com/jasonrudolph/ControlEscape.spoon and Hammerspoon to remap my Control key to an Escape _if_ I tap it vs. maintaining the standard modifier behaviour if it's held.

Is something like this possible w/ shkd so I can switch from Hammerspoon to shkd?

**Comment by koekeishiya** [comment]
This is technically possible, yes, but not in the current implementation. This is not something that I am likely to implement in the near future.

**Comment by jamesottaway** [comment]
OK, thanks for the reply. Love your work, regardless!
