### ISSUE TITLE
modal support

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/skhd#15]
I've come to realize that modal support can be added in a way that will not cause ~~significant~~ any performance degradation ~~, if noticeable~~ at all. 

This is achieved by adding a separate operator (e.g: `;` instead of `:`) to identify an internally defined command, rather than something to be ran through `$SHELL -c`. By doing this, *skhd* will not require input at runtime to simply switch into another mode (*khd* uses a unix domain socket primarily for this functionality).

As there can only be one active mode at a time and because that mode can only change internally by performing a registered bind; this system is lock-free. Because the datastructures for modes and their associated hotkeys are built during parse-time, the only performance impact that matters is during hotkey execution.

The extra work we have to do is simply checking if the command is an *internal command* or *external command*. If it's an *internal command* we call through a function pointer (validation and lookup happens during parsing), and if it is an *external command* we do the old logic.
This happens after we get a hotkey-match, and will not impact the checking of keys themselves.

The suggested mode implementation in *skhd* will NOT provide the prefix-timer (timeout based modes) that *khd* currently does.
 
Another issue in *khd* with regards to modal support is the terrible syntax. The grammar that *khd* implements is not really defined, whereas in *skhd* it is.

Syntax for mode-definition:
```
# define mode 'switcher' with an on_enter command
:: switcher : chunkc border::color 0xff24ccaa

# define modes without an on_enter command
:: swap
:: focus
```
A mode must be defined as specified above, before it can be utilized.
Failure to do so will result in a parse error.

Hotkey syntax extension for modal support 
```
# hotkey   = <mode> '<' <action> | <action>
#
# mode     = <mode> | <mode> ',' <mode>
#
# action   = <keysym> ':' <command> |
#            <keysym> '->' ':' <command>


# adds the defined hotkey to all specified modes
switcher, swap, focus < ctrl - f ; switcher

# adds hotkey to mode 'focus'
focus < alt - l : chunkc tiling::window --focus east

# old syntax; adds hotkey to the 'default' mode
alt - l : chunkc tiling::window --focus east
```

**Comment by choco** [comment]
Any news on this? I'. in the middle of reworking by setup/configuration files and I'm still using khd

**Comment by koekeishiya** [comment]
The modal branch works as described in the above post, but I have not yet merged into master due to memory leak upon config reload that I never bothered to fix due to being lazy: https://github.com/koekeishiya/skhd/commit/94c26f456f095ec8334d9c313943c2747d27c0c2#diff-c640797beed694f7cadbaa34555d5791R132

**Comment by koekeishiya** [comment]
memory leak and some error reporting has been fixed in the latest commit, as well as merged in fixes from master.

It should be ready for usage, but I want to do another pass of cleanup before getting this into an actual release.

**Comment by meck** [comment]
I've been trying out this, seems great, made a whole separate mode for window management and set it up to toggle the dark mode of the Mac menubar as a mode indicator. Im wondering if there is any way to unbind all the keys in a mode, eg start with a clean slate?
Anyhow great work!

**Comment by koekeishiya** [comment]
There isn't any way to clean a mode that has already been populated. I'm curious as to what the end-goal is here. Basically, after the config file has been parsed, there is no way to modify the available binds; this is supposed to be a one time thing (unless you of course edit the config file and save, which will trigger a complete reparse).

**Comment by meck** [comment]
I didn't mean unbind at runtime, I've meant to use it as a vim style mode where all keys that I've not explicitly bound to a function at setup dosen't do their normal function. 
[this](https://github.com/meck/dotmeck/blob/master/.skhdrc) is the setup I'm working on, with all the window operations except movement between windows in a separate mode. And I just wanted to disable keys that set in the rc file in that layer. It's a very minor thing however...

**Comment by koekeishiya** [comment]
Right I see what you're trying to do. This is an option in *khd*, however that is a global setting.
I believe in **skhd**, this should be a setting for the particular mode.
Will think a bit about what the syntax should be, but ideally I'd like for it all to happen during the *mode* declaration.

e.g: `:: my_mode <some_keyword> : <command>`

where `<some_keyword>` indicates that this mode will ignore keys that are not registered as binds.

**Comment by meck** [comment]
I've been running on this branch for a good while now without any issue, anything missing for merging it?

**Comment by ChinesePeanuts** [comment]
Yes, it would be nice to have this feature, it's the only thing that is missing for me to leave khd!

**Comment by koekeishiya** [comment]
@meck 

My previous post regarding the functionality for  

> where all keys that I've not explicitly bound to a function at setup dosen't do their normal function

is pretty much what's left before merging, I just haven't gotten around to doing this yet.

@ChinesePeanuts 

> Will it have a prefix expire feature like in khd?

Prefix expire based on timeout will not be implemented here.

**Comment by koekeishiya** [comment]
Merged in release v0.1.0.

See README / sample config for updated information.

**Comment by pkazmier** [comment]
Does anyone have any good modal layouts they could share? My fingers feel like they are doing gymnastics with the default layout 😀 I just discovered chunkwm/skhd yesterday and am loving it! Thanks for your hard work!

**Comment by alyssais** [comment]
Here’s mine.  
https://gist.github.com/alyssais/3845e4e9d3cb6b7f080b271270685741#file-skhdrc

**Comment by pkazmier** [comment]
@alyssais Thanks! I like how you have a separate mode for each of the main functions. I'm looking forward to trying this layout when I get home!

**Comment by pkazmier** [comment]
@alyssais I finished tweaking my modal config over the past couple of days, so I thought I'd share back as I essentially extended yours. I really like the dedicated mode for each major function (focus, warp, resize, swap) as I like the consistency with using the same keys for directions. I added two other modes (grid and warpnf). I'll have to work with this for a week or so, but thus far, I am enjoying the layout.

https://gist.github.com/pkazmier/213d9dce6b1ea313eaf0a17b017c2b08

**Comment by alyssais** [comment]
That’s awesome @pkazmier! I’m going to borrow that config right back! :D

**Comment by giulioungaretti** [comment]
omg both @alyssais and @pkazmier  your configurations are like the best I have ever seen <3

**Comment by chrishoage** [comment]
The addition of modes allowed me to switch from khd to skhd. Below are both my rc files to compare. The only difference is there is no timeout on prefix, which I have talked about how to do here https://github.com/koekeishiya/skhd/issues/37#issuecomment-395995098


<details>
<summary>Expand for `.khdrc`</summary>

```
khd mode prefix prefix on
khd mode prefix timeout 0.5

# set border color for different modes
khd mode default on_enter chunkc border::color 0xFF6699CC
khd mode prefix on_enter chunkc border::color 0xFFFAC863
khd mode manage on_enter chunkc border::color 0xFFC594C5
khd mode insert on_enter chunkc border::color 0xFFF99157

ctrl - k                  : khd -e "mode activate prefix"
prefix - i                : khd -e "mode activate insert" ; khd -e "void_unlisted_bind off"
prefix - m                : khd -e "mode activate manage"
manage - 0x35             : khd -e "mode activate default"
insert - 0x35             : khd -e "mode activate default" ; khd -e "void_unlisted_bind on"

# prefix

prefix + cmd + shift - r  : chunkc tiling::desktop --equalize
prefix - 0x2A             : chunkc tiling::window --toggle split

# Toggle window state
prefix + shift - f        : chunkc tiling::window --toggle fullscreen
prefix - p                : chunkc tiling::window --toggle parent
prefix - w                : chunkc tiling::window --toggle float

# Move focused window to display
prefix + cmd - 1          : chunkc tiling::window --send-to-monitor 1
prefix + cmd - 2          : chunkc tiling::window --send-to-monitor 2

# Move focused window to space
prefix + shift - 1        : chunkc tiling::window --send-to-desktop 1
prefix + shift - 2        : chunkc tiling::window --send-to-desktop 2
prefix + shift - 3        : chunkc tiling::window --send-to-desktop 3

# Set space tiling mode
prefix + b                : chunkc tiling::desktop --layout bsp
prefix + f                : chunkc tiling::desktop --layout monocle
prefix + w                : chunkc tiling::desktop --layout float

# Rotate tree 90 clockwise
prefix + cmd - r          : chunkc tiling::desktop --rotate 90

# Restore code layout
prefix - c                : chunkc tiling::desktop --deserialize ~/.chunkwm_layouts/code

# Expand focused window in direction
manage + cmd - h          : chunkc tiling::window --use-temporary-ratio 0.025 --adjust-window-edge west
manage + cmd - j          : chunkc tiling::window --use-temporary-ratio 0.025 --adjust-window-edge south
manage + cmd - k          : chunkc tiling::window --use-temporary-ratio 0.025 --adjust-window-edge north
manage + cmd - l          : chunkc tiling::window --use-temporary-ratio 0.025 --adjust-window-edge east

# Reduce focused window in direction
manage + cmd + shift - h  : chunkc tiling::window --use-temporary-ratio -0.025 --adjust-window-edge west
manage + cmd + shift - j  : chunkc tiling::window --use-temporary-ratio -0.025 --adjust-window-edge south
manage + cmd + shift - k  : chunkc tiling::window --use-temporary-ratio -0.025 --adjust-window-edge north
manage + cmd + shift - l  : chunkc tiling::window --use-temporary-ratio -0.025 --adjust-window-edge east

# Container Gaps
manage - g                : chunkc tiling::desktop --gap inc
manage + shift - g        : chunkc tiling::desktop --gap dec

# Increase Screen Padding
manage - p                : chunkc tiling::desktop --padding inc
manage + shift - p        : chunkc tiling::desktop --padding dec

# Global keybinds

# Open new iTerm window
cmd - return           : exec ~/bin/open-iTerm.applescript

# Mark focused window for next insertion point
# ctrl + shift - m          : kwmc window -mk focused

# Focus window in direction
cmd + alt - h             : chunkc tiling::window --focus west
cmd + alt - j             : chunkc tiling::window --focus south
cmd + alt - k             : chunkc tiling::window --focus north
cmd + alt - l             : chunkc tiling::window --focus east

cmd + alt - c             : chunkc tiling::window --focus next
cmd + alt + shift - c     : chunkc tiling::window --focus prev

# Swap Focused Window
ctrl + alt - h           :  chunkc tiling::window --swap west
ctrl + alt - j           :  chunkc tiling::window --swap south
ctrl + alt - k           :  chunkc tiling::window --swap north
ctrl + alt - l           :  chunkc tiling::window --swap east

# Detach Focused Window And Reinsert In Direction
ctrl + shift - h         : chunkc tiling::window --warp west
ctrl + shift - j         : chunkc tiling::window --warp south
ctrl + shift - k         : chunkc tiling::window --warp north
ctrl + shift - l         : chunkc tiling::window --warp east

# Set next insertion point in direction

ctrl + cmd - h           : chunkc tiling::window --use-insertion-point west
ctrl + cmd - j           : chunkc tiling::window --use-insertion-point south
ctrl + cmd - k           : chunkc tiling::window --use-insertion-point north
ctrl + cmd - l           : chunkc tiling::window --use-insertion-point east
ctrl + cmd - c           : chunkc tiling::window --use-insertion-point cancel

# Cycle focus though displays
cmd + alt - p             : chunkc tiling::monitor -f prev
cmd + alt - n             : chunkc tiling::monitor -f next

# Cycle focus though spaces
cmd + alt - 0x21          : khd -p "ctrl - left"
cmd + alt - 0x1E          : khd -p "ctrl - right"
```
</details>

<details>
<summary>Expand for `.skhdrc`</summary>

```
:: default    : chunkc border::color 0xFF6699CC
:: prefix @   : chunkc border::color 0xFFFAC863
:: nobind     : chunkc border::color 0xFFF99157
:: manage @   : chunkc border::color 0xFFC594C5

prefix, nobind, manage  < escape    ; default
ctrl - k                            ; prefix
prefix                  < i         ; nobind
prefix                  < m         ; manage

# Rebalance BSP Tree
prefix                   < cmd + shift - r   : chunkc tiling::desktop --equalize

# Change the split mode of the current node (\)
prefix                   < 0x2A              : chunkc tiling::window --toggle split

# Toggle window state of focused node
prefix                    < shift - f        : chunkc tiling::window --toggle fullscreen
prefix                    < p                : chunkc tiling::window --toggle parent
prefix                    < w                : chunkc tiling::window --toggle float

# Move focused window to display
prefix                    < cmd - 1          : chunkc tiling::window --send-to-monitor 1
prefix                    < cmd - 2          : chunkc tiling::window --send-to-monitor 2

# Move focused window to space
prefix                    < shift - 1        : chunkc tiling::window --send-to-desktop 1
prefix                    < shift - 2        : chunkc tiling::window --send-to-desktop 2
prefix                    < shift - 3        : chunkc tiling::window --send-to-desktop 3

# Set space tiling mode
prefix                    < b                : chunkc tiling::desktop --layout bsp
prefix                    < f                : chunkc tiling::desktop --layout monocle
prefix                    < w                : chunkc tiling::desktop --layout float

# Rotate tree 90 clockwise
prefix                    < cmd - r          : chunkc tiling::desktop --rotate 90

# Restore code layout
prefix                    < c                : chunkc tiling::desktop --deserialize ~/.chunkwm_layouts/code

# Expand focused window in direction
manage                    < cmd - h          : chunkc tiling::window --use-temporary-ratio 0.025 --adjust-window-edge west
manage                    < cmd - j          : chunkc tiling::window --use-temporary-ratio 0.025 --adjust-window-edge south
manage                    < cmd - k          : chunkc tiling::window --use-temporary-ratio 0.025 --adjust-window-edge north
manage                    < cmd - l          : chunkc tiling::window --use-temporary-ratio 0.025 --adjust-window-edge east

# Reduce focused window in direction
manage                    < cmd + shift - h  : chunkc tiling::window --use-temporary-ratio -0.025 --adjust-window-edge west
manage                    < cmd + shift - j  : chunkc tiling::window --use-temporary-ratio -0.025 --adjust-window-edge south
manage                    < cmd + shift - k  : chunkc tiling::window --use-temporary-ratio -0.025 --adjust-window-edge north
manage                    < cmd + shift - l  : chunkc tiling::window --use-temporary-ratio -0.025 --adjust-window-edge east

# Container Gaps
manage                    < g                : chunkc tiling::desktop --gap inc
manage                    < shift - g        : chunkc tiling::desktop --gap dec

# Increase Screen Padding
manage                    < p                : chunkc tiling::desktop --padding inc
manage                    < shift - p        : chunkc tiling::desktop --padding dec

# Global keybinds

# Open new iTerm window
cmd - return              : exec ~/bin/open-iTerm.applescript

# Focus window in direction
cmd + alt - h             : chunkc tiling::window --focus west
cmd + alt - j             : chunkc tiling::window --focus south
cmd + alt - k             : chunkc tiling::window --focus north
cmd + alt - l             : chunkc tiling::window --focus east

cmd + alt - c             : chunkc tiling::window --focus next
cmd + alt + shift - c     : chunkc tiling::window --focus prev

# Swap Focused Window
ctrl + alt - h           :  chunkc tiling::window --swap west
ctrl + alt - j           :  chunkc tiling::window --swap south
ctrl + alt - k           :  chunkc tiling::window --swap north
ctrl + alt - l           :  chunkc tiling::window --swap east

# Detach Focused Window And Reinsert In Direction
ctrl + shift - h         : chunkc tiling::window --warp west
ctrl + shift - j         : chunkc tiling::window --warp south
ctrl + shift - k         : chunkc tiling::window --warp north
ctrl + shift - l         : chunkc tiling::window --warp east

# Set next insertion point in direction

ctrl + cmd - h           : chunkc tiling::window --use-insertion-point west
ctrl + cmd - j           : chunkc tiling::window --use-insertion-point south
ctrl + cmd - k           : chunkc tiling::window --use-insertion-point north
ctrl + cmd - l           : chunkc tiling::window --use-insertion-point east
ctrl + cmd - c           : chunkc tiling::window --use-insertion-point cancel

# Cycle focus though displays
cmd + alt - p             : chunkc tiling::monitor -f prev
cmd + alt - n             : chunkc tiling::monitor -f next

# Cycle focus though spaces
cmd + alt - 0x21          : qes -k "ctrl - left"
cmd + alt - 0x1E          : qes -k "ctrl - right"
```
</details>


Great work @koekeishiya this is a huge improvement over khd!

**Comment by koekeishiya** [comment]
@ChinesePeanuts 

After @chrishoage dropped his message in the other issue, I realized that we actually can do prefix-timeout with the current implementation, by doing the following:
```
:: default : chunkc border::color 0xFF8fee96
:: prefix  : chunkc border::color 0xFFFAC863; sleep 2; qes -k "escape"
prefix < escape ; default
```

**Comment by ChinesePeanuts** [comment]
I've seen this, I was wondering about the performance of doing this rather than having prefix thing directly in chunkwm? Thanks for noticing me, this is nice of you! 
Anyway I now that I don't use prefixes anymore, I don't feel like needing them anymore aha

**Comment by chrishoage** [comment]
> Anyway I now that I don't use prefixes anymore, I don't feel like needing them anymore aha

I'm in the same boat. I thought I would miss them, but have been getting along just fine with out them. 

Thanks for the awesome improvement over khd @koekeishiya!
