### ISSUE TITLE
Noticable delay in Big Sur

### ISSUE THREAD

**Issue by askurihin** [koekeishiya/skhd#150]
Hello, first of all, thank you for skhd and yabai!

After yabai has been fixed to work in Big Sur (scripting additions), I started to use skhd to travel between spaces
(yabai -m space --focus) and immediately noticed a ~0.5 delay.
First I thought it was a yabay's issue, but if `yabai -m space --focus` is executed from terminal, 
space focuses without a noticeable delay.

My skhd config:

```
# fast space travel
ctrl - 1 : yabai -m space --focus 1
ctrl - 2 : yabai -m space --focus 2
ctrl - 3 : yabai -m space --focus 3
ctrl - 4 : yabai -m space --focus 4
ctrl - 5 : yabai -m space --focus 5
ctrl - 6 : yabai -m space --focus 6
ctrl - 7 : yabai -m space --focus 7
ctrl - 8 : yabai -m space --focus 8
ctrl - 9 : yabai -m space --focus 9
ctrl - 0 : yabai -m space --focus 10
```

skhd version: **skhd version 0.3.5**

Can you help me debug this issue?

**Comment by dominiklohmann** [comment]
What's your shell startup time? For a quick and easy test, run `time $SHELL -c exit`.

This is important because skhd runs commands via `$SHELL`.

For example, on my machine, starting the shell takes less than 5ms.

```
❯ hyperfine "$SHELL -c exit"
Benchmark #1: /usr/local/bin/zsh -c exit
  Time (mean ± σ):       4.6 ms ±   0.9 ms    [User: 1.7 ms, System: 1.6 ms]
  Range (min … max):     3.6 ms …   9.6 ms    414 runs
```

**Comment by askurihin** [comment]
Thank you, I didn't know commands go through $SHELL, that explains the delay!
