### ISSUE TITLE
Is the project name a typo?

### ISSUE THREAD

**Issue by apetresc** [koekeishiya/skhd#151]
Sorry, I just can't resist the curiosity. Clearly this project is an homage to sxhkd (but it's not for X), and the description repeatedly calls it a "**s**imple **h**ot**k**ey **d**aemon". Everything points to the name being "shkd", except it's not - it's "skhd". The README doesn't acknowledge this at all. I'm just baffled, curious, and slightly amused 😅 So just to sate my own curiosity - is there a reason for this subtle barrier to remembering the name?

**Comment by koekeishiya** [comment]
Not a typo, just an inside joke. Probably should choose something better when making software used by other people.

**Comment by apetresc** [comment]
Haha, I see 😁 Thanks for humoring my trivial question!
