### ISSUE TITLE
How can I define custom functions?

### ISSUE THREAD

**Issue by ZakTaccardi** [koekeishiya/skhd#153]
For example, I have two different ways of launching applications

```sh
open -a "<APPLICATION>"
osascript -e 'activate application "<APPLICATION>"'
```

So I want to define a function like:

```sh
goTo () {
  open -a $1
}

activeApplication () {
  osascript -e 'activate application $1'
}


```

and use it like:

```
cmd + alt + ctrl + shift - a : goTo("Android Studio")
cmd + alt + ctrl + shift - b : activeApplication("Google Chrome")
```

How can I add custom functions to `skhd`?

**Comment by 1rodriguez** [comment]
For zsh, you'll want to define those functions in you .zshenv, since skhd doesn't use an interactive shell to execute the commands (.zshrc definitions are limited to interactive shells)

So in your .zshenv:
```bash
goTo () {
   open -a $1
}
```

And in your .skhdrc:

```
alt - t : goTo TextEdit
```

**Comment by Inc0n** [comment]
An alternative, put thoese into a script folder somewhere, for example `.local/scripts/`, or in the same directory as your skhdrc config file.
And a tip:
Use a consistent script folder path are, they don't have to, but makes it esaier to manage your scripts.
