### ISSUE TITLE
How to run command on keydown rather than keypress event?

### ISSUE THREAD

**Issue by danijar** [koekeishiya/skhd#156]
I've noticed that the latency with which the commands are executed is larger when I keep a key pressed for a couple of hundred milliseconds before releasing it, and it is faster when I press and release the key immediately. Is there a way to register commands to the keydown event? I think this would make window management using yabai respond faster.

**Comment by koekeishiya** [comment]
We already observe and react to the *key down* event: https://github.com/koekeishiya/skhd/blob/master/src/skhd.c#L164

**Comment by danijar** [comment]
Okay cool. I probably tricked myself into believing it reacted faster to shorter key presses then.
