### ISSUE TITLE
Key sequences in addition to key chords?

### ISSUE THREAD

**Issue by DivineDominion** [koekeishiya/skhd#157]
I've been considering to add key sequence support to the program. I've peeked at the code and this would of course affect the config file parser and also the event listener. But before trying my luck at this, I'd like to ask first if this is something that's actually wanted :)

To get the terms straight: at the moment, skhd support _key chords_ like <kbd>Ctrl-Alt-X</kbd> that you have to hit at the same time. That's probably the most common shortcut command invocation method nowadays.  _Key sequences_ are more like how you can navigate app main menus in MS Windows: You can hit <kbd>Alt</kbd>, let go, then hit <kbd>E</kbd> for "Edit", then <kbd>C</kbd> for "Copy" inside the "Edit" menu. That's obviously slower than Ctrl-C, but this approach scales for less often used functiona (because you eventually run out of single modifier key + letter combos). See e.g. http://xahlee.info/kbd/banish_key_chords.html for reference.

What I have in mind: use <kbd>Cmd + Alt + M</kbd> as a toggle for "window management", then I can let go, and type any other key -- e.g. arrow keys to switch to adjacent windows, or <kbd>v</kbd> to split vertically, or whatever.

This is pretty uncommon on Mac in general, it seems, so what do y'all think?

**Comment by afarrell** [comment]
This is already possible by using modes. Take a look at https://github.com/nikhgupta/dotfiles/blob/osx/user/.config/skhd/skhdrc for a very nice example (you'll need a few scripts from his dotfiles in order for all features to work but the syntax should be clear).

**Comment by DivineDominion** [comment]
Thanks for the link, @afarrell! That looks great. I guess I can close the issue then :)

**Comment by adzenith** [comment]
The linked file has moved to here:
https://github.com/nikhgupta/dotfiles/blob/osx/config/skhd/skhdrc

**Comment by nikhgupta** [comment]
Thank you for mentioning my config :)

I am moving away from yabai, but for reference - adding a permalink to the above version: https://github.com/nikhgupta/dotfiles/blob/372799ce55f6fb26a5c6d6d230cfe0b5134cea40/config/skhd/skhdrc
