### ISSUE TITLE
command not found: chunkc

### ISSUE THREAD

**Issue by Victornovikov** [koekeishiya/skhd#162]
skhd doesn't work.
When I run it manually from CLI (and not through brew) I get the following error. 

`command not found: chunkc`

I am using example config. Here is associated key binding:
`shift + cmd - s : chunkc tiling::window --use-temporary-ratio -0.1 --adjust-window-edge south
`

What are the possible avenues to resolve this error?

**Comment by Victornovikov** [comment]
Somehow I assume that since yabai references skhd, then example config would work out of the box as well. :)

for posterity -- https://raw.githubusercontent.com/Julian-Heng/chunkwm-yabai-config/master/yabai/skhdrc

**Comment by maxvet** [comment]
@Victornovikov have you manage to find a solution? I'm having the same problem right now
