### ISSUE TITLE
Basic keybindings don't work but no errors appear

### ISSUE THREAD

**Issue by howdoimakethiswork** [koekeishiya/skhd#169]
I am testing skhd with the following config: 

``` 
cmd - b : open /Applications/Firefox.app
lctrl + lshift + lalt - t : echo "testing" 
```

It appears to be correct because `skhd -V` gives 

```
skhd: successfully created pid-file..
skhd: using config '/Users/username/.config/skhd/skhdrc'
hotkey :: #1 {
        mod: 'cmd'
        key: 'b' (0x0b)
        cmd: 'open /Applications/Firefox.app'
}
hotkey :: #2 {
        mod: 'lctrl'
        mod: 'lshift'
        mod: 'lalt'
        key: 't' (0x11)
        cmd: 'echo "testing"'
}
skhd: watching files for changes:
        /Users/username/.config/skhd/skhdrc
```

I am running this on Big Sur 11.2.3 with the M1 chip. I installed homebrew and tried both the intel and arm64 versions, with the same results. The "open /Applications/Firefox.app" command works if I type it manually, but I do not see any actions/errors/logs if I try using the hotkey. Note that I can only use `skhd -V` and `skhd -o` if the brew service is stopped, since otherwise the commands try to create another PID.

**Comment by stuartthomas25** [comment]
I am having a similar issue. It seems like after the Big Sur 11.2.1 update the skhd service fails. Apparently this is due to Secure Keyboard entry in Safari, Terminal or iTerm2 (even though I turned it off on all of them).

It seems like Apple added a new security feature that broke skid but this is just a hunch.

**Comment by stuartthomas25** [comment]
Somehow working now? I don't think I changed anything however the "Secure Keyboard Entry" on iTerm2 no longer shows a dash next to it.

**Comment by howdoimakethiswork** [comment]
Unfortunately this still isn't working for me. I just tried reinstalling after seeing your comment. 
I am running Kitty, compiled for arm64. Secure keyboard entry is unchecked.

**Comment by howdoimakethiswork** [comment]
Update: the problem seems be solved. I had Karabiner running and it was taking precedence, and because I swapped my ctrls and commands I had to reconfigure my skhdrc.
