### ISSUE TITLE
Doesn't seem to work on Big Sur 11.3.1

### ISSUE THREAD

**Issue by x-ji** [koekeishiya/skhd#172]
The service is started but is not responding to keypresses.

Trying to start it manually with `skhd -V` results in:

```
skhd: successfully created pid-file..
skhd: secure keyboard entry is enabled by (1662) 'iterm2'! abort..
```

Even though secure keyboard entry is disabled in the menu. It's the same for the built-in terminal app.

**Comment by x-ji** [comment]
After a restart of MacOS everything seems to be back to normal again.

**Comment by x-ji** [comment]
Will not close the issue though since @tami5 reported another error.

**Comment by kwstannard** [comment]
I tried restarting and skhd worked again for about 5 or 10 minutes before it stopped.

**Comment by kwstannard** [comment]
Seems like a lot of stuff has this issue. I just tried the sleep suggestion and that has fixed it for a few minutes now.

https://apple.stackexchange.com/questions/331557/is-there-a-way-to-fix-or-disable-secure-input

**Comment by robowraith** [comment]
Even that workaround (standby+ wkaeup) does not work on my macbook pro. I updated to BigSur 11.3.1 yesterday and immediately had problems. skhd did not respond, while yabai commands in the terminal stll still worked. Strangely (yesterday) skhd showed no errors when started with `skhd -V` but simply did not work. What made it work again was (strangely enough) to replace ~/.skhdrc with a blank one and redoing the same shortcuts as before. Maybe I had introduced a typo somewhere.  
Today skhd first wrked normally but suddenly, after a longer standby (30 min+) it stopped working and shows 
```
skhd -V
skhd: successfully created pid-file..
skhd: secure keyboard entry is enabled by (59706) 'iterm2'! abort..
```
And even in application which have a terminal but don't even have the "secure keybaord entry" option (AFAIK) like VScode:
```
skhd -V
skhd: successfully created pid-file..
skhd: secure keyboard entry is enabled by (24872) 'code'! abort..
```

If I can provide any (debug-) logs, please let me know.

**Comment by robowraith** [comment]
WHile standby + wakeup did not work, logout and login did (for now). I will report back if it fixes it (semi-permanently).

**Comment by robowraith** [comment]
And now it stopped working again. Last steps were to switch to an app (Signal Messenger Desktop app) and then trying to switch to desktop no. 1 (current shortcut "cmd + 1"). That shortcut is used in the Signal app to switch to the first conversation.

**Comment by ashkan-leo** [comment]
Sometimes the secure keyboard gets enabled globally and I lock the computer and log in back and the secure keyboard mode is disabled. This might be a helpful trick. 
BetterTouchTool shows warnings when the secure keyboard mode is enabled.
I thought someone may find these tricks useful.

**Comment by robowraith** [comment]
I can confirm that Locking and Unlocking works as a worg-around but BTT did not show any warning. Could you check if you have configured BTT to switch back to the old keybaord implementation if "Secure INput" gets enabled? This looks like a setting that could cause this warning.

**Comment by BackSeat** [comment]
I'm seeing this problem and I don't have BTT installed, so I don't think it's that.

**Comment by robowraith** [comment]
No, but the warning by BTT could be a good indicator about when it happens.

**Comment by spepakay** [comment]
I am on Big Sur 11.4. I tried everything (uninstall, sleep, restart, logout and login etc) but always keep getting "secure keyboard entry is enabled by iTerm2! abort..". Tried with other terminal emulators such as kitty and Terminal as well. Same result even though "Secure Keyboard Entry" is disabled.

Finally, I tried closing everything on the machine and ssh'd into it from another macbook pro. Guess what! Now I get "secure keyboard entry is enabled by Finder! abort.."!! 

What makes this more confusing is that skhd works fine the other macbook pro which is running Big Sur 11.4 too. 

Hope the above data point is helpful in debugging. At this point I gave. I have different software on the machine causing problems than on the one that works. Maybe one of them is causing this issue. Sometime over the weekend, I will try wiping  the rogue machine clean and see if skhd works with a fresh install

**Comment by aaraney** [comment]
I am having similar issues, namely `could not lock pid-file`. This may be related to #82? I tried the workaround suggested there and got `skhd` working by stopping the homebrew services (`brew services stop skhd`), removing the `pid` singleton (`rm /tmp/skhd_${USER}.pid`), and starting `skhd` in a non-daemonic form with `skhd` or `skhd -V` for more information. 

I also tried launching the daemon by loading the `skhd` `plist`  using `launchctl`, but that did not work either. 

For reproducibility, im using `skhd` v`0.3.5` on MacOS X 11.4.

**Comment by aaraney** [comment]
Ive played with starting a daemonic like process without using `launchctl` and I just got this to work:

`nohup skhd &`

This will not persist through restarts or logouts, but it does the trick for now. Basically this is starting `skhd` in the background and suppressing the `SIGHUP` signal. Meaning that when the parent process is closed, `Terminal` in this case, `skhd` is not killed. 

This might need to be moved to it's own issue or reopen #83 and move discussion there for context sake. @koekeishiya, when you get the chance, do you have any advice regarding this?

**Comment by aaraney** [comment]
Just as an update, the `could not lock pid-file` is a non-issue for me. This is shown when the daemon process has been started by `brew services` or equivalently, `launchctl load /path/to/skhd.plist`. So, you are trying to start a new instance of `skhd` when it is already running, and thus the first process has the lock on the `pid` file.

**Comment by JoelLau** [comment]
hi @x-ji , i faced the same issue and resolved it by following the instructions on [this blog post](https://www.samundra.com.np/skhd-suddenly-stopped-working-after-upgrade/1738).

you'll need to disable the Secure Keyboard Entry option on iTerm before restarting your machine

**Comment by gkzhb** [comment]
It seems you have to add skhd to `Input Monitor` which is located at `System Preferences` -> `Security & Privacy` -> `Input Monitoring`. You can just drag the file into the list to add it. Maybe you can check out whether this is the problem.

After adding to this list, my skhd finally works again on Mac Big Sur.

**Comment by alexaldrick** [comment]
@gkzhb This fixed it for me too! Thanks very much :)

**Comment by dittoalex** [comment]
Adding skhd to Privacy > Input Monitoring did not work for me on 11.5.2.  I tried many restarts and logging out between other troubleshooting avenues like manually writing the PID to the PIDFILE.

**Comment by ahmadassaf** [comment]
For me it took a couple of trials to understand what was happening.

First, I tried to run `skhd` using `/usr/local/opt/skhd/bin/skhd` rather than the `brew services start` or `restart`.

The command above gave the following error:
`skhd: secure keyboard entry is enabled by (2638) 'terminal'! abort..`

Now, despite having secure keyboard turned off on my terminal, it seemed that some app(s) is controlling that! so I ran `ioreg -l -w 0 | grep SecureInput`.

That will tell you the process ID (kCGSSessionSecureInputPID) of the application that has Secure Input enabled. You can then use `ps auxww | grep NNN` to find the process with the specified pid.

For me, the culprit turned out to be Keybase, uninstalling that gave me my skhd back!

[Source: Disable Secure Input](https://forum.keyboardmaestro.com/t/disable-secure-input/2410/3)

**Comment by ZakTaccardi** [comment]
per https://github.com/koekeishiya/skhd/issues/48#issuecomment-590531621

```
ioreg -l -w 0 \
    | perl -nle 'print $1 if /"kCGSSessionSecureInputPID"=(\d+)/' \
    | uniq \
    | xargs -I{} ps -p {} -o comm=
```
    
shows that `/System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow` is my problem.

Not sure how to fix other than a restart

**Comment by coltoneakins** [comment]
For those experiencing this issue, I found that Chrome (or in this case Chrome via Vivaldi Browser) on my mac triggered this when I was simply on a login page for a website (in some cases)

Yet, when I tried things to troubleshoot like: https://github.com/koekeishiya/skhd/issues/172#issuecomment-1028389241,
the `loginwindow` process was flagged as the culprit. But, killing this process or locking/unlocking my mac did not resolve this.

Every time I attempted to run `skhd -V` in my terminal to troubleshoot the program starting, I would get errors like mentioned here:
https://github.com/koekeishiya/skhd/issues/172#issuecomment-916281758
i.e. `skhd: secure keyboard entry is enabled by (2638) 'terminal'! abort..`
regardless of the terminal program I used (I have both hyper and alacritty).

Turned out the problem was just because I was on a login page for a web app in Chrome. Closing the tab with the login screen resolved the issue immediately and skhd started working right away.

Just something to consider....may be the cause of your problem as well.

**Comment by martinhjartmyr** [comment]
> For those experiencing this issue, I found that Chrome (or in this case Chrome via Vivaldi Browser) on my mac triggered this when I was simply on a login page for a website (in some cases)
> 
> Yet, when I tried things to troubleshoot like: [#172 (comment)](https://github.com/koekeishiya/skhd/issues/172#issuecomment-1028389241), the `loginwindow` process was flagged as the culprit. But, killing this process or locking/unlocking my mac did not resolve this.
> 
> Every time I attempted to run `skhd -V` in my terminal to troubleshoot the program starting, I would get errors like mentioned here: [#172 (comment)](https://github.com/koekeishiya/skhd/issues/172#issuecomment-916281758) i.e. `skhd: secure keyboard entry is enabled by (2638) 'terminal'! abort..` regardless of the terminal program I used (I have both hyper and alacritty).
> 
> Turned out the problem was just because I was on a login page for a web app in Chrome. Closing the tab with the login screen resolved the issue immediately and skhd started working right away.
> 
> Just something to consider....may be the cause of your problem as well.

Thanks!

I had the same problem with it telling me it was enabled by what ever terminal I was testing with. For me, it was not a Chrome tab that was the problem. It was the GitHub desktop app asking to unlock my key. After completing this prompt, skhd started to work instantly without reboot.

**Comment by kwstannard** [comment]
I should probably report that skhd has been working for me probably since shortly after my post above. Not sure what changed though.

**Comment by aaraney** [comment]
@x-ji, can this be closed now?

**Comment by x-ji** [comment]
Sure. I haven't used skhd in a while though from what I remember it seemed to work the last time I tried.

**Comment by paolomainardi** [comment]
To leave something useful for the next desperate: it happened to me with a Chrome extension configured to read "When you click the extension." I solved the issue by changing to be able to read on all sites.

<img width="601" alt="Screenshot 2023-12-14 at 19 09 21" src="https://github.com/koekeishiya/skhd/assets/8747/c9ecb1f1-6f60-4086-9e6d-dde745bc0525">
