### ISSUE TITLE
Can't get it to work | Catalina 10.15.7

### ISSUE THREAD

**Issue by wolfiiy** [koekeishiya/skhd#173]
Hello,

I tried using skhd multiple times without success. If I run it as a brew service, nothing happens. `skhd -V` outputs the following _every time:_
`skhd: successfully created pid-file..`
`skhd: must be run with accessibility access! abort..`

I already gave permission but it keeps asking for it anyway and giving the same error message each time I run `skhd -V` again. I'm using macOS Catalina 10.15.7. From what I read on [this](https://github.com/koekeishiya/skhd/issues/168) issue, I'm not supposed to get the same prompt over and over again.

If I run `brew services restart skhd` then `brew services list` it is said that the service is running, but nothing works (none of the shortcuts from my config do anything).

I tried rebooting, re-installing skhd, removing brew service and building from source, restarting the service, toggling permission, disabling permission -> rebooting -> enabling it again, but nothing seems to work. Permission is indeed granted from System Preferences, but the app thinks it isn't. Any idea as to why?

Don't hesitate to ask if you need any more information.

[Edit: formatting]
[Edit: updating to 10.15.7 (19H1030) seems to have fixed it somehow]

**Comment by irlevesque** [comment]
This happened to me after the latest Catalina security update (2021-003). When I run `skhd` interactively, it works fine. But when run via launchctl it appears to be unresponsive.

**Comment by bob-ortiz** [comment]
I have the same issue on Mojave 10.14.6. I've installed both from brew and building through git and none of the bindings work. I've tried a variety of config files, including the example one and it none seem to work. The code below is the simplest config I [found online ](http://hde-advent-2017.hatenadiary.jp/entry/2017/12/24/000000) but it didn't work either.

      # enter fullscreen mode for the focused container
      alt - f : chunkc tiling::window --toggle fullscreen
      
      # change focus between tiling / floating windows
      shift + alt - space : chunkc tiling::window --toggle float
      
      # change layout of desktop
      alt - e : chunkc tiling::desktop --layout bsp
      alt - s : chunkc tiling::desktop --layout monocle

**Comment by wolfiiy** [comment]
@irlevesque this is probably a very stupid question but just to be sure, when you said
> When I run skhd interactively, it works fine.
what did you mean?

Anyway, I updated to the latest Catalina (I had a security update since my post) and now it suddenly works fine. I just ran the service normally with `brew services start skhd` and now my config files work flawlessly. I leave the issue open for @bob-ortiz

**Comment by irlevesque** [comment]
@wolfiiy I meant that when I run `skhd` on the terminal, it works:

```
→ skhd -V
skhd: successfully created pid-file..
skhd: using config '/Users/ian.levesque/.config/skhd/skhdrc'
hotkey :: #8 {
	mod: 'shift'
	mod: 'alt'
	key: 'c' (0x08)
	cmd: 'open /Applications/Google\ Chrome.app'
}
...
skhd: watching files for changes:
	/Users/ian.levesque/.config/skhd/skhdrc
```

When it's run via `brew services`, here's what I get in the logs:

```
skhd: successfully created pid-file..
skhd: using config '/Users/ian.levesque/.config/skhd/skhdrc'
hotkey :: #8 {
    mod: 'shift'
    mod: 'alt'
    key: 'c' (0x08)
    cmd: 'open /Applications/Google\ Chrome.app'
}
...
hotkey :: #81 {
    mod: 'cmd'
    mod: 'ctrl'
    key: '8' (0x1c)
    cmd: 'yabai -m window --space 8'
}
hotkey :: #82 {
    m
```
and it gets stuck there.

**Comment by irlevesque** [comment]
I just upgraded to Big Sur (11.14) and still have this problem.

**Comment by bob-ortiz** [comment]
I did it all over again and, literally, restarted the services (both yabai and skhd) and it suddenly started working (really now quite sure what I did correctly but it now works). Thanks. @wolfiiy

**Comment by hatunike** [comment]
Had this same problem and just running 

`brew services start skhd -v`

asked me for accessibility support (which i had already previously enabled - but now it showed up twice the list and i enabled it for both entries. Once i did that it now just works again.

**Comment by mbeno** [comment]
Had the same issue and found that removing any old skhd entries from the accessibility database solved the issue.
Run ```sudo sqlite3 /Library/Application\ Support/com.apple.TCC/Tcc.db 'delete from access where client like "%skhd%"'```
Start skhd, grant it permissions and restart the service.

**Comment by Hritik14** [comment]
I had to uninstall and reinstall skhd. Also, I had an error in my rc file. After doing all three, got it to work.

**Comment by connorsimpsoncomposer** [comment]
> Had the same issue and found that removing any old skhd entries from the accessibility database solved the issue. Run `sudo sqlite3 /Library/Application\ Support/com.apple.TCC/Tcc.db 'delete from access where client like "%skhd%"'` Start skhd, grant it permissions and restart the service.

Having trouble running this command due to Error: stepping, attempt to write a readonly database (8). Any chance you know how I can fix this?

**Comment by mbeno** [comment]
Not sure, if you are trying to open it as root then there might be an issue with the db. You could se if there is a way to recreate it

**Comment by moosch** [comment]
@connorsimpsoncomposer I'm a little late to the party, but for the benefit of others the quotes are wrong in that sqlite snippet. Try `sudo sqlite3 /Library/Application\ Support/com.apple.TCC/Tcc.db "delete from access where client like '%skhd%'"`
