### ISSUE TITLE
zsh:1: command not found: chunkc

### ISSUE THREAD

**Issue by dps910** [koekeishiya/skhd#176]
I am unable to get this to work on macOS Big Sur 11.4. I have tried using chunkc.c from here https://github.com/kylef/chunkwm/blob/master/src/chunkc/chunkc.c, but when invoking chunkc in the terminal, I will get `chunkc: connection failed!`

```
david@iMac Desktop % ./chunkc tiling::window --focus east
chunkc: connection failed!
```
I am unsure how to fix this, please help if someone can :)

**Comment by Moosatronic** [comment]
How did you fix this?
