### ISSUE TITLE
Difference between - and +

### ISSUE THREAD

**Issue by michaelmcmillan** [koekeishiya/skhd#18]
Konge prosjekt! 

Got everything working, but can't seem to find the difference between these two operators.

````
 keysym = <mod> '-' <key> | <key>
 mod = 'built-in mod keyword' | <mod> '+' <mod>
````

From testing I've found that `shift - t` means holding down both keys at the same time. However, I don't understand what `shift + t` means? Can't seem to get the latter to work.

**Comment by koekeishiya** [comment]
`+` is used to chain modifiers, and `-` is used to indicate the literal coming after a modifier. There is no reason really for this.

so `cmd + shift - t` is basically "hold cmd and shift down, then press  t".

**Comment by michaelmcmillan** [comment]
Great, thanks! Any clue as to why `shift - t` works but `shift + t` doesn't?

**Comment by koekeishiya** [comment]
> + is used to chain modifiers, and - is used to indicate the literal coming after a modifier.

You can edit the parse-routine, specifially this line: https://github.com/koekeishiya/skhd/blob/master/src/parse.c#L166 to check for `Token_Plus` instead of `Token_Dash` and recompile, if you wish to use `shift + t` instead of `shift - t`.
