### ISSUE TITLE
Making iTerm window spawning smoother

### ISSUE THREAD

**Issue by edran** [koekeishiya/skhd#20]
If I simply replace Kitty with iTerm in the example config, I end up spawning a lot of new iTerm.app processes instead of simply creating new windows using the old process:

```
hyper - return : open -na /Applications/iTerm.app
```

I've therefore tried to use `osascript` to activate iterm and inject the command myself:

```bash
hyper - return : osascript -e 'tell application "iTerm" to activate' -e 'tell application "System Events" to tell process "iTerm" to keystroke "n" using command down'
```

however I don't get any visual feedback. The logs at `/usr/local/var/log/skhd/` are also empty.

This is also the case when I put the command in a bash script in `~/bin` and I try to run that with

```bash
hyper - return: bash ~/bin/my_script
```

FYI, I'm running High Sierra and I have installed skhd from homebrew.

**Comment by edran** [comment]
Uuuh, I realised what the issue is: osascript fails when hyper is still pressed.

I guess this is not quite a skhd bug then. Closing :)

**Comment by davelongdev** [comment]
is it possible to replace "iTerm2" with $1 in the above script and pass an app name as an argument?  i can't seem to get it to work.

thanks
