### ISSUE TITLE
How could I make it detect the "Semicolon Key" or other Punctuation?

### ISSUE THREAD

**Issue by Ushio-Clover** [koekeishiya/skhd#205]
**Take the semicolon as an example ：**

I have tried to edit it in my **skrdrc** like this :
` alt - ";" : <commands> `
and
` alt - ';' : <commands> `
But it couldn't work.

I don't know if this is because **the semicolon** and other punctuation symbols are keywords.

Forgive my poor English, please.

**Comment by syuni** [comment]
@Ushio-Clover `alt - 0x29 : <command>` works fine.

**Comment by jjant** [comment]
This would be nice to have in the readme 😄.

**Comment by Ushio-Clover** [comment]
@syuni Thank you very much for your help! I don't know exactly what type hotkey needs to be set. I look stupid. 😂
