### ISSUE TITLE
Everytime I restart my computer, SKHD asks for accessibility permissions

### ISSUE THREAD

**Issue by erikc96** [koekeishiya/skhd#216]
This started happening out of nowhere. Anyone else having issues with this?

**Comment by erikc96** [comment]
![Uploading image.png…]()

**Comment by osdiab** [comment]
looks like the image doesn't come though I keep getting this and SKHD doesn't seem to be running anymore ever since I updated my Mac.

<img width="466" alt="Screen Shot 2022-08-24 at 13 06 49" src="https://user-images.githubusercontent.com/1890926/186326592-19baeed0-4415-41a1-a9ec-397e0514943e.png">

**Comment by osdiab** [comment]
https://www.loom.com/share/2119d22bf01941c5afc870056d82c95e

**Comment by osdiab** [comment]
ok so i found out that if i just run the `skhd` command directly, and give accessibility permissions to my terminal (`kitty`), then that works. But if I try to start it with `brew services start skhd` then SKHD fails to actually respond to anything. Regardless, it still asks me for the accessibility access forever.

**Comment by ncko** [comment]
I had this issue where I was being asked over and over again to give skhd accessibility access, despite the fact that those permissions were already granted.

I have a (hopefully temporary) hacky fix to get it to run in the background. It only works when I open a zsh terminal, but I tend to work a lot in the zsh terminal so it works for me. I added this to my .zshrc file:

```
# hacky fix to get skhd to work in the background
# obviously it only works when you open terminal
# 100% there is a better way to do this
# https://github.com/koekeishiya/skhd/issues/216
function remove_skhd_lock_file_on_end() {
  local process_name="$(ps -p $SKHD_PID | tail -n 1 | awk '{print $4}')"

  while [[ $process_name == "skhd" ]]; do
    local process_name="$(ps -p $SKHD_PID | tail -n 1 | awk '{print $4}')"
    sleep 1
  done

  rm /tmp/skhd.lock
  rm /tmp/skhd_$(whoami).pid
}


if [ ! -f /tmp/skhd.lock ]; then
  echo "skhd is not running. Starting skhd..."
  echo "skhd is running" > /tmp/skhd.lock
  skhd &!
  SKHD_PID=$!

  remove_skhd_lock_file_on_end &
fi
```

**Comment by mbeno** [comment]
Try removing skhd from the accessibility list like so
```
sudo sqlite3 /Library/Application\ Support/com.apple.TCC/Tcc.db 'delete from access where client like "%skhd%"'
```

start skhd and it should show up again in the accessibility list, grant it permission and restart the service.

**Comment by koekeishiya** [comment]
Probably needs to be codesigned in newer versions of macOS.
