### ISSUE TITLE
How to use Return (i.e. not Enter)

### ISSUE THREAD

**Issue by marcjoha** [koekeishiya/skhd#22]
I don't seem to find a way to map the numpad's Return button. Is there a way?

**Comment by koekeishiya** [comment]
You can specify the keycode in hexadecimal.

The numpad return button usually has a keycode of: 0x4C

The following should launch Terminal when you hit cmd + numpad_return:

```
cmd - 0x4C : open -na /Applications/Terminal.app
```

Do note that hexcodes must be specified with the 0x prefix and uppercase A-F letters.

For a list of keycodes, you can go here https://github.com/koekeishiya/khd/issues/1#issue-177177268

**Comment by marcjoha** [comment]
Awesome, thanks!

**Comment by ryuta69** [comment]
@koekeishiya 
Hi, I would like to see that issue, however, issue seems to have gone...

Is there any same list of keycode anywhere?
