### ISSUE TITLE
Preloading bash environment

### ISSUE THREAD

**Issue by jcguu95** [koekeishiya/skhd#228]
I use the following in my skhd config to open `ranger`, a terminal-based file manager.

```
cmd - r : open -na alacritty --args -e bash ranger
```

Upon pressing `cmd-r`, an alacritty terminal is opened, with ranger loaded. However, that shell session doesn't have environment correctly loaded. In particular, asking ranger to `:shell echo $PATH` returns the bare

```
/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

while in a normal session the result would be

```
/Users/jin/Library/Python/3.10/bin:/usr/local/opt/openjdk/bin:/Users/jin/Library/Python/3.9/bin:/Users/jin/.local/bin:/Users/jin/.scripts:/Users/jin/.emacs.d/bin:/Users/jin/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/homebrew/bin
```

**Question:** How do I make sure programs opened by skhd load the correct environment?

**Comment by dekuofa1995** [comment]
I have same incorrect env variable PATH too. And I found skhd load and save the PATH when use `skhd --install-service`.
You can check the PATH variable at `$HOME/Library/LaunchAgents/com.koekeishiya.skhd.plist`

---
If you want update the variable, you can try `skhd --uninstall-service` and then `skhd --install-service`

**Comment by koekeishiya** [comment]
This used to be a problem when the launchd service was managed by brew services. The new services system implemented in skhd will correctly set the PATH variable in the service file.
