### ISSUE TITLE
Yabai space focus not working after brew upgrade

### ISSUE THREAD

**Issue by notflip** [koekeishiya/skhd#231]
I have the following setup in .skhdrc to move between my spaces using cmd + 1, 2, 3
```
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
```
However these stopped working after I ran brew upgrade, has anything changed?

**Comment by julientaq** [comment]
Got the same issue here, can’t use yabai anymore.

**Comment by julientaq** [comment]
@notflip 

just fixed it using this: 

https://www.samundra.com.np/skhd-suddenly-stopped-working-after-upgrade/1738

**Comment by jrock2004** [comment]
When I run `skhd -V` and I try to switch focus to another window, I see the following error

```
cannot focus space due to an error with the scripting-addition
```
