### ISSUE TITLE
using grave accent symbol (`) in keybindings

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/skhd#235]
I've noticed that when i use ` (grave accent) (the key on the left side of 1) in my keybindings the whole skhdrc stops working. Is there any way I can use that symbol? I need it to focus to the recent space. 

```cmd - ` : yabai -m space --focus recent && /usr/local/bin/polybar-refresh.sh```

**Comment by akuhnregnier** [comment]
I had the same issue. 
See #1. Notably, use `skhd --observe` to see which keycode is the right one.
In my case, I was also trying to use \` which ended up being `0x0A`, but this may be different for you.
You then use the resulting keycode like any other key, e.g.: `cmd - 0x0A : ...`

**Comment by azinsharaf** [comment]
Perfect! it is `0x32` for my keyboard. Works now!
