### ISSUE TITLE
No config file

### ISSUE THREAD

**Issue by snax08** [koekeishiya/skhd#236]
I can not find the default config file. I cant even find XDG_CONFIG_HOME and a web search is not helping.

**Comment by rebelopsio** [comment]
@snax08 👋🏻 hopefully I can help you out!

You can create a file at one of the locations [here](f1e7ca9556f7ba49f8a0be3e0b917dc0739da66b5760093a9a0f552798f5c92d)

- $XDG_CONFIG_HOME/skhd/skhdrc
- $HOME/.config/skhd/skhdrc
- $HOME/.skhdrc

You can use [this file](https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc) to start or you can use [my config](https://github.com/rebelopsio/dotfiles/blob/main/skhd/skhdrc) if you'd like. 

You probably don't have the `XDG_CONFIG_HOME` environment variable set. So don't fret. I keep my *skhd* config at `$HOME/.config/skhd/skhdrc` or you can define it in your `.zshrc` file as `export XDG_CONFIG_HOME=...`.

Let me know if I can help any further or if some of that didn't make sense.

**Comment by snax08** [comment]
Hi.

I didn't have XDG_CONFIG_HOME defined in my .zshrc file. I added this line to it;

XDG_CONFIG_HOME=/Users/"user"/

I also put my skhdrc file in 

~/.config/skhd/skhdrc


I had fixed this issue previously by adding the following lines;

`<array>`
`   <string>/usr/local/opt/skhd/bin/skhd</string>`
`      <string>--config=/Users/"user"/.config/skhd/skhdrc</string>`
`</array>`

into the;

/usr/local/Celler/skhd/"version number"/homebrew.mxcl.skhd.plist

to make the skhd service run with the `--config` arugment.
