### ISSUE TITLE
skhd: must be run with accessibility access!

### ISSUE THREAD

**Issue by Enak-Nalla** [koekeishiya/skhd#237]
Hi, I have a problem with skhd running ventura 13.1.

`skhd: must be run with accessibility access! abort..`

Was working before update. 
skhd is enabled in the accessibility menu, however when I start it asks for the permissions.
I can't enable because it is already enabled and this the program aborts.

Great project along with yabai 👍 
Hope you can help me fix this.

**Comment by Enak-Nalla** [comment]
Removed every trace of skhd and reinstalled. Not complaining anymore, log looks fine. 
However none of my shortcuts work. Secure keyboard entry is disabled.

**Comment by pigmej** [comment]
Same issue on my end.

**Comment by bashu** [comment]
offtopic, but both `yabai` and `skhd` available via MacPorts
