### ISSUE TITLE
Documentation Request: Link to chunkwm

### ISSUE THREAD

**Issue by brandondrew** [koekeishiya/skhd#239]
There are many references to `chunkc` in the example config file.  But googling finds almost nothing... pretty much just a blog post that leads to [another repo that gives a 404 error](https://github.com/koekeishiya/chunkwm).  

Could you please include a link to currently available source code?

Thanks!

**Comment by koekeishiya** [comment]
Rebranded as https://github.com/koekeishiya/yabai
