### ISSUE TITLE
Allow any combination of keys to be more flexible

### ISSUE THREAD

**Issue by ramblingenzyme** [koekeishiya/skhd#24]
Is it possible to do keybinds that don't involve only the traditional modifier keys?

For example, instead of having to rebind Caps to Hyper and not having anymore modifiers left, it would be far more flexible to be able to bind Caps to say...F20 and still have modifiers left.

**Comment by koekeishiya** [comment]
There is no support for key-remapping in *skhd*. *skhd* can only identify the official modifier flags provided by the OS.

If you want to have "fake" modifiers that do not interfere with the official modifier keys, you need a full custom solution that can simulate a modifier and also execute the requested command.

Anything to do with remapping should work as a kernel extension, which *skhd* won't do.

Your best bet at this time is probably Karabiner-Elements.

**Comment by ramblingenzyme** [comment]
Thank you, such disappointment OSX constantly delivers. The plan was to use
Karabiner-Elements to rebind Caps to F20, shame that there's no way to use
skhd with it.
