### ISSUE TITLE
zsh: command not found: chunkc

### ISSUE THREAD

**Issue by szafran98** [koekeishiya/skhd#246]
I already spent at least 5 hours to made skhd work, but i stuck. I want to configure macbook m1 via yabai and skhd. Yabai is working, skhd too i suppose, but keymaps didn't work. I restarted skhd with verbose parameter and on keypress i'm getting error `zsh: command not found: chunkc`. I can't find any solution, i've reinstalled both applications many times. I was even reading source code, but there is no any quote about this binary. What can i do in this case?

**Comment by supermar1010** [comment]
I think the example config contains commands for chunkc, which I suspect is another program like yabai. You don't have that installed so that's why you get the error. Just change the commands to for example `yabai -m space --focus next`
