### ISSUE TITLE
Warning: Calling plist_options is deprecated! Use service.require_root instead.

### ISSUE THREAD

**Issue by MylesBR** [koekeishiya/skhd#247]
When starting skhd on Mac OS Ventura 13.2.1

I am getting the warning

```
brew services start skhd
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the koekeishiya/formulae tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/skhd.rb:26
```
Please advise

**Comment by JaJaon** [comment]
Any idea if this is something that might break the functionality of Yabai or SKHD?

**Comment by dialtone** [comment]
Not sure if it does, but skhd from brew services doesn't work for me while it works fine when launched from command line

**Comment by niltrix** [comment]
Just replace "plist_options" with "service.require_root" in "/opt/homebrew/Library/Taps/koekeishiya/homebrew-formulae/skhd.rb"
<img width="647" alt="image" src="https://user-images.githubusercontent.com/1227187/225186466-73746747-7a04-47b6-a1c1-81a6422d224a.png">

**Comment by alanmicah** [comment]
> Just replace "plist_options" with "service.require_root" in "/opt/homebrew/Library/Taps/koekeishiya/homebrew-formulae/skhd.rb" <img alt="image" width="647" src="https://user-images.githubusercontent.com/1227187/225186466-73746747-7a04-47b6-a1c1-81a6422d224a.png">

I'm getting `undefined method `require_root' for nil:NilClass` when trying to start or restart services with brew

**Comment by szfkamil** [comment]
I'm also getting the error but I'm no longer using skhd and yabai, and uninstalled both. It pop-ups on every brew command I run on the terminal. https://share.cleanshot.com/XTZFp7B7

**Comment by koekeishiya** [comment]
Replaced brew services with a lunchd integration

```
# installs a user-specific launchd service plist file into ~/Library/LaunchAgents/com.koekeishiya.skhd.plist
# the program path used is the executable path of the invoked skhd command that installs the service
# the PATH env is set to the $PATH currently available to the invoked skhd command that installs the service
skhd --install-service

# removes launchd service file
skhd --uninstall-service

# loads the service, causing skhd to start running immediately, as well as upon login
# will attempt to install service automatically if it is not already installed, so --install-service is not really necessary to run manually
skhd --start-service

# restart the skhd service immediately
skhd --restart-service

# unload service, causing skhd to terminate immediately f it is running, and stop launching upon login
skhd --stop-service
```
