### ISSUE TITLE
No keybinds working (MacOS Ventura 13.2.1)

### ISSUE THREAD

**Issue by g1sbi** [koekeishiya/skhd#250]
I'm on a Macbook Air M1, Ventura 13.2.1, installed both yabai and skhd following the instructions, enabled accessibility settings and restarted both my computer and brew services multiple times. My config file is also the one provided in the repo, I did not touch it. Basically no keybinds are working, they seem to be overridden by the application underneath. I tried to create logs using `skhd --verbose` and stopping the service, but I receive an error saying I need to enable accessibility settings.

**Comment by EvanCarroll** [comment]
Did you rebuild skhd? There are patches on the code for the M1 not in a release.

**Comment by yoohahn** [comment]
I installed yabai + skhd on my M2 Air yesterday from brew. Only "issue" is the `plist_options` deprecation warning for both yabai and skhd.

And works as expected here.

**Comment by melMass** [comment]
Same here, both yabai and skhd give that warning but they work fine.

**Comment by alanmicah** [comment]
I'm having the same issues. skhd keybindings have stopped working. But Yabai still seems to be working.

**Comment by Dave1112** [comment]
my keybinds just stopped working.  not sure why?  running montery 12.6.3

**Comment by g1sbi** [comment]
Update: I managed to run `skhd -V` succesfully and the error I now get when running a hotkey is:
`zsh:1: permission denied: /Applications/Firefox.app/`

**Comment by g1sbi** [comment]
Marking this as solved. The config had two separate issues that made me think that no keybinds worked.
- I didn't know that to open an app you needed to execute all the way inside `/Contents/MacOS/example`
- I didn't notice the example config used a different WM from mine
Sorry for the confusion!
