### ISSUE TITLE
yabai + skhd not working

### ISSUE THREAD

**Issue by alexgulbrandsen** [koekeishiya/skhd#253]
Hello! 
I have installed yabai and skhd, but I can´t get the keyboard shortcuts to work. What might be the issue?

**Comment by root-host** [comment]
same here skhd not working
my config is in home folder and i even try in .config/skhd/skhdrc
same think skhd don't work

mac os 13.2.1

**Comment by YootTanA** [comment]
Can you show me your yabairc and skhdrc file?

**Comment by root-host** [comment]
> Can you show me your yabairc and skhdrc file? Or Can you try `brew services restart yabai` and `brew services restart skhd` after you edited your rc file?
> 
> I just installed them both minutes ago and they worked perfectly fine.

i used this tutorial,yabai works fine just skhd don't work

**Comment by YootTanA** [comment]
This is the same configuration I am using. 
I have tried   alt - <h,j,k.l> to move to the target desktop and it works.
 
Which features of skhd you have tried and it did not work?

I'll try further and let you know if it don't work too.

**Comment by root-host** [comment]
now it's working, i remove skhdrc file uninstalled skhd rebooted mac stopped the yabai installed skhd make a new skhdrc in .config/skhd started yabai and skhd and now skhd working.

**Comment by YootTanA** [comment]
That's great.

**Comment by YootTanA** [comment]
@alexgulbrandsen If your problem still remains please feel free to let me know.

**Comment by root-host** [comment]
> That's great.

Thanks,
one more question, what is the command in skhdrc to spawn new terminal?

**Comment by YootTanA** [comment]
Well, you can create a script and configure skhdrc to point at it. 

https://github.com/koekeishiya/skhd/issues/20

**Comment by teelahti** [comment]
MacOS 13.2.1 broke skhd + yabai for me, too. Works after restart, no need to re-install skhd. I assume there is some change in MacOS that breaks skhd.

**Comment by alexpopov** [comment]
> MacOS 13.2.1 broke skhd + yabai for me, too. Works after restart, no need to re-install skhd. I assume there is some change in MacOS that breaks skhd.

Can confirm restarting fixes it. Neither yabai nor skhd worked. I briefly attached a debugger and found that `skhd` would segfault because [`carbon.process_name` was null](https://github.com/koekeishiya/skhd/blob/master/src/skhd.c#L165) and eventually gets dereferenced. 

But _why_ that happened for one boot cycle after updating to 13.2.1 I don't know.

**Comment by alexgulbrandsen** [comment]
> @alexgulbrandsen If your problem still remains please feel free to let me know.

I´ve got it to work, but after a restart it does not work anymore. Any suggestions?

**Comment by YootTanA** [comment]
Would you mind show me your scripts?

**Comment by szfkamil** [comment]
I've been having the same issue with skhd not working no matter what, but yabai working just fine. Ventura 13.3

I uninstalled skhd, killed yabai, and am about to install skhd, and reboot my computer.

> now it's working, i remove skhdrc file uninstalled skhd rebooted mac stopped the yabai installed skhd make a new skhdrc in .config/skhd started yabai and skhd and now skhd working.

**Comment by darer** [comment]
MacOS Ventura 13.3. Yabai works fine. Skhd service is started by brew, but none of the shortcuts work. Restarting the computer didn't help. Tried reinstalling and everything, but no luck.

**Comment by szfkamil** [comment]
> 

Basically, the same thing here. It's the issue with Ventura, then. It's now a matter of 

- do we wait
or..
- is there a workaround someone figures out?

**Comment by alexpopov** [comment]
> > MacOS Ventura 13.3. Yabai works fine. Skhd service is started by brew, but none of the shortcuts work. Restarting the computer didn't help. Tried reinstalling and everything, but no luck.
> 
> Basically, the same thing here. It's the issue with Ventura, then. It's now a matter of
> 
> * do we wait
>   or..
> * is there a workaround someone figures out?

Have you tried starting skhd manually, instead of using brew? That may print out some useful diagnostic information. 

* Create a new temporary config with just this line:
```
default < 7 : open 'http://google.com' 
```

This will cause the browser to open Google any time you press '7'. 

Run skhd manually with your temporary config, e.g.:

```
# use your temporary config
$(which skhd) --config /tmp/skhdrc_temp
```

Press '7' to see if Google opens. 

Also, please double check that `skhd` appears in the list of System Settings > Privacy & Security > Accessibility

**Comment by surt666** [comment]
I have the same problem that skhd is not working on 13.3. Used yabai from HEAD and that seems to work fine, to get around the `Calling plist_options is deprecated` bug. I also complied skhd from source and tried that, but no luck. The minimal example above also doesn't work , but no errors anywhere I can find.

**Comment by tknapen** [comment]
> > MacOS Ventura 13.3. Yabai works fine. Skhd service is started by brew, but none of the shortcuts work. Restarting the computer didn't help. Tried reinstalling and everything, but no luck.
> 
> Basically, the same thing here. It's the issue with Ventura, then. It's now a matter of
> 
> * do we wait
>   or..
> * is there a workaround someone figures out?

Same here, just adding some info; running skhd -o  in the terminal does register the keys (such as alt, etc.) and returns key codes. However, in any app, pressing alt - anything just returns non-ASCII symbols as if skhd is not "catching" the modifiers/keys before the system handles them.

**Comment by lightbluepoppy** [comment]
I spent hours trying to debug skhd not working at all. When I execute `skhd -V` it shows the error below.

```rc
skhd: successfully created pid-file..
skhd: using config '/Users/orcinus/.config/skhd/skhdrc'
hotkey :: #47 {
#47:1 undeclared identifier
skhd: watching files for changes:
	/Users/admin/.config/skhd/skhdrc
```
I just copy&pasted the code in the example. I couldn't figure out  **how to find the exact hotkey in the skhdrc file** 

https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc

Could someone help me out debugging this, and possibly update the example?

**Comment by grandmasteri** [comment]
I'm getting a similar issue as above. I had yabai running and installed skhd (`brew install koekeishiya/formulae/skhd`). Then ran ` skhd --start-service` as instructed by the *README* and got this error:

> Load failed: 5: Input/output error
> Try running `launchctl bootstrap` as root for richer errors.

When I run `skhd -V` I get this output:

> skhd: could not lock pid-file! abort..

I've tried:
- restarting my computer
- Trying to start *skhd* after **1)** turning off *yabai* (`brew services stop yabai`), restarting *yabai* (`brew services restart yabai`), and manually turning *yabai* off and on (`brew services stop yabai; brew services start yabai`).

I am on *MacOS Ventura 13.3.1 (a)* if that helps at all.

**Comment by pencilcheck** [comment]
I'm getting syntax error
```
/usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/skhd.rb
```
Error: skhd: /usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/skhd.rb:28: syntax error, unexpected <<, expecting end
<<<<<<< Updated upstream
^~
/usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/skhd.rb:29: syntax error, unexpected ===, expecting end
=======
^~~
/usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/skhd.rb:98: syntax error, unexpected >>, expecting end
>>>>>>> Stashed changes
```

I had to run `brew update-reset [repo url]` to fix the issue.

**Comment by koekeishiya** [comment]
> Load failed: 5: Input/output error
Try running launchctl bootstrap as root for richer errors.

https://github.com/koekeishiya/skhd/issues/264#issuecomment-1532968259

**Comment by koekeishiya** [comment]
On newer versions of macOS the binary likely needs to be codesigned.

**Comment by darer** [comment]
> On newer versions of macOS the binary likely needs to be codesigned.
> 
> For yabai I ship pre-compiled binaries that are already codesigned. skhd does not come with pre-built binaries and must be codesigned by the user.

Do you have any plans to ship pre-compiled binaries for skhd as well? And if you don't, could you (or anyone else) explain how we can codesign the binary?

**Comment by koekeishiya** [comment]
I would like skhd to work the same was as yabai (in terms of project management, changelogs, releases etc), but I am not particularly active these days; doing such a restructure takes quite a bit of time, so yeah don't get your hopes up.

For codesigning you can follow the introduction on this page from the yabai wiki, but replace yabai with skhd instead: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

**Comment by AJAYK-01** [comment]
just deleting the skhd lock file in /private/tmp and starting skhd again worked for me

**Comment by lmBored** [comment]
> just deleting the skhd lock file in `/private/tmp` and starting skhd again with the command `nohup skhd &` worked for me

you mean the skhd_master.pid right?

**Comment by AJAYK-01** [comment]
skhd

> > just deleting the skhd lock file in `/private/tmp` and starting skhd again with the command `nohup skhd &` worked for me
> 
> you mean the skhd_master.pid right?

depends on your username, it would be like ```skhd_<username>.pid``` , so if your username is master, then yes

**Comment by golioss1886** [comment]
> just deleting the skhd lock file in `/private/tmp` and starting skhd again with the command `nohup skhd &` worked for me

It works for me. Thank you.

**Comment by JagrajBenipal** [comment]
Hey, earlier my skhdrc used to work, but it isn't working anymore. I don't think I changed anything in particular. I deleted, stopped, reinstalled both yabai and skhd, but of no use. Yabai works perfectly fine, but I am not able to use the keymaps I defined in my skhdrc. The location is ~/.config/yabai/yabairc and ~/.config/skhd/skhdrc. Below is my skhdrc file:

# Your existing keybindings below
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

Now even if I restart both yabai and skhd, the mappings still don't work. Instead I get those symbols (ex. alt+j gives ∆).

I even tried replacing alt with any other key like ctrl, but it also didn't work. I also followed josean's tutorial about yabai again, that also didn't help.

**Comment by shinyuta** [comment]
This was also a problem for me on Sonoma 14.5 AYAYK-01's reply worked for me. Deleting the file in tmp and using the command. Now all the hotkeys work perfectly and it also fixed the skhd pop-up for accessability. 👍

**Comment by Malachite40** [comment]
Doesn't seem to fix the issue for me :(
