### ISSUE TITLE
skhd command not found: yabai

### ISSUE THREAD

**Issue by yarecryb** [koekeishiya/skhd#261]
yabai and skhd are both installed through brew but none of the yabai keyboard shortcuts work with skhd. Running skhd -V and trying the shortcuts shows 

`zsh:1: command not found: yabai`

Any ideas for a fix?
Thanks!

Edit: Other kinds of skhd shortcuts work

**Comment by qtaped** [comment]
You should ask on the yabai page. This is not related to skhd.
Run `yabai` command directly in your terminal and you'll see the same message. You probably miss something when you have installed yabai.

**Comment by koekeishiya** [comment]
Fix the $PATH env that is available to the skhd process.
