### ISSUE TITLE
plist_options deprecated (macOS ventura)

### ISSUE THREAD

**Issue by nilanjan** [koekeishiya/skhd#262]
brew-based installation on Macos showing the following warning for skhd and yabai.

Warning: Calling plist_options is deprecated! Use service.require_root instead.

**Comment by kalvinyuu** [comment]
i got it when i restarted skhd

**Comment by koekeishiya** [comment]
Replaced brew services with a launchd integration

```
# installs a user-specific launchd service plist file into ~/Library/LaunchAgents/com.koekeishiya.skhd.plist
# the program path used is the executable path of the invoked skhd command that installs the service
# the PATH env is set to the $PATH currently available to the invoked skhd command that installs the service
skhd --install-service

# removes launchd service file
skhd --uninstall-service

# loads the service, causing skhd to start running immediately, as well as upon login
# will attempt to install service automatically if it is not already installed, so --install-service is not really necessary to run manually
skhd --start-service

# restart the skhd service immediately
skhd --restart-service

# unload service, causing skhd to terminate immediately f it is running, and stop launching upon login
skhd --stop-service
```

**Comment by dkovacevic15** [comment]
A heads-up for a breaking change and a migration period would've been nice. This project has 4k stars and is one of the most popular WMs for Mac OS. I signed into work today, ran `brew upgrade` after a while and my whole system went haywire.

**Comment by koekeishiya** [comment]
skhd is not a WM, although that is not related to your point.

A heads up was given 3 weeks ago in the `yabai`repository (which is the actual window manager), which also mentions this in the caveat section printed after installing with brew.

I agree that skhd is not managed properly with changelogs and documentation in general, and I would like that to work the same was as yabai eventually, but as you can see I am not particularly active these days; doing such a restructure takes quite a bit of time.
