### ISSUE TITLE
`skhd` is showing notifications, but it doesn't appear in the Notifications system menu so that I control the behavior

### ISSUE THREAD

**Issue by farzadmf** [koekeishiya/skhd#265]
Hi, pretty much what the title says.

I think this was a recent change to `skhd`: previously, I started `skhd` using `brew services`, but seems like I now need to do `skhd --install/start service` etc.

The isssue is that I want to disable the notifications, but `skhd` doesn't appear in the list when I go to `Settings > Notifications`.

---

MacOS version: Ventura 13.3.1 (a)

**Comment by koekeishiya** [comment]
removed notifications and pushed v0.3.7.
