### ISSUE TITLE
v0.3.6 and v0.3.7: lose peripherals following brew upgrade

### ISSUE THREAD

**Issue by jasisk** [koekeishiya/skhd#266]
When upgrading from v0.3.5 → v0.3.6 and v0.3.6 → v0.3.7 (both times via homebrew), I've lost the ability to type or register mouse clicks immediately following the reinstall. When I've lost the ability to type and click, I've tried plugging in / connecting via bluetooth additional mice and keyboards but with no resolution. At that point, the only action I can take is force shutdown the machine.

It's unclear to me why this is happening but one (obvious) observation is that the accessibility permission doesn't stick since the bin path changes. After I shutdown, I'm correctly prompted to open the accessibility permissions and everything works again.

Otherwise, (pure speculation) is it possible that brew is unceremoniously killing the skhd process, preventing it from releasing peripherals or something? Maybe the brew service handling terminated the service gracefully before?

(In any case, thanks for all the work you do! Much appreciated!)

**edit**: also happened for v0.3.8 though I found a workaround without having to force-restart this time. I was able to hit shift+cmd+Q to logout, then log back in and set the permissions for skhd and yabai. Unclear if this shortcut would have worked in the previous versions or if something was different this time.

**Comment by koekeishiya** [comment]
The macOS permissions model works the way it does; stop the service before running upgrade.
