### ISSUE TITLE
Brew service no longer exists on latest skhd

### ISSUE THREAD

**Issue by grepsedawk** [koekeishiya/skhd#267]
➜  ~ brew services restart skhd
Error: Formula `skhd` has not implemented #plist, #service or installed a locatable service file
➜  ~ skhd --version
skhd-v0.3.7

**Comment by qtaped** [comment]
Same here. After updating and upgrading brew packages. (Apple Silicon / last macOS monterey)

As a workaround, you can start skhd with launchd running `skhd --start-service`

In my case I first get an error `skhd: service file '/Users/user/Library/LaunchAgents/com.koekeishiya.skhd.plist' is not installed! attempting installation..`and had to restart it `skhd --restart-service`.

Hope it can help.

**Comment by dautroc** [comment]
@qtaped it doesn't work for me, try to restart it but got the same error
`skhd: service file '/Users/eh/Library/LaunchAgents/com.koekeishiya.skhd.plist' is not installed! abort..`

Btw I got the same error when trying to start yabai as well, here is what I have tried:
```
❯ brew services start yabail

Error: Formula "yabai" has not implemented #plist, #service or installed a locatable service file
``` 
--------------------------------------------------------------------
Also try this
```
❯ yabai --start-service

yabai: service file '/Users/user/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
yabai: service file '/Users/user/Library/LaunchAgents/com.koekeishiya.yabai.plist' could not be installed! abort..
```

**Comment by lcjnil** [comment]
try `skhd --stop-service` and `skhd --start-service`, may check log file for more information

**Comment by Alkindi42** [comment]
You can try to run `skhd --install-service` or/and check if the directory `~/Library/LaunchAgents` exists. If it's not the case : `mkdir ~/LIbrary/LaunchAgents` and run again `skhd --start-service`

**Comment by vizcay** [comment]
> Same here. After updating and upgrading brew packages. (Apple Silicon / last macOS monterey)

- The exact same happened to me, but I cannot get it to work.

- `brew services` is not listing `skhd` anymore.

- When I try
```
$ skhd --start-service
skhd: service file '/Users/pablo/Library/LaunchAgents/com.koekeishiya.skhd.plist' is not installed! attempting installation..
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
```

- I've tried uninstalling `skhd` and removing those `plist` files manually for fresh start.

- Tried all combinations of `--stop-service`, `--start-service` and `--restart-service`.

- Added it to accessibility list again.

- I was able to get it started from `launchctl` but is not working:

```
$ ps aux | grep skhd
pablo             1682   0.0  0.0 408628368   1648 s000  S+   11:08AM   0:00.00 grep skhd

$ launchctl load ~/Library/LaunchAgents/com.koekeishiya.skhd.plist

$ ps aux | grep skhd
pablo             1649   0.0  0.1 408880208  17168   ??  S<   11:07AM   0:00.07 /opt/homebrew/bin/skhd
pablo             1682   0.0  0.0 408628368   1648 s000  S+   11:08AM   0:00.00 grep skhd
```

- Running it manually neither works.

Why why why 😢

**Comment by koekeishiya** [comment]
> Load failed: 5: Input/output error

This is a `launchctl` gimmick, and other people have also experienced the same error using brew services.

Moved away from brew services because of https://github.com/koekeishiya/yabai/issues/1619

**Comment by executionByFork** [comment]
> > Load failed: 5: Input/output error
> 
> This is a `launchctl` gimmick, and other people have also experienced the same error using brew services.
> 
> Moved away from brew services because of [koekeishiya/yabai#1619](https://github.com/koekeishiya/yabai/issues/1619)

I am currently getting `Load failed: 5: Input/output error` when trying to start skhd using `skhd --start-service` so I am not sure this is actually a brew issue?

**Comment by vizcay** [comment]
> > > Load failed: 5: Input/output error
> > 
> > 
> > This is a `launchctl` gimmick, and other people have also experienced the same error using brew services.
> > Moved away from brew services because of [koekeishiya/yabai#1619](https://github.com/koekeishiya/yabai/issues/1619)
> 
> I am currently getting `Load failed: 5: Input/output error` when trying to start skhd using `skhd --start-service` so I am not sure this is actually a brew issue?

I was getting the exact same error.. only god knows how it solved for itself after touching a million things. Good luck.
