### ISSUE TITLE
v0.3.7 not working

### ISSUE THREAD

**Issue by williamhCode** [koekeishiya/skhd#268]
I upgraded to v0.3.7 and brew services doesn't work anymore, so i tried `--start-services` and it returned this:
```
~ ❯ skhd --start-service
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
```

I realized I already had it running, but none of the shortcuts are working

**Comment by williamhCode** [comment]
i forgot to update yabai's scripting addition after upgrading it mybad

**Comment by FrancoLab** [comment]
Can you please let me know what you did and how you resolved this issue? I do not have yabai installed. Is that a problem? 

`
❯ skhd --start-service
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
`

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/skhd/issues/264
