### ISSUE TITLE
No skhd service

### ISSUE THREAD

**Issue by itaysharir** [koekeishiya/skhd#270]
I installed skhd today after not having it installed for around 6 months, and when i ran
```brew services start skhd``` I got this: ```Error: Formula `skhd` has not implemented #plist, #service or installed a locatable service file```

**Comment by sean-hale-dev** [comment]
Same as #267

**Comment by itaysharir** [comment]
I'm dumb. It's supposed to be like that, it changed since the last time i used it to  ```skhd --start-service```
