### ISSUE TITLE
Assumes home directory is /Users/$(whoami)

### ISSUE THREAD

**Issue by chorismate** [koekeishiya/skhd#276]
Due to something related to Migration Assistant, my username is `choris` but my home directory is `/Users/admin_1`. This causes Yabai to fail when attempting to create the launch agent.

Symlinking `/Users/choris` to `/Users/admin_1` fixes this issue, but is a workaround I'd rather avoid.

<img width="1036" alt="Screenshot 2023-06-01 at 17 05 17" src="https://github.com/koekeishiya/skhd/assets/102564844/78079ced-2333-44b9-9cc1-1ce562f5484e">

### Text of error
```
yabai: service file '/Users/choris/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
yabai: service file '/Users/choris/Library/LaunchAgents/com.koekeishiya.yabai.plist' could not be installed! abort..
```

### Steps to reproduce
- Create a user with a home directory that is *not* the output of `echo /users/$(whoami)`.
- Install and run Yabai.

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#505---2023-05-21

**Comment by chorismate** [comment]
Oops, I'm on version 5.0.4 because my package manager (Nix) hasn't updated the Yabai package.

Sorry!
