### ISSUE TITLE
Can't run skhd: skhd: could not lock pid-file! abort..

### ISSUE THREAD

**Issue by szfkamil** [koekeishiya/skhd#300]
I am unable to run skhd properly nor change the directory:

```
skhd -c ~/.skhdrc
skhd: could not lock pid-file! abort..
```

I've tried several solutions, which include:

-  `brew uninstall skhd` & doing a fresh install as specified in the documentation
- Creating a new blank skhdrc file

I tried to delete the the pid files
```
pgrep -fl skhd
546 /opt/homebrew/bin/skhd
❯ kill 546
❯ ❯ pgrep -fl skhd
zsh: command not found: ❯
```

I checked if the pid file exists on my system and if the permissions may have issues, it seems they don't.
```
ls /tmp/skhd.pid
ls: /tmp/skhd.pid: No such file or directory
❯ ls -ld /tmp
lrwxr-xr-x@ 1 root  wheel  11 Sep  2 09:35 /tmp -> private/tmp
❯ ls -ld /private/tmp
drwxrwxrwt  11 root  wheel  352 Sep 24 09:38 /private/tmp
```

To my understanding then it's either something else on my system or a bug.

Environment:
MacOS Ventura 13.5.2

**Comment by tjex** [comment]
Have you given access to skhd in system settings -> privacy and security -> accessibility?

**Comment by szfkamil** [comment]
> Have you given access to skhd in system settings -> privacy and security -> accessibility?

I don't remember how, but I've solved the issue and forgot to close it. Thanks!
