### ISSUE TITLE
Unbinding macOS hotkey

### ISSUE THREAD

**Issue by appleseedexm** [koekeishiya/skhd#307]
So my actual problem is macOS using emacs hotkeys for some stuff, i.e. `Ctrl - H` to `backspace` in specific apps / fields. I have some universal tmux / nvim bindings that I use in all systems, also via ssh. All of these system hotkeys are basically ruined and I refuse to change all my linux environments just because of macOS. 

I wanted to try to circumvent the macOS hotkey with skhd, but both just remapping it to the same hotkey and using `~` didnt work, the later as expected, the first just didnt to anything, probably to not trigger an infinite loop:
`ctrl - h : skhd -k "ctrl - h"`

```
ctrl - h [
  "alacritty" ~
  *          : skhd -k 'cmd - h'  # this was just for testing, I would rather just have it do nothing everywhere where the application doesnt know this key combination
]
```

Anyone got an idea how this could be resolved with skhd? Or maybe a way to patch it (I would love to look into it if its not yet possible)?

**Comment by trisduong** [comment]
same problem :((

**Comment by tjex** [comment]
I'm a little confused what your needing. The title suggests unbinding the macos `cmd` key? 
modifier keys can't be unbound / rebound with skhd.

but you're addressing the `ctrl` key for bindings. The ctrl key is the same across linux / macos. So I'm unsure why there is a conflict in your keybinds then?.. 

Maybe you need to look at binding `ctrl - h` in your macos shell config instead of looking to skhd?

**Comment by appleseedexm** [comment]
The title was about this being a built-in hotkey in macOS (see document shotcuts https://support.apple.com/en-us/HT201236).

This hotkey is persistent for me in every shell and every terminal emulator, and since it is a system wide hotkey by macOS, I never thought that this would be a shell issue. Tunnelvision ftw. 

Turns out `bindkey -r "^H"` would remove this particular binding in the current shell, which, after this many hours, is all I need. 
The general system-wide hotkey still persists for specific fields, so I dont know if someone else would still benefit from a general solution with skhd, but for me this is more than enough, thanks!
