### ISSUE TITLE
All keybindings ignored when iTerm2 is focused

### ISSUE THREAD

**Issue by pyrho** [koekeishiya/skhd#31]
I've tried most key bindings provided in the sample config file, and all of them are ignored when iTerm is focused.
Everything works fine when another app is focused.

**Comment by pyrho** [comment]
Randomly disabled "Secure Keyboard Entry" from the settings, then looked for that in the opened issues for Chunkwm and found the following:

> You have most likely activated Secure keyboard entry in iTerm. There is usually an entry to enable / disable this in the menubar.

🤦‍♂️ 

Sorry for the noise.. 
I would suggest adding this to ChunkWM's FAQ.

**Comment by koekeishiya** [comment]
This is already mentioned in the readme for skhd. I don't think it belongs in the chunkwm repo because these are two completely separate programs that are not necessarily bundled together.

**Comment by pyrho** [comment]
Oh right I missed that.
But I guess I did not know _Secure Keyboard Entry_ was the cause of my issue, so I couldn't really search for it.

Maybe it's just me, but I spent a lot of time on {google, stackoverflow, github issues} trying to find the cause of my issue, and really solved it by pure luck.

I think I accidentally activated Secure Keyboard Entry while I was trying key bindings for chunkwm (via skhd).

Thanks for your hard work on all of this !

**Comment by BovineEnthusiast** [comment]
Hey, maybe the following line should be changed to specify that it's referring to the terminal apps?

> Secure Keyboard Entry must be disabled for skhd to receive key-events.

to

> Secure Keyboard Entry in your terminal app (e.g. iTerm) must be disabled for skhd to receive key-events.

I had accidentally turned it on and couldn't find out why for a while

**Comment by dominiklohmann** [comment]
Secure Keyboard Entry is not a feature that is exclusive to terminal applications.
