### ISSUE TITLE
Cannot start as service

### ISSUE THREAD

**Issue by bekirisgor** [koekeishiya/skhd#317]
Hey,

After skhd crash it stopped and i cant start it as service

Starting via brew is giving this error: 
```Error: Formula `skhd` has not implemented #plist, #service or installed a locatable service file```

Starting via ```skhd --start-service``` asking for permission every time even i permit it. 

I have checked other issues there is similar issues but couldnt find any helpful answer. 

Currently using it as daemon ```skhd&```

Current Versions
- Macos Sonoma  14.1.1 (23B81)
- skhd-v0.3.9

**Comment by koekeishiya** [comment]
The binary needs to be codesigned; follow the instructions here, but replace yabai with skhd

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

**Comment by bekirisgor** [comment]
Thanks for the help, really appreciated for this.
