### ISSUE TITLE
What should I do? 

### ISSUE THREAD

**Issue by Alohaoh** [koekeishiya/skhd#320]
![Screenshot 2023-11-30 at 4 23 04 PM](https://github.com/koekeishiya/skhd/assets/106124331/6d248c8b-80f7-4fbe-9985-9a0782e966f8)
and when i use command skhd --start-service, and right away use brew services stop skhd, i got this: Warning: Services `skhd` is not started.

**Comment by tjex** [comment]
`brew services` is a "user friendly" way to interact with `launchd` services. 
`skhd` handles it's own launchd service with `--start-service` etc. 

So you dont actually need to use both - in fact I'm pretty sure the recommended way to interact with the service for skhd is via skhd itself.

so what you should do: execute `skhd --start-service` and see if skhd is working. If you want to stop the service, execute `skhd --stop-service`. 

Also, in future, a more descriptive issue title will not only be more enticing for people to engage with, but it will also help others who have a similar issue in the future to find a solution to their current problem (and to avoid lodging an issue themselves).

Something like "cannot start skhd service with brew" or if no descriptive title comes to mind, then the error message you encounter "Formula skhd has not implemented `#plist`, `#service` ... etc"
