### ISSUE TITLE
Key press only registered when `skhd --profile` is running

### ISSUE THREAD

**Issue by rimi-itk** [koekeishiya/skhd#322]
I'm running macOS Sonoma Version 14.2 and **skhd** (seems) to only register key presses when `skhd --profile` is running.

Anybody experiencing similar issues?

Running `skhd --profile` is a workaround that I'm happy to live with given the value of **skhd**.

```console
$ system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.2 (23C64)
      Kernel Version: Darwin 23.2.0
      Boot Volume: …
      Boot Mode: Normal
      Computer Name: …
      User Name: …
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 35 minutes, 24 seconds
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 8-Core Intel Core i9
      Processor Speed: 2,3 GHz
      Number of Processors: 1
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
      Hyper-Threading Technology: Enabled
      Memory: 32 GB
      System Firmware Version: 2020.61.1.0.0 (iBridge: 21.16.2057.0.0,0)
      OS Loader Version: 580~1053
      Serial Number (system): C02DD3E0MD6T
      Hardware UUID: 6F015C4A-A3F9-59F4-8428-C8B0305B5F8E
      Provisioning UDID: 6F015C4A-A3F9-59F4-8428-C8B0305B5F8E
      Activation Lock Status: Disabled

$ skhd --version
skhd-v0.3.9
```

**Comment by zoominGiladSher** [comment]
Hi @rimi-itk , what was your solution to this? I see you marked this as completed without additional context. I'm facing the same problem so would appreciate your input. Thank you.

**Comment by rimi-itk** [comment]
Hi @zoominGiladSher, I found out that just running `skhd`, i.e. with `--profile` worked, and then running `skhd` via the service started working. Therefore, I closed this issue, and in my excitement forgot to tell why I closed it. Sorry about that.

However, the `skhd` service has just stopped working on my machine, so now I'm back to running `skhd` in a terminal to enjoy it.

**Comment by zoominGiladSher** [comment]
Thanks for your answer @rimi-itk, I'm facing the same issue, unfortunately. Thanks for letting me know!
