### ISSUE TITLE
`skhd --start-service` does not check all config locations

### ISSUE THREAD

**Issue by BeCracked** [koekeishiya/skhd#323]
When starting skhd as a service with `skhd --start-service` the error log reads `skhd: could not open file '/Users/xxxx/.skhdrc'`. This is correct as in that I do have the config file under `/Users/xxxx/.config/skhd/skhdrc` (as stated as possible in the README) and not `~/.skhdrc`.
When I run `skhd` it works with the correct configuration in the `.config` directory.

Having the config under `~/.skhdrc` does work correctly when starting skhd both ways.

I also do not seem to be [the only one with this issue](https://github.com/koekeishiya/skhd/issues/284#issuecomment-1759227432).

**Comment by 9tin9tin9** [comment]
I just cloned the repo and compiled to test.
I cannot reproduce the problem by moving my config from `~/.config/skhd/skhdrc` to `~/.skhdrc`. Having config in both places and starting skhd in both ways work correctly

**Comment by BeCracked** [comment]
I also just retried by removing the symlink to `~/.skhdrc`, and I am pretty certain I didn't touch anything, but now it works. Maybe I _did_ have the path fumbled or something... Well whatever, thank you!
