### ISSUE TITLE
Keybindings don't work while focused in password fields

### ISSUE THREAD

**Issue by paulodiovani** [koekeishiya/skhd#325]
SKHD keybindinds don't work when a `password` field is focused on the browser.

It looks like, in password fields, the browser handles the keybinding itself, instead of the OS.

- OS keybindings should take precedence over application
- In the same way, SKHD-defined keybindings should take precedence over any other apps, since they are more general and can be set per application

### Test details

- Tested in Firefox and Chromium.
- Does not happen with other input fields

### How to reproduce

1. create a custom keybinding. e.g.
  ```apache
  cmd - t : open -na /System/Applications/Utilities/Terminal.app
  ```

2. open a login page (e.g. https://accounts.google.com/)
3. Fill in your username
4. When on the password field, hit your keybinding (e.g. `cmd - t`)

#### Expected

Run the keybinding and execute the action (e.g. open the terminal app)

#### Current

- Nothing happens
- Browser custom keybinding, if any, occurs (e.g. open a new tab)

**Comment by koekeishiya** [comment]
This is a security feature built into the macOS event-listener APIs.
