### ISSUE TITLE
Cannot focus an already focused space

### ISSUE THREAD

**Issue by Blebesquefee** [koekeishiya/skhd#326]
Hi everyone !

Since the update to Sonoma 14.2, i cannot move windows across different space.
The error message is the following : cannot focus an already focused space.

This error is still present even after a complet uninstall / install process

Here is my config file : 

[config.txt](https://github.com/koekeishiya/skhd/files/13759491/config.txt)

**Comment by tjex** [comment]
I also sometimes get this and have no idea what causes it. Then it starts working again all of a sudden

**Comment by tjex** [comment]
the 'complete process' included the system settings caveats listed in the readme for Sonoma? Which differ from Ventura.
Did you also regenerate the sudoers.d file for yabai?

This does sound like it's a yabai issue. If your other keybinds with skhd work, the it most likely isnt a skhd issue.

From what I understand, the logs of skhd catch output of whichever application it's interacting with.

**Comment by Blebesquefee** [comment]
Hi !
Which cavetas are you talking about ?
Yes, i did regenerate the sudoers file.

**Comment by tjex** [comment]
ah sorry, they're on the yabai repo readme: https://github.com/koekeishiya/yabai

What happens if you just execute the command from the CLI? e.g., `yabai -m space --focus 1`

If it works, then it would point to a probelm with skhd, if it doesn't then it could be safer to look at yabai

**Comment by Blebesquefee** [comment]
I upgraded the system and the visudo file and it works magicly now 🤷🏻‍♂️
