### ISSUE TITLE
Media Key Support

### ISSUE THREAD

**Issue by hughrawlinson** [koekeishiya/skhd#33]
Hi! I'd really like to be able to bind commands to media keys. #featurerequest

**Comment by koekeishiya** [comment]
Implemented in v0.2.0. See #1 for how to refernce the media-keys.

**Comment by hughrawlinson** [comment]
I thought I had searched, but should've searched harder. Sorry!

**Comment by koekeishiya** [comment]
Don't worry, you did search :)
The feature was added about 4hours ago.
