### ISSUE TITLE
Find/output current mode

### ISSUE THREAD

**Issue by exic** [koekeishiya/skhd#332]
So I have the passthrough mode to disable skhd temporarily, but too often I don't remember to turn it back on and am then confused when my shortcuts don't work. So I'd like a notification in my bar. For that to have, shkd would need an interface to show the current mode. Is that already somewhere or can it be implemented? Thanks :)

```
:: passthrough
alt - 0x21 ; passthrough
passthrough < alt - 0x21 ; default
```

**Comment by PhrantiK** [comment]
I have this in my config to change the bar border color when the mode changes:

````
:: default : sketchybar --bar border_color=0xff393939
:: window @ : sketchybar --bar border_color=0xffee5396
:: scripts @ : sketchybar --bar border_color=0xffffe97b

default, scripts < alt - escape ; window
window, scripts < escape ; default
default, window < alt - escape ; scripts

````

**Comment by exic** [comment]
Smart, that helps 😄 will have to see how I do this with simple-bar as well, but I'll figure that out. Thanks!

**Comment by PhrantiK** [comment]
> Smart

I wish I could take the credit but I shamelessly snagged it from this blokes config:

https://github.com/typkrft/chezmoi/blob/29dea8810f355c1e5103d68707fc8075e81e911f/dot_config/skhd/skhdrc

Even more shenanigans in there, check it out. :)
