### ISSUE TITLE
`zsh:1: command not found: yabai` - only when running the service

### ISSUE THREAD

**Issue by CH4O7IC** [koekeishiya/skhd#353]
Installed `yabai` and `skhd` via `brew`.
When running `skhd --start-service` my keybinds not using `yabai` work as intended.
Whenever I try to run a keybind using `yabai` the line from the title is added to the error log.
However, if I just run `skhd` in a terminal (after stopping the service of course) all my keybinds work just fine.

**Comment by avrahamappel** [comment]
Possibly duplicate of https://github.com/koekeishiya/skhd/issues/350

**Comment by CH4O7IC** [comment]
Ah yes, it seems it was after all.
Calling `eval "$(/opt/homebrew/bin/brew shellenv)"` inside my .zshenv did the trick.
Tnanks
