### ISSUE TITLE
Move window to space not working on macOS Sonoma 14.5

### ISSUE THREAD

**Issue by edoski** [koekeishiya/skhd#355]
This morning, after having upgraded my macOS to Sonoma 14.5 from 14.4.2, I tried using my usual keymaps for skhd such as the following:

shift + alt - 1 : yabai -m window --space 1; 
shift + alt - 2 : yabai -m window --space 2;

And neither seem to work now after updating to 14.5. I can confirm however that other mappings that use the shift key do work as expected, as I have both tested others with shift, and have tried the above ones using ctrl instead, so for that reason I believe that there is something wrong with this window to space function specifically. Cheers.

**Comment by jordan-da** [comment]
this just happened to me as well, my config is located here: 

https://github.com/hypergig/workstation/blob/master/config/skhdrc

**Comment by edoski** [comment]
[skhdrc.txt](https://github.com/koekeishiya/skhd/files/15312081/skhdrc.txt)
attaching for reference as well my config

**Comment by carlos-gtz** [comment]
This is already closed (and is not related to skhd).
This can be closed @edoski @koekeishiya
