### ISSUE TITLE
Multiple action hotkeys not working

### ISSUE THREAD

**Issue by fabibombo** [koekeishiya/skhd#356]
I'm using skhd in Sonoma 14.5 with latest yabai installed from HEAD. All commands work well but the following commands that chain multiple actions do not work, only the first command works and the window indeed moves to the proper space but the other two after it do not execute:

```
shift + alt - 1 : yabai -m window --space 1; yabai -m space --focus 1; yabai -m window --focus last
shift + alt - 2 : yabai -m window --space 2; yabai -m space --focus 2; yabai -m window --focus last
shift + alt - 3 : yabai -m window --space 3; yabai -m space --focus 3; yabai -m window --focus last
shift + alt - 4 : yabai -m window --space 4; yabai -m space --focus 4; yabai -m window --focus last
shift + alt - 5 : yabai -m window --space 5; yabai -m space --focus 5; yabai -m window --focus last
shift + alt - 6 : yabai -m window --space 6; yabai -m space --focus 6; yabai -m window --focus last
shift + alt - 7 : yabai -m window --space 7; yabai -m space --focus 7; yabai -m window --focus last
shift + alt - 8 : yabai -m window --space 8; yabai -m space --focus 8; yabai -m window --focus last
shift + alt - 9 : yabai -m window --space 9; yabai -m space --focus 9; yabai -m window --focus last
```

One thing that bothers me is that I remember it working when I set it up, but after rebooting this has been happening. Any ideas why? Thanks.

**Comment by michaelsaxon** [comment]
Same issue. shift + alt - (anything) is failing for me because it is no longer intercepting the characters.

So shift + alt - h gives the non-ascii Ó character, shift + alt - j gives Ô etc. Any ideas what's going on?

**Comment by diegounzer** [comment]
I am facing the same issues, any news about it? Is there any workaround?

Thanks!

**Comment by fabibombo** [comment]
Alright I figured out the issue, I needed to update the sha256 hash for yabai, it had changed for me after my first time configuration. It is working great now.

Read: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
