### ISSUE TITLE
Desktop switching behavior with modal support

### ISSUE THREAD

**Issue by pkazmier** [koekeishiya/skhd#36]
For consistency of how I use `skhd`, I want to use my modal keybindings to switch desktops, so I'm "faking" it by:

  * using `qes` to escape out of my `focus` mode (note: I capture keystrokes in all my modes via `@` so it would gobble up any Mac keyboard shortcuts if I didn't),
  * sending the Mac keyboard shortcut to switch desktops, 
  * and then using `qes` again to toggle back into `focus` mode. 

This works well except that border color does not change upon entry into my `focus` mode. I believe this is due to a timing issue with the mission control animations.

I "fixed" this by adding an explicit sleep (shorter for explicit desktop specification and longer for next/prev desktop as the animation speed varies), and then manually calling `chunkc` to set the border color again. It works, but it seems hacky. Is there a better way of handling this _without_ having to resort to using fast desktop switching as I don't want to inject code into my Dock.

Thanks for such as awesome window manager!

```
focus                     < 1           : qes -k "ctrl - space"; qes -k "cmd + alt - 1"; qes -k "ctrl - space"; sleep 0.4; chunkc border::color 0xffe06c75
focus                     < 2           : qes -k "ctrl - space"; qes -k "cmd + alt - 2"; qes -k "ctrl - space"; sleep 0.4; chunkc border::color 0xffe06c75
focus                     < 3           : qes -k "ctrl - space"; qes -k "cmd + alt - 3"; qes -k "ctrl - space"; sleep 0.4; chunkc border::color 0xffe06c75
focus                     < tab         : qes -k "ctrl - space"; qes -k "ctrl - right"; qes -k "ctrl - space"; sleep 0.75; chunkc border::color 0xffe06c75
focus                     < shift - tab : qes -k "ctrl - space"; qes -k "ctrl - left"; qes -k "ctrl - space"; sleep 0.75; chunkc border::color 0xffe06c75
```

**Comment by koekeishiya** [comment]
This is not a timing issue, but just a bug chunkwm's border plugin.

The command `chunkc border::color <..>` only affects the current border, but since you switch spaces, it reads the color again from `chunkc get focused_border_color`.

I've made the `border::color ..` command also update the `focused_border_color` cvar on the latest chunkwm master branch.

**Comment by pkazmier** [comment]
Thanks! I’ll update tomorrow!
