### ISSUE TITLE
firefox opens in troubleshoot mode

### ISSUE THREAD

**Issue by 5brian** [koekeishiya/skhd#376]
when no instance of firefox is open (after quitting with cmd+q), firefox tries to open in troubleshoot mode
works fine when firefox is already open
is my config wrong? works fine when using google chrome

config:
cmd + alt - q : open -na "Firefox Developer Edition"

![image](https://github.com/user-attachments/assets/02df2f12-fac0-449b-8011-3d40d114ce50)

**Comment by michaelpercillier** [comment]
I found the problem: Firefox opens in troubleshooting mode when the Alt key is pressed at launch. Try changing the keybinding to something without Alt, such as ctrl + shift + q.

**Comment by 5brian** [comment]
Thanks!
