### ISSUE TITLE
MPV fails to run when called

### ISSUE THREAD

**Issue by RosalesJ** [koekeishiya/skhd#40]
# Issue
Adding the following config to ```.skhdrc``` causes MPV to fail.
```
cmd + alt - p : mpv -v $(pbpaste)
```
In fact MPV fails for any link if called from skhd.

# Version info
Software | Version
--------|----------
Macos | 10.13.5
skhd | 0.2.2
mpv | 0.28.2
youtube-dl | 2018.06.19

# Attempts
* Running ```mpv -v $(pbpaste)``` on any terminal works fine.
* Compiling from source doesn't make a difference.
* Compiling ```fork_and_exec``` from ```hotkey.c``` and calling it with an MPV command actually works. So I called it with 
```"mpv -v https://www.youtube.com/watch?v=D52TF1OtgSE > mpv_success.log"```
and added 
``` 
cmd + alt - p : mpv -v https://www.youtube.com/watch?v=D52TF1OtgSE > mpv_failure.log
```
to ```.skhdrc``` resulting with the following two files.

[mpv_success.log](https://github.com/koekeishiya/skhd/files/2121693/mpv_success.log)
[mpv_failure.log](https://github.com/koekeishiya/skhd/files/2121690/mpv_failure.log)

These files only differ in that the command
```
/usr/local/bin/youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist -- https://www.youtube.com/watch?v=0SWS4M94TiM
```
fails in one but not the other.

# Speculation
It might be the case the skhd is messing with the environment that mpv is running in, this might cause youtube-dl to fail as it's doing.

**Comment by koekeishiya** [comment]
Do you run skhd from a terminal or through launchd (or brew services)?

**Comment by RosalesJ** [comment]
Running ```skhd``` from either the terminal or brew services with the following command
```bash
ctrl + cmd - p : mpv --no-border --log-file=~/work/mpv_log.log -- https://www.youtube.com/watch?v=GCN9ULeU_jI
```
Both fail to run mpv and make the log file [mpv_log.log](https://github.com/koekeishiya/skhd/files/2167319/mpv_log.log).

**Comment by koekeishiya** [comment]
What is `mpv` aliased to in your case, or how did you install mpv?

using the following seems to work fine for me: `cmd - m : mpv $(pbpaste)`

I've just aliased `mpv` to `open -na /Applications/mpv.app` because I had other issues with mpv not opening correctly (unrelated to chunkwm, skhd though)

**Comment by RosalesJ** [comment]
I installed mpv through the latest brew formula. I have ```mpv``` as ```/usr/local/bin/mpv/```. Although I've tried installing ```--with-bundle``` and calling mpv through
```
/usr/local/Cellar/mpv/0.28.2/mpv.app/Contents/MacOS/mpv
```
which is probably called by ```open```, but that results in the same error both with, or without running ```skhd``` in the terminal.  How did you install mpv?

**Comment by koekeishiya** [comment]
I just downloaded the app package from mpv.io and moved it into the /Applications folder.
FYI *skhd* is not doing anything with the environment or anything. All it does is run the command through your specified shell, as you saw in the `fork_and_exec` function.

I'm not sure why you are having that issue..

**Comment by RosalesJ** [comment]
Where have you aliased ```mpv``` to ```open -na /Applications/mpv.app``` I tried, but skhd wouldn't load my ```.bashrc```.  Instead I called open directly which actually worked. 

The following works for me too ```cmd - m : open -na /Applications/mpv.app $(pbpaste)```.

But calling the binary directly from skhd fails. 
The following fails: ```cmd - m : /Applications/mpv.app/Contents/MacOS/mpv $(pbpaste)```

For all intents and purposes my problems are solved, although I'm still curious about what you did for the alias (where you put it) and why calling the binary directly works when called from any terminal but not through ```skhd```.

**Comment by koekeishiya** [comment]
I noticed that my skhdrc actually uses the full path to mpv with open, and not my alias, sorry about that. On second though, I don't think *execvp* can actually utilzie aliases, but it just looks for the given executable in your path.

Calling the binary directly does not even work from the terminal for me, and never has:
`Assertion failed: (self->_mk_tap_port != nil), function __33-[EventsResponder startMediaKeys]_block_invoke, file ../osdep/macosx_events.m, line 407.`, so I suppose something is happening in the startup code of mpv.
