### ISSUE TITLE
Howto : launch single instant of apps 

### ISSUE THREAD

**Issue by imagnma** [koekeishiya/skhd#46]
Hello 

I've been trying for hours to launch a single instance of iTerm2 and qutebrowser, and ranger 
the task seems impossible 

currently I manged to luanch iTerm app with :
`alt - return : open -na /Applications/iTerm.app`

However, it launch new app and also bother me with choose profile window. 

I tried the following and also it didn't fix it : 
`alt - return : open -na /Applications/iTerm.app/MacOs/iTerm2`
and for qutebrowser, and ranger mpv-youtube 

I have no idea how to open them with shortcuts .
thanks

**Comment by koekeishiya** [comment]
The *-n* part of the argument given to *open* says that it should poen a brand new instance.
Change it to `alt - return : open -a /Applications/iTerm.app` to launch a single instance.

**Comment by koekeishiya** [comment]
For *qutebrowser*, I use the following script: https://github.com/koekeishiya/dotfiles/blob/master/scripts/qtb.sh

and in *skhd*: `cmd + shift - return : ~/Scripts/qtb.sh`

**Comment by imagnma** [comment]
when I put just `-a`, & tried adding with /MacOS/iTerm . it doesn't work at all 

for qutebrowser, cloned qtb.sh, after creating directory `~/scripts` 
the cmd + shift - return : ~/scripts/qtb.sh <<< does it work with .app or installed with pip3

thanks

**Comment by imagnma** [comment]
`-a` matter of fact retook me to the last active iTerm

**Comment by dr1s** [comment]
I use the following script to launch iterm with skhd:
https://github.com/Julian-Heng/chunkwm-config/blob/master/chunkwm/scripts/misc/open_iTerm2.sh

**Comment by imagnma** [comment]
OMG, it actually worked @dr1s , thanks a lot , I’ve tried tweeting the code to make it work with my default browser “qutebrowser” and still no luck , it gives me an error and well as kill my other qutebrowser window.

**Comment by imagnma** [comment]
thanks a lot @dr1s this ive tried and it didnt work :(

**Comment by koekeishiya** [comment]
Works fine for me. You may have to change it to use the full path to your qutebrowser.app

**Comment by yanzhang0219** [comment]
> I use the following script to launch iterm with skhd:
> https://github.com/Julian-Heng/chunkwm-config/blob/master/chunkwm/scripts/misc/open_iTerm2.sh

This link is changed to https://github.com/Julian-Heng/chunkwm-yabai-config/blob/master/scripts/open_iterm2.sh. I put it here in case anybody needs it.

**Comment by mefengl** [comment]
MacOS 12.6, seems like -a is used to call a app without given its path, -n create a new distance


more:
In the command open -n iTerm.app, the -n flag tells the open command to open a new instance of the specified app, even if an instance of the app is already running.

The open command is a built-in command on macOS that is used to open files, URLs, and applications. When you use the open command to open an application, it will open the app if it is not already running, or it will bring the app to the front if it is already running.

However, if you include the -n flag in the open command, it will open a new instance of the app even if an instance is already running. This allows you to have multiple instances of the same app open at the same time.

In the example you provided, the command open -n iTerm.app will open a new instance of iTerm even if an instance is already running. This can be useful if you want to have multiple iTerm windows open at the same time.

In the open command, the -a flag is used to specify the name of the application that you want to open. For example, if you want to open the app "TextEdit", you could use the following open command:
`open -a TextEdit`
This command will open the TextEdit app if it is not already running, or it will bring the TextEdit app to the front if it is already running.

The -na flag is a combination of the -n and -a flags, and it tells the open command to open a new instance of the specified app even if an instance of the app is already running.

For example, if you want to open a new instance of the TextEdit app even if an instance is already running, you could use the following open command:

`open -na TextEdit`
This command will open a new instance of the TextEdit app, allowing you to have multiple instances of the app open at the same time.
