### ISSUE TITLE
application specific hotkeys

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/skhd#47]
Kind of similar to what was done in **khd** prior.

Have not decided how this is going to work, but currently thinking something as follows:

```
cmd - f [
    "notes"   : <some_command>
    "firefox" : <some_other_command>
    "finder"  : <some_totally_unrelated_command>
]
```

This will allow one bind to do various actions depending on the active application, or none if the application is not listed.

Note that spacing / indentation above is purely for readability, *EXCEPT* that commands *MUST* end with an EOL character. As such, you'd have to do a line delimeter before the next application can be specified.

An issue with this syntax is that it can't really support the *"run command for all applications NOT listed"* in a nice way (but I'm not sure if I care too much about that anyway).

**Comment by koekeishiya** [comment]
implemented on branch i47. Not on macOS, so not tested.
Syntax is as described in the first post.

process-names will be in full lowercase, and must also be written in lowercase by the user.

*"run command for all applications NOT listed"* is not going to be a thing for now.

**Comment by koekeishiya** [comment]
implemented on master / v0.3.0

**Comment by andbloch** [comment]
Is there still a way to easily do "run command for all applications NOT listed"?

On khd I used to do:

# remap CTRL + C to CMD + C:
ctrl - 0x08 ![Terminal,iTerm2]: skhd -k "cmd - 0x08"

How can this be done on skhd?

**Comment by danijar** [comment]
I'm running into the same issue --- I'd like to map `Cmd + H` to a dummy command to disable the "Hide Window" feature in Mac, except for VSCode where I'm manually mapping `Cmd + H` to an editor command (which prevents the Mac default behavior).

Would it be possible to add regex support to the syntax? That way, we could easily do "all other programs" (and it's more flexible in many other ways):

```
cmd - f [
    "notes"   : <some_command>
    "firefox" : <some_other_command>
    ".*"  : <some_totally_unrelated_command>
]
```
