### ISSUE TITLE
skhd aborting because of false secure keyboard entry error

### ISSUE THREAD

**Issue by msuess** [koekeishiya/skhd#48]
When I try and start `skhd` from the CLI it aborts with

```
skhd: secure keyboard entry is enabled! abort..
```

It randomly stopped working after a reboot yesterday and I couldn't get it to run since then. I've tried rebooting, reinstalling, reinstalling with `--HEAD` and turning accessibility access off and on, to no avail.

**Comment by crisidev** [comment]
You have enabled the secure keyboard entry without noticing (iTerm2).

Click on iterm2 menu, and then click on Secure Keyboard Entry to and untick it :)

**Comment by msuess** [comment]
Hey, thanks for the quick response. I'm using kitty as my terminal. Here's a screenshot of me trying to run it in `Terminal.app`:

![screen shot 2018-09-04 at 14 05 13](https://user-images.githubusercontent.com/337886/45030274-98f48e80-b04b-11e8-8b4a-d39a65770162.png)

It's also not working when started as a service, with the same error message in the log file.

**Comment by msuess** [comment]
I... just restarted my laptop without my screen connected, restarted chunkwm and skhd and plugged in my screen again. It's working now 🤔

**Comment by msuess** [comment]
Sorry for the false alarm, everyone!

**Comment by yurrriq** [comment]
This keeps happening to me. `skhd` will stop working and if I try to restart it I get the "secure keyboard entry" error. I, too, am using kitty. Any advice? FWIW it works briefly if I log out and log back in. Maybe it's an issue with my company's AD.

**Comment by koekeishiya** [comment]
Some application on your system is likely turning it on without notifying you.

**Comment by yurrriq** [comment]
Any tips on how to track that down?

**Comment by yurrriq** [comment]
I'm just seeing your advice, thanks. By brute force, I think I've determined it was [Keybase.app](https://github.com/keybase/client). After almost a week I finally have `skhd` back! :tada:

**Comment by WhatisRT** [comment]
Maybe the info on how to troubleshoot this could be put somewhere in the readme? I'm having the same issue (though I cannot test if the troubleshooting will help me, as I just rebooted and it's working for now).

**Comment by koekeishiya** [comment]
I might implement support in skhd for figuring out the application keeping secure keyboard entry enabled, when it detects that it is in fact enabled, if I can be bothered looking into the IOReg API.

**Comment by dominiklohmann** [comment]
There's probably a better way to do this but this oneliner works just fine for me. Broke it up into multiple lines to make it easier to see. Also there's probably some easier way to do this for bash wizards.
```bash
ps auxww \
    | grep $(ioreg -l -w 0 \
        | grep -woE '\"kCGSSessionSecureInputPID\"=([0-9]+)' \
        | cut -f2- -d= \
        | uniq) \
    | awk '{ print $NF }'
```

**Comment by WhatisRT** [comment]
Well, in my case it was actually safari. Turns out in enables secure keyboard entry when you want to get a password from the settings dialogue, and just closing that window did the trick...

**Comment by L3rchal** [comment]
In my case it was `loginwindow console` process (So I did kill it and killed my whole user session 😆 do not recommend do this).

**Comment by halvardlange** [comment]
I had the same issue, and it was the `loginwindow console` process that caused it. I just locked my screen, and logged in again - that fixed the issue.

**Comment by eugeneware** [comment]
Likewise thanks to [this code](https://github.com/koekeishiya/skhd/issues/48#issuecomment-421511393l) I also identified it was the `loginwindow console` process. I killed the process (which logged me out). I should have locked and logged in again as suggested above!

**Comment by carlosdagos** [comment]
Came across this issue today. For me that was `iTerm` causing the issue. I disabled Secure Input as described in this link: https://gitlab.com/gnachman/iterm2/issues/3937

The oneliner provided by @dominiklohmann helped me figure that out. Thanks a lot!

**Comment by koekeishiya** [comment]
For what it's worth. In the latest version skhd will try to locate the process that has activated secure keyboard input when it starts, and report the process name and pid. The output is printed to stderr, so if you are running through launchservices you probably need to edit the plist (preferences list) and specify the path for a logfile.

**Comment by aiguofer** [comment]
I'm running into this issue as well... in my case, the code that tries to locate the process seems to detect whichever console/terminal I'm trying to use to start `skhd` (see https://github.com/alacritty/alacritty/issues/3364).

Next time this happens I will try some of the above mentioned workarounds. Is there a way to simply disable the secure keyboard entry globally?

**Comment by koekeishiya** [comment]
Not really sure what that is happening. skhd uses the API `CGSIsSecureEventInputSet` to check the current state and `CGSCopyCurrentSessionDictionary` to retrieve info about the process.

**Comment by aiguofer** [comment]
Ok, just happened again:

```
$ ioreg -l -w 0 \
    | perl -nle 'print $1 if /"kCGSSessionSecureInputPID"=(\d+)/' \
    | uniq \
    | xargs -I{} ps -p {} -o comm=
/System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
$ skhd -V
skhd: successfully created pid-file..
skhd: secure keyboard entry is enabled by (65710) 'alacritty'! abort..```

this is getting pretty annoying.. any way to disable that entirely? it seems to happen waaay too often making `skhd` unreliable.

**Comment by koekeishiya** [comment]
I mean you can disable that check, but then I assume skhd wouldn't actually receive the input event, and so it won't really help.

**Comment by aiguofer** [comment]
Oh, i meant "Is there a way to simply disable the secure keyboard entry globally".

As for the incorrect output, I can create a separate issue for that if it helps :)

**Comment by aiguofer** [comment]
Hmm, nvm.... There might not be a workaround https://wiki.keyboardmaestro.com/assistance/Secure_Input_Problem

My list of things I hate about Mac keeps growing -.-

**Comment by aiguofer** [comment]
For others having this issue... are you using finger print to log in?

It seems like the issue happens when I log in using my finger print before "waking up" the laptop to see the login screen

**Comment by dominiklohmann** [comment]
This is almost certainly not related to Touch ID. If it was, you'd see way more complaints on this issue board.

Please just check which process enables Secure Input: If it's loginwindow, reboot (seems to be a bug that cannot be reproduced reliably), if it's any other process (as shown above) disable it for that process and restart skhd.

**Comment by mrrsm** [comment]
When it has been loginwindow I have been able to fix by locking and unlocking rather then rebooting.

**Comment by NickClark** [comment]
I found that whatever app I had opened, skhd would report that app as having secure entry turned on. This happened to me after I woke my computer up and logged in again after it had been sleeping overnight. I locked it and unlocked it again, and the problem went away.

**Comment by eraserhd** [comment]
I just had this issue, and it was Google Chrome, but only while I was on a password field.  skhd dies, but since I have it in a KeepAlive service, it attempts to respawn, so after I clicked enter on the form, I could resume (after 10 seconds or something).

**Comment by jneen** [comment]
Just had this happen to me again after logging in with touch ID. It is in fact the loginwindow process.

**Comment by jls5177** [comment]
I keep running into this issue. Just resolved it by locking and unlocking with `Touch ID`. So definitely not related to `Touch ID`.  

For me it was `kitty` that was holding the lock:
```
skhd: secure keyboard entry is enabled by (7422) 'kitty'! abort..
```

Is there anything I should capture next time this happens to help root cause the issue?

**Comment by rmGFW** [comment]
> Not sure if this still works, but I came across this:
> 
> ```
> 
> peternlewisElderDec '15
> Thanks to info provided by the fine folks at Smile Software 24, you can use the Terminal command:
> 
> ioreg -l -w 0 | grep SecureInput
> That will tell you the process ID (kCGSSessionSecureInputPID) of the application that has Secure Input enabled. You can then use:
> 
> ps auxww | grep NNN
> to find the process with the specified pid.
> 
> I will endeavour to add some support for this within Keyboard Maestro’s alert in the future.
> 
> Thanks again to the Smile Software 24, makers of great Mac software!
> ```
> 
> Source: https://forum.keyboardmaestro.com/t/disable-secure-input/2410/3

i execute this command and find that `loginwindow console` is the process that toggle the secure keyboard.
if i kill `loginwindow console` ,it will stop all my process . is there any way to solve this problem 🤣

**Comment by koekeishiya** [comment]
This "problem" is because some software running on macOS enables Secure Keyboard Input (which is a security feature to make it harder for keylogging software), and for some reason, some of these applications forget or fail to disable this mode when it is no longer necessary. There is nothing I can to fix this in skhd without losing a lot of the customization power that it currently has.

**Comment by patlux** [comment]
Same issue here:

```bash
❯ ioreg -l -w 0 \
    | perl -nle 'print $1 if /"kCGSSessionSecureInputPID"=(\d+)/' \
    | uniq \
    | xargs -I{} ps -p {} -o comm=
/System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow

❯ skhd -V
skhd: successfully created pid-file..
skhd: secure keyboard entry is enabled by (3169) 'kitty'! abort..
```

Really annoying....

**Comment by augustebaum** [comment]
Same issue here and locking and unlocking the screen does not help; so far I've only gotten success by rebooting.
However the troubleshooting technique does do something:
1. Usually I'll open up my computer and either
 a. it works (and then I'm happy because `skhd` is great software and I'm actually really dependent on it now!), or
 b. it doesn't and the script prints `loginwindow` as the culprit.
2. Accordingly, I'll lock and unlock my screen, and now the script shows the terminal I'm using to start skhd (kitty, alacritty, Terminal.app...) as the culprit.

What is there to do in this situation that doesn't involve heavily hampering my workflow (which `skhd` is meant to speed up, ironically)?

**Comment by doei** [comment]
> 2. Accordingly, I'll lock and unlock my screen, and now the script shows the terminal I'm using to start skhd (kitty, alacritty, Terminal.app...) as the culprit.
This happens to me too

> I need to do further testing, but _it seems like the problem might have come from the Bitwarden app_; I closed it and the issue was no more.
Same here ! Closing Bitwarden definitely solved the issue, I couldn't restart / start skhd in any way before that.

Thanks for figuring it out @augustebaum

**Comment by alimli** [comment]
> > 1. Accordingly, I'll lock and unlock my screen, and now the script shows the terminal I'm using to start skhd (kitty, alacritty, Terminal.app...) as the culprit.
> 
> This happens to me too
> 
> > I need to do further testing, but _it seems like the problem might have come from the Bitwarden app_; I closed it and the issue was no more.
> 
> Same here ! Closing Bitwarden definitely solved the issue, I couldn't restart / start skhd in any way before that.
> 
> Thanks for figuring it out @augustebaum

Same symptoms here, however this time the application is KeePassXC instead of Bitwarden.

**Comment by jaycunningham-8451** [comment]
For what it's worth, although the loginwindow issue happens to me all the time (maybe 50-60% of the time my laptop wakes from sleep), skhd always misreports iTerm as the culprit. Locking and unlocking the screen fixes the issue 100% of the time for me so it's no big hardship, just a bit confusing at first.

**Comment by usizu** [comment]
I had this happen to me - turns out it was because 1Password had the editing field open on a password entry in the background. Just closing the entry fixed it. 

Seems obvious that that would cause it, but SKHD was reporting Safari or iTerm as the one to enable Secure Input, and I had 
 1Password hidden and forgotten. So it seems that easy fix is to just quit any app that might have been involved in Secure Input.

**Comment by nocksock** [comment]
I had this issue with kitty as several others here too. And I have found the **reason** and **solution** to fix this once and for all! 🎉 Well, at least for those where kitty was the culprit of course.

It's in fact a sensible kitty feature, with an **annoyingly bad default shortcut**, that can be easily hit by accident:

`cmd+opt+s`: `toggle_macos_secure_keyboard_entry`

Pressing this I can consistently recreate the issue.

The state persists even with reboots - which is probably a smart thing to do on kitty's part, given the purpose of the toggle. The default shortcut is just astoundingly bad (and a visual indicator might be helpful too).

I immediately disabled it:

```conf
# ~/.config/kitty/kitty.conf
map cmd+opt+s noop
```

Note: there's a [PR making the remap possible](https://github.com/kovidgoyal/kitty/pull/4478) earlier this year. It has been merged - but if remapping ain't working, check your kitty version

**Comment by lmBored** [comment]
In my case, terminal is using secure keyboard entry, so disabling and quitting terminal solves the problem

**Comment by tgallacher** [comment]
In my case a website I was using the day before had automatically logged me out by the time I came back the next day. This put me onto their log in page, which meant the browser (brave) enabling the secure keyboard entry api. This probably happens a lot, but in this case I was working on something else and so didn't notice the log in page. 

Lost `skhd` for most of the day until I tracked this down... 

Closing the login page (or logging in) and restarting skhd solved the issue

**Comment by skyferix** [comment]
> For what it's worth, although the loginwindow issue happens to me all the time (maybe 50-60% of the time my laptop wakes from sleep), skhd always misreports iTerm as the culprit. Locking and unlocking the screen fixes the issue 100% of the time for me so it's no big hardship, just a bit confusing at first.

For those who lock/unlock does not work try restarting the skdh after unlock

- `brew services restart skdh` -> if registered as service
- `skhd` -> if you start it by hand

**Comment by subfor** [comment]
control+command+q and entering the password from the keyboard helped for me

**Comment by mo-dayyeh** [comment]
I'm facing this issue and the process responsible is:  /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
 anyways to resolve that ?  it does not make sense for me to kill my terminal !

**Comment by tjex** [comment]
> I'm facing this issue and the process responsible is: /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal anyways to resolve that ? it does not make sense for me to kill my terminal !

You need to disable secure keyboard entry in Terminal's prefs.

**Comment by mariuspana** [comment]
Is there a solution to this issue? After every reboot/Lock Screen/login this happens with safari, item, loginwindow.

Thanks.

**Comment by tigger04** [comment]
I keep getting the same issue. It tells me WezTerm has enabled secure keyboard entry. If i kill WezTerm, it tells me Firefox has enabled secure keyboard entry ... kill that and ... it simply keeps reporting the frontmost app as having secure keyboard entry, even stickies, textpad, anything. It's like russion dolls with the same errors.
Only solution seems to be a reboot. Works for a while then ... whatever app is frontmost, skhd seems to think it has secure keyboard and so the goose chase begins again until reboot.

It's driving me barmy!

**Comment by tigger04** [comment]
Initially I though the issue was Seqouia, but I have 2 macs one running sonoma, one running sequoia. Both have exact same issue.

**Comment by sohaha** [comment]
This problem should not be solved yet, right?

**Comment by martinengelke** [comment]
> This problem should not be solved yet, right?

Right
