### ISSUE TITLE
Is there are support meta or leader key?

### ISSUE THREAD

**Issue by seyar** [koekeishiya/skhd#49]
I using skhd and I really like it.
But some hotkey mappings are conflicts with mapping in other applications. 

Is there a config for meta key? 

For example, I press `Ctrl+a` and then `d` like in tmux
or `ctrl+w` then left arrow like vim.

**Comment by dominiklohmann** [comment]
You can use modes for that. Make <kbd>ctrl</kbd><kbd>a</kbd> activate your mode, then make <kbd>d</kbd> trigger your desired action when in that mode. The example configuration has lots of bits that you can chain together to do this.

**Comment by seyar** [comment]
@dominiklohmann thank you

**Comment by seyar** [comment]
@dominiklohmann 
Ok. I tried your setup. Works as well. But I not sure that its working similar to tmux or vim etc.

How I can define action in some test mode with executing command and immediately exit to default mode?

```bash
# from 'default' mode, activate mode 'test'
alt - d ; test
# from 'test' mode, activate mode 'default'
test < alt - d ; default # there is exit to default without executing command

test < j : chunkc tiling::window --focus south; default # executing command only. We are stay in test mode still
```

according docs
> @         = capture keypresses regardless of being bound to an action

but action has not sample exec command and exit mode
```bash
## action   = <keysym> ':' <command> | <keysym> '->' ':' <command>
##                                  <keysym> ';' <mode>    | <keysym> '->' ';' <mode>
```

**Comment by dominiklohmann** [comment]
Your issue is in this line:
```
test < j : chunkc tiling::window --focus south; default # executing command only. We are stay in test mode still
```

Everything after the `:` is being executed as a shell command. 

Instead what you want to have is this:

```
# toggle mode "test" using alt-d
alt - d ; test
test < alt - d ; default

# execute command in mode "test", then leave mode by simulating alt-d keypress
test < j : chunkc tiling::window --focus south; skhd -k "alt - d"
```

**Comment by seyar** [comment]
it works. Thank you
