### ISSUE TITLE
Segmentation fault when using key literals

### ISSUE THREAD

**Issue by xaviervalarino** [koekeishiya/skhd#5]
This seems related to #2 **Segfaults when using function key literals**.

skhd segfaults whenever I try to use key literals in my `.skhdrc`. I have no issue when I switch them out for the keycodes. 

I installed skhd version 0.0.7 using the `--HEAD` flag in homebrew on OSX 10.11.6

---
### What I see in the terminal
When using keycodes:
```
$ skhd
skhd: using config '/Users/xavier/.skhdrc'
(#39) hotkey :: {
	mod: 'ralt'
	key: '0x04' (0x04)
	cmd: 'chunkc tiling::window --focus west'
}
hotload: watching file '.skhdrc' in directory '/Users/xavier'
```

When using literals:
```
$ skhd
skhd: using config '/Users/xavier/.skhdrc'
(#44) hotkey :: {
	mod: 'ralt'
Segmentation fault: 11
```

**Comment by koekeishiya** [comment]
See #4

**Comment by koekeishiya** [comment]
Cloning the repo and building from source should work fine.

**Comment by xaviervalarino** [comment]
Thank you for clarifying, and again, sorry to duplicate the issue.

**Comment by xaviervalarino** [comment]
Unexpectedly, building from source causes the same `Segmentation fault: 11` with literals, regardless of whether I change the optimization to `-02`,`-03` or `-0s`

**Comment by koekeishiya** [comment]
I really don't know. I've never had any problems even during development, and I still cannot reproduce a crash with complex or simple configs.

The code also looks just fine to me, there are no bad memory accesses etc.
I don't have an El Capitan system available, so I don't have any means to debug it either.

**Comment by xaviervalarino** [comment]
I should have been more thorough with my investigation; skhd works when I build the development version.

```
skhd (master)$: make install

rm -rf ./bin
mkdir -p ./bin
clang src/skhd.c -std=c99 -O2 -framework Carbon -o bin/skhd
 
skhd (master)$: ./bin/skhd

skhd: using config '/Users/xavier/.skhdrc'
(#11) hotkey :: {
	mod: 'alt'
Segmentation fault: 11
 

skhd (master)$: make

rm -rf ./bin
mkdir -p ./bin
clang src/skhd.c -std=c99 -Wall -g -O0 -framework Carbon -o bin/skhd

 skhd  (master)$: ./bin/skhd

skhd: using config '/Users/xavier/.skhdrc'
(#11) hotkey :: {
	mod: 'alt'
	key: 'h' (0x04)
	cmd: 'chunkc tiling::window --focus west'
}
(#12) hotkey :: {
	mod: 'alt'
	key: 'j' (0x26)
	cmd: 'chunkc tiling::window --focus south'
}
(#13) hotkey :: {
	mod: 'alt'
	key: 'k' (0x28)
	cmd: 'chunkc tiling::window --focus north'
}
(#14) hotkey :: {
	mod: 'alt'
	key: 'l' (0x25)
	cmd: 'chunkc tiling::window --focus east'
}
hotload: watching file '.skhdrc' in directory '/Users/xavier'
```
