### ISSUE TITLE
Recurring "Accessibility Access" requests under macOS Mojave

### ISSUE THREAD

**Issue by mgiugliano** [koekeishiya/skhd#52]
I am under macOS Mojave 10.14 and skhd (v. 0.3.0) has restated prompting "Accessibility Access", despite being already granted access. 

Deselecting and selecting skhd from the list of apps from Security & Privacy in System Preferences had no effect.

**Comment by koekeishiya** [comment]
This is not really an issue with skhd, but rather quirky behaviour in macOS. See the referenced issue for things you can try to resolve the problem. Closing this issue.

**Comment by a-r-j** [comment]
Hi @mgiugliano did you fix this?

@koekeishiya Could you please indicate the issue you're referencing? Have you come across any things to try since then?

**Comment by mgiugliano** [comment]
> Hi @mgiugliano did you fix this?
> 
> 
> 
> @koekeishiya Could you please indicate the issue you're referencing? Have you come across any things to try since then?

I stopped using the software (unfortunately), as I could not fix the problem. I now use Hammerspoon.
