### ISSUE TITLE
Per-application opt-out of all mappings?

### ISSUE THREAD

**Issue by bcully** [koekeishiya/skhd#53]
I love chunkwm and skhd. I also like i3, which I run in a VM on my mac. It's a little painful keeping the keyboard mappings for chunkwm from swallowing those of skhd. I think if there were a way to configure skhd to completely ignore an application it would make it a lot easier to manage this particular use case. Thoughts?

**Comment by bobbybroadcast** [comment]
+1 Came here hoping to find an option for this

**Comment by bobbybroadcast** [comment]
That's a good workaround, if only temporary. thanks

**Comment by koekeishiya** [comment]
Fixed on master. See updated sample config and/or README for information. I'll be posting the syntax for it here as well.

There is now a new category in the grammar called *options*, and these begin with a `.` followed by the name of the option. Currently there is one option `.blacklist` which require a list of process-names that are to be ignored by **skhd**.

e.g:
```
.blacklist [
    "google chrome"
    "kitty"
    "vmware fusion"
]
```

**Comment by koekeishiya** [comment]
Part of release v0.3.2, closing this.

**Comment by bcully** [comment]
Thank you!
