### ISSUE TITLE
Config load seems slower than khd?

### ISSUE THREAD

**Issue by kwstannard** [koekeishiya/skhd#54]
### Back story

I have been using khd to simulate my crazy workflow that I developed in i3 and originally I was having a lot of issues getting modals to work, but one day I realized I could just programmatically rewrite the config with a tiny ruby script and tell khd to reload and I got that working and everything was great.

### Issue

After the switch to skhd, it is taking 1-3 seconds for my config files that seemed to load instantly in khd.

This is my current config. I don't know if there is anything useful. The config rewrite happens on line 41.

https://github.com/kwstannard/kws-scripts-and-configs/blob/master/configs/skhdrc.erb.conf

**Comment by koekeishiya** [comment]
How do you trigger the config rewrite?
I don't immediately see how this works out, so the only tip I can give is to compile skhd with profiling from source: `make fast_profile`

Run skhd and it will print some timing info, e.g how long it took to reload the config and so on.

**Comment by kwstannard** [comment]
Sorry about the delay. Had a baby 3 months ago.

```
0.4940ms (handle_keypress) # This is when I hit alt - 6-9 to re-write the config
0.1490ms (hotload_config)
0.2640ms (hotload_config)
0.4710ms (handle_keypress) # This is when I hit alt - 6-9 to re-write the config
0.2000ms (hotload_config)
0.2590ms (hotload_config)
0.4630ms (handle_keypress) # This is when I hit alt - 6-9 to re-write the config
0.2470ms (hotload_config)
0.2870ms (hotload_config)
```

These are all me hitting alt - 1-5 to switch between tmux windows.

```
0.7720ms (handle_keypress)
0.4830ms (handle_keypress)
0.4710ms (handle_keypress)
0.4920ms (handle_keypress)
0.4540ms (handle_keypress)
```

This is me benchmarking the ruby config generation:

```
/Users/kstannard  (scripting)(not a repo)  Feb 12
>> time ruby -r erb -e 'puts ERB.new(File.read(Dir.home+"/scripts/configs/skhdrc.erb.conf")).result binding' 2 > ~/.skhdrc

real    0m0.176s
user    0m0.102s
sys     0m0.052s

/Users/kstannard  (scripting)(not a repo)  Feb 23
>> time ruby -r erb -e 'puts ERB.new(File.read(Dir.home+"/scripts/configs/skhdrc.erb.conf")).result binding' 2 > ~/.skhdrc

real    0m0.188s
user    0m0.107s
sys     0m0.059s
```

Me telling tmux to switch windows:

```
/Users/kstannard  (scripting)(not a repo)  Feb 23
>> time tmux select-window -t :=6

real    0m0.013s
user    0m0.003s
sys     0m0.006s

/Users/kstannard  (scripting)(not a repo)  Feb 23
>> time tmux select-window -t :=7

real    0m0.028s
user    0m0.003s
sys     0m0.006s
```

Me telling tmux to set status line:

```
/Users/kstannard  (scripting)(not a repo)  Feb 23
>> time tmux set status-left "[#S]"

real    0m0.028s
user    0m0.003s
sys     0m0.006s

/Users/kstannard  (scripting)(not a repo)  Feb 23
>> time tmux set status-left "[#S]"

real    0m0.033s
user    0m0.004s
sys     0m0.007s
```

Me telling alacritty to open:

```
/Users/kstannard  (scripting)(not a repo)  Feb 23
>> time open -a Alacritty

real    0m0.043s
user    0m0.018s
sys     0m0.017s

/Users/kstannard  (scripting)(not a repo)  Feb 23
>> sleep 1; time open -a Alacritty

real    0m0.035s
user    0m0.014s
sys     0m0.014s
```

**Comment by koekeishiya** [comment]
No worries, just cleaning out issues - I will reopen this one for you.

I'm still quite puzzled as to how the bind that performs the config-rewrite actually is able to trigger.
Assuming that the config you linked in the first comment is the one that **skhd** loads at launch, yes?

From what I can tell, **skhd** should straight up just fail to parse the file as it begins with the following:
```
<% terminal = "Alacritty" %>
```

The same should be true on line 35, when it gets to the literal/keycode part: `alt + shift - <%= 1 + i %>`

Is there something that I am just oblivious to here, or do you trigger the config rewrite through a mechanism external to **skhd**?

**Comment by kwstannard** [comment]
That file is not the actual config, it is just the template for the config. I have to manually run the line once to generate the config and after that it is good to go.

**Comment by kwstannard** [comment]
This is a generated config file:
```


# open terminal, blazingly fast compared to iTerm/Hyper
alt - p : open -a Firefox\ Developer\ Edition
alt - o : open -a /Applications/Slack.app
alt + shift -o : open -a Messages
alt - i : open -a /Applications/KeePassX.app

alt - return [
  "Alacritty" : tmux new-window -c ~/
]
alt - t : tmux new-window -a -t :=0

# focus window
alt - h : tmux select-pane -L
alt - j : tmux select-pane -D
alt - k : tmux select-pane -U
alt - l : tmux select-pane -R

alt - up : tmux copy-mode
alt - pageup : tmux copy-mode -u

alt + shift - m : osascript $HOME/scripts/osascript/maximize

alt - 0: tmux move-window -r


alt - 1 : tmux select-window -t :=5; \
  tmux set status-left "[#S] e1 5"; \
  open -a Alacritty

alt + shift - 1 : tmux swap-window -t :=5; \
  tmux set status-left "[#S] e1 5"; \
  open -a Alacritty

alt - 2 : tmux select-window -t :=6; \
  tmux set status-left "[#S] e1 6"; \
  open -a Alacritty

alt + shift - 2 : tmux swap-window -t :=6; \
  tmux set status-left "[#S] e1 6"; \
  open -a Alacritty

alt - 3 : tmux select-window -t :=7; \
  tmux set status-left "[#S] e1 7"; \
  open -a Alacritty

alt + shift - 3 : tmux swap-window -t :=7; \
  tmux set status-left "[#S] e1 7"; \
  open -a Alacritty

alt - 4 : tmux select-window -t :=8; \
  tmux set status-left "[#S] e1 8"; \
  open -a Alacritty

alt + shift - 4 : tmux swap-window -t :=8; \
  tmux set status-left "[#S] e1 8"; \
  open -a Alacritty

alt - 5 : tmux select-window -t :=9; \
  tmux set status-left "[#S] e1 9"; \
  open -a Alacritty

alt + shift - 5 : tmux swap-window -t :=9; \
  tmux set status-left "[#S] e1 9"; \
  open -a Alacritty



alt - 6 : ruby -r erb -e 'puts ERB.new(File.read(Dir.home+"/scripts/configs/skhdrc.erb.conf")).result binding' 0 > ~/.skhdrc

alt - 7 : ruby -r erb -e 'puts ERB.new(File.read(Dir.home+"/scripts/configs/skhdrc.erb.conf")).result binding' 1 > ~/.skhdrc

alt - 8 : ruby -r erb -e 'puts ERB.new(File.read(Dir.home+"/scripts/configs/skhdrc.erb.conf")).result binding' 2 > ~/.skhdrc

alt - 9 : ruby -r erb -e 'puts ERB.new(File.read(Dir.home+"/scripts/configs/skhdrc.erb.conf")).result binding' 3 > ~/.skhdrc


ctrl - 1 : khd -p 'cmd - 1'
ctrl - 2 : khd -p 'cmd - 2'
ctrl - 3 : khd -p 'cmd - 3'
ctrl - 4 : khd -p 'cmd - 4'
ctrl - 5 : khd -p 'cmd - 5'
ctrl - 6 : khd -p 'cmd - 6'
ctrl - 7 : khd -p 'cmd - 7'
ctrl - 8 : khd -p 'cmd - 8'
ctrl - 9 : khd -p 'cmd - 9'
ctrl - 0 : khd -p 'cmd - 0'

#ctrl - q ![Alacritty] : khd -p 'cmd - q'
#ctrl - w ![Alacritty] : khd -p 'cmd - w'
ctrl + shift - w [
"Alacritty" : tmux kill-window
]
ctrl - k [
"Slack" : khd -p 'cmd - k'
]

ctrl - b [
"KeePassX" : khd -p 'cmd - b'
]

ctrl - space : dismiss_notification

alt + shift - escape : pmset displaysleepnow
```

**Comment by koekeishiya** [comment]
So yeah, that config looks fine.. the timing from your previous comment also seem fine to me.
Can you try to build the latest commit from master? I've gotten rid of the compiler flag for enabling profiling, and I have added an argument instead: `skhd --profile` or `skhd -P`, so simply do a `make install`. I've changed the code to use a more accurate API to measure time elapsed..

For me, reloading the config when I manually edit it in `vim` takes about `0.3977` ms.
What I've noticed though, is that it actually takes maybe 1-2seconds for macOS to notify us that the file changed. This might be the delay that you are noticing as well.

You can verify this by looking at the output of `skhd -P`, then press your hotkey to generate a config-file. Take note of the time between the print of `... (handle_keypress)` and `... (hotload_config)`.
This time is time that we are not in control of, sadly..

**Comment by kwstannard** [comment]
Shoot, thank you. I guess you can close this.

**Comment by koekeishiya** [comment]
I could maybe add an option to disable the hotloading functionality and allow a `SIGUSR1` signal to trigger a reload of the config file. That way you could perform a  `kill -SIGUSR1 skhd` after the command that rewrites your config. Not sure if this is a good alternate solution or not, just a thought I had.

**Comment by kwstannard** [comment]
I would be good with a command to trigger a reload.

My first thought is that you may want to follow the tmux pattern. They have the `$ tmux source-file /path` that allows loading of a config to a running process. Maybe something like `skhd reload-config` that might even just be a wrapper for your kill signal?

**Comment by koekeishiya** [comment]
@kwstannard 

Do you happen to know if tmux uses a pid-file or a named semaphore, or some other method to detect an already running instance of the process?

**Comment by kwstannard** [comment]
I don't, sorry.

**Comment by koekeishiya** [comment]
So far I'm thinking of using a pid-file. When **skhd** starts, it looks to see if the pid-file exists, and if it does we try to see if a process with that pid exists. If it does, we know that an instance of **skhd** is already running and we can terminate. This way we make sure only one instance of the application is actually running.

Then we can add a launch argument `--reload` that will identify the existing instance, and send it a `SIGUSR1` signal, trigger a config reload.

**Comment by kwstannard** [comment]
That sounds like a very reasonable solution.

**Comment by koekeishiya** [comment]
Implemented on master. There is a new launch argument `skhd --no-hotload` or `skhd -h` that will disable the hotloader functionality. Simply invokce `skhd --reload` when an existing instance is running to manually trigger a reload of the config file.

The pid-file is created in `/tmp/skhd.pid` and so the user running **skhd** must have write access to that directory.

**Comment by koekeishiya** [comment]
Part of release v0.3.2, closing this.
