### ISSUE TITLE
any trick to "jump to previous desktop"? 

### ISSUE THREAD

**Issue by joefromct** [koekeishiya/skhd#55]
I am a new chunkwm/skhd user coming from linux + i3.

Is there any functionality Ii can put together to "jump back to previous desktop"?  I used this quite a bit with i3; it was the `workspace_auto_back_and_forth` functionality. 

https://i3wm.org/docs/userguide.html#workspace_auto_back_and_forth

Is there anyway to bind something to "jump to previous desktop" with skhd and chunkwm? 

``` 
workspace_auto_back_and_forth yes
bindsym $mod+z workspace back_and_forth
``` 
Thanks in advance,

**Comment by koekeishiya** [comment]
You can use the following, if you have chunkwm-sa installed:
```
cmd + alt - z : chunkc tiling::desktop --focus $(chunkc get _last_active_desktop)
```

I had a solution that did not require chunkwm-sa, but I don't have that available.
You might find it if you look through the history of the sample config in this repo.
