### ISSUE TITLE
Command key not working for repeated shortcuts outside skhd in Vivaldi browser

### ISSUE THREAD

**Issue by tokyovigilante** [koekeishiya/skhd#56]
I've got an interesting problem which may or not be a bug with skhd.

I'm using it with chunkwm and it's 99% great, however my preferred browser is Vivaldi, and although I don't have a binding defined in skhd for `cmd + w`, this key is used in Vivaldi to close tabs. The first time I invoke it to close a tab it works fine, but if I keep holding `cmd` and try to close another tab by pressing `W` again nothing happens. If I release `cmd` then press `cmd + w` again it works, but only once. Same for `cmd + t`, `cmd + n` etc.

I'm not sure whether this is a bug with skhd, Vivaldi (or Karabiner-Elements which I'm also using) or an interaction between one or more of them. 

As an aside, I'm only using Karabiner-Elements to remap `R_Opt` to forward delete, so if there's a way to do this in skhd, that would be great!

**Comment by koekeishiya** [comment]
Granted I don't use Vivaldi, I don't have this problem with Firefox nor Chrome.
I doubt it is an issue with **skhd**, as all we do is read the keyboard state and react to that.

I think your best bet is to stop **skhd** and try to see if the problem persists.

The level at which **skhd** intercept keys is unfortunately not suitable to do the kinds of remapping that *Karabiner* can perform, or at the very least would require a much much more complex structure for this to work seemlessly. 

You could also try a different browser (Safari ?). Both holding *cmd + w* and repeatedly releasing *w* while having *cmd* down the entire time works fine for me.

This is a tedious way to approach the problem, but should at least get you closer to finding the source of the issue.

**Comment by tokyovigilante** [comment]
Embarassingly this seems to be a Vivaldi bug. I was running the 2.2 beta, have downgraded to the 2.1 stable version and this bug is not present. I've filed a bug on their tracker. Sorry to waste your time, and thanks again for skhd/chunkwm!
