### ISSUE TITLE
include/source additional config files

### ISSUE THREAD

**Issue by BlueDrink9** [koekeishiya/skhd#58]
Is it currently possible to include/source an additional skhdrc file? Or must the config file be chosen by the startup option?

Would be excellent to have the former, as a way of managing complex configurations and per-machine overrides.

**Comment by koekeishiya** [comment]
This is currently not possible

**Comment by BlueDrink9** [comment]
Darn. Thanks for considering it! Would be great for matching up other program config file abilities. At least chunkwmrc can source like any bash script, right?

**Comment by koekeishiya** [comment]
chunkwmrc is just a shellscript yes, so everything you can do within a script can be done there.

**Comment by BlueDrink9** [comment]
Do you have a way to donate to you for all your work btw? Chunkwm is turning OSX into my favourite OS right now, and I'd like to give you a small thanks. (Also wouldn't mind a small bounty on this issue).

**Comment by BlueDrink9** [comment]
As an alternative way for this that may match your preferences, [sxhkd simply allows you to specify multiple configs at launch](https://github.com/baskerville/sxhkd/issues/57)

**Comment by koekeishiya** [comment]
Multiple configs at launch seem to be a better way to handle this situation due to the config-hotloading system. Need to figure some way to separate hotkeys by the config they originated from, so that we only flush bindings defined in the config-file that was edited.

Regarding supporting me, I do have a patreon here: https://www.patreon.com/aasvi (description is sort of outdated) and support is appreciated, however you should not feel obliged to donate.

**Comment by BlueDrink9** [comment]
I currently have a workaround using this code at the start of my `chunkwmrc`, that combines my custom config with any local config, then start skhd with that config. I do the same thing/a similar thing with sxhkd and bspwm.
```bash
XDG_CONFIG_HOME="$HOME/.config"
skhd_CombineConf(){
  configDir="$XDG_CONFIG_HOME/skhd"
  baseRCName=".skhdrc"
  combinedRC="$configDir/combined.skhdrc"
  baseRCDir="$HOME"

  baseRC="${baseRCDir}/${baseRC}"
  mkdir -p "$configDir"
  cat "$DOTFILES_DIR/windowManagers/chunkwm"/skhd/* "$baseRC" >| "${combinedRC}"
  unset baseRC backup baseRCName baseRCDir configDir localRC
}
export DOTFILES_DIR="$(cat $XDG_CONFIG_HOME/.dotfiles_dir)" && skhd_CombineConf && \
skhd -c "$XDG_CONFIG_HOME/skhd/combined.skhdrc" > $HOME/.logs/skhd.log 2> $HOME/.logs/skhd.err &
```

**Comment by koekeishiya** [comment]
After giving this some thought - I like including files more than having multiple configurations specified during startup.

Potential syntax for this would be: `.load "some file"`

If `"some file"` starts with a `/` or `~` it will be processed as an absolutepath, and if it does not begin with either of these we will assume relative pathing from the config file that it was loaded from.

To incorporate this with our current hotloading system - we will track changes made to the main config-file, as well as all files loaded through this option. In response to a file-changed event, we will be clearing all state the same way it works currently, and have it reload the *main* config. By doing it this way we can avoid having to deal with complex dependency tracking without limiting the power given to the user.

**Comment by koekeishiya** [comment]
Fixed on master. See my previous comment or updated information in the sample config or README  file for how to specify multiple config-files.

**Comment by BlueDrink9** [comment]
This WM is so much better than bspwm imo. Thank you so much for your work!

**Comment by koekeishiya** [comment]
Part of release v0.3.2, closing this.
