### ISSUE TITLE
Changing keymaps requires a restart

### ISSUE THREAD

**Issue by jboyens** [koekeishiya/skhd#59]
I use multiple keymaps (input sources) on my laptop. Dvorak when I'm on the internal keyboard and then US when I use my hardware Dvorak keyboard at the office.

Each time I switch between the different keymaps, I need to restart skhd in order for it to correctly get the new keymap and bind the right keys. If I don't restart, it holds the previous mapping so CMD-T is mapped to the action bound to CMD-K

My expectation would be that I could switch keymaps and not need to kill/restart the process.

**Comment by jboyens** [comment]
Forgot to mention that this is on Mojave.

**Comment by koekeishiya** [comment]
So this is just due to a caching optimization done in **skhd**: https://github.com/koekeishiya/skhd/blob/master/src/locale.c#L88
Which is only called once, in the startup routine.

We'd need a way to track when a keymap switch occur (is there an API for this?).
I'd like to avoid having to call this every time we parse the config-file, but that may be the only approach is there is no API available.

No ETA for now.

**Comment by jboyens** [comment]
This seems like it might be a public API, but I'm no macOS developer: https://stackoverflow.com/a/26024628

**Comment by jboyens** [comment]
I was able to fix this by using Hammerspoon's `hs.keycodes.inputSourceChanged()` and just running an `hs.execute('pkill skhd')`

The source for how they implement the watcher is here: [Source](https://github.com/Hammerspoon/hammerspoon/tree/master/extensions/keycodes)

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by koekeishiya** [comment]
part of release 0.3.1. closing this.

**Comment by HyunggyuJang** [comment]
Is it possible to disable this feature? I use multiple languages daily, so I frequently switches between multiple input sources, but those layouts are all same. So I don't want skhd to reload config every time I switches windows, which might triggers input source switches, in turn, reloading skhd config.

**Comment by HyunggyuJang** [comment]
Ideally, it would be better to add an option for this feature, like the hotload option.
