### ISSUE TITLE
Unable to use alt(option) + shift - left/right to highlight text

### ISSUE THREAD

**Issue by alexanghh** [koekeishiya/skhd#61]
Hi,

I am trying to get back the word/block highlighting of text in chrome/editor.
I tried using the passthrough but could not find examples and did not manage to get it to work. 
Any help would be appreciated.

Thanks.

**Comment by koekeishiya** [comment]
If you are using the config provided in the sample directory, you need to remove/comment the following lines: 

https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc#L126

https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc#L129

**Comment by alexanghh** [comment]
Thanks! Got it working.

**Comment by NickLarsenNZ** [comment]
> [master/examples/skhdrc#L126](https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc?rgh-link-date=2019-02-19T19%3A52%3A24Z#L126)
>
> [master/examples/skhdrc#L129](https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc?rgh-link-date=2019-02-19T19%3A52%3A24Z#L129)

@koekeishiya could you please provide permalinks? The file in master has changed enough that I'm unsure which lines you were talking about.
