### ISSUE TITLE
Unbind hotkey per application

### ISSUE THREAD

**Issue by timlkelly** [koekeishiya/skhd#62]
Is it possible to remove a hotkey for a certain application?
I see that you can have application specific hotkeys as you demonstrate here:
```
# cmd - n [
#     "kitty"       : echo "hello kitty"
#     "qutebrowser" : echo "hello qutebrowser"
#     "finder"      : false
# ]
```

Is it possible, without listing every application, to overwrite / unbind the hotkey for one application?
For instance, I have 
```alt - f : chunkc tiling::window --toggle fullscreen```
but i'd like this hotkey to not work in iTerm2

**Comment by dominiklohmann** [comment]
In khd you could switch from a whitelist of applications to a blacklist of applications by writing adding an `!` before the brackets but I don't think this is available in skhd as of now. This should not be particularly hard to implement aside from the argument parsing, since the filtering logic is already in-place and the logic just needs to be inverted.

**Comment by koekeishiya** [comment]
I wonder if we could do some sort of special syntax for that.

e.g:
```
# cmd - n [
#     "kitty"       : echo "hello kitty"
#     "qutebrowser" : echo "hello qutebrowser"
#     "finder"      : false
#     "iTerm2"      :  ---
#     "*"           : echo "everyone else"
# ]
```

The above would do something specific for every defined application. iTerm2 is specified to do nothing (unbound, keypress will go through to iterm2 as if skhd was not there), and every other application falls through to the last case.

**Comment by koekeishiya** [comment]
Implemented on master. See sample config and/or README for information. My previous comment in this issue has been edited  to reflect the new syntax.

**Comment by koekeishiya** [comment]
part of release 0.3.1, closing this.

**Comment by timlkelly** [comment]
Thank you for adding this, I appreciate the quick response! :)
