### ISSUE TITLE
Rebind closing applications/CMD+Q?

### ISSUE THREAD

**Issue by xiamaz** [koekeishiya/skhd#63]
I would like to rebind CMD+Q to refer to some other command, but would like to bind the functionality of closing applications to some other key.

Using the normal keybinding manager, there is no global option to rebind the application close behavior. Would it be possible in skhd?

**Comment by dominiklohmann** [comment]
```
ctrl - q : osascript -e "tell application \"Finder\" to set p to item 1 of (get file of (processes whose frontmost = true)) as text" -e "tell application p to quit"
```
