### ISSUE TITLE
Keybindings not working after 0.3.1 release

### ISSUE THREAD

**Issue by neverfox** [koekeishiya/skhd#65]
After updating to 0.3.1 through homebrew, none of the keybindings work anymore. For example, alt-f for fullscreen now just types a ƒ character. The service is running and accessibility is approved. Has this happened to others?

**Comment by neverfox** [comment]
Fixed on reboot

**Comment by PrismaPhonic** [comment]
I'm having the same issue but reboot isn't fixing it :-\ also I installed with logging and it's not even outputing logs, or giving me any stdout or stderr
