### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [koekeishiya/skhd#67]
Would you like to add more error handling for return values from functions like the following?
- [fread](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html "Binary input") ⇒ [read_file](https://github.com/koekeishiya/skhd/blob/ac494e3f72e397aaf3245b0401bd1b963bd4ebd3/src/parse.c#L38)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [table_new_bucket](https://github.com/koekeishiya/skhd/blob/e23811d884b9dae356c84e4515ef52184aa3432c/src/hashtable.h#L38)

**Comment by koekeishiya** [comment]
Not interested.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
