### ISSUE TITLE
segmentation fault skhd

### ISSUE THREAD

**Issue by cj** [koekeishiya/skhd#7]
This happens when using the default config and running `skhd` in the terminal.  Here's my crash report: https://gist.github.com/cj/b15332f0d1188c4adb9e29d8c062c2e3

Let me know if you need me to do/test anything else!

**Comment by koekeishiya** [comment]
See #4, #5 

I still can't reproduce the problem.

**Comment by cj** [comment]
@koekeishiya you mention that it's El Capitan specific, but I'm running macOS Sierra 10.12.6.  I can give you VNC access to the machine if that would help?  I'll shoot you an email.

**Comment by rzhikharevich** [comment]
I do have this problem on macOS High Sierra Golden Master with the Homebrew package (both 0.0.8 and HEAD). I don't experience this after building skhd myself, neither I do while using LLDB.

**Comment by chadbay** [comment]
I had this happen via brew install as well. One `git clone` and a `make install` later it worked like a charm. I had the problem with the default `.chunkwmrc` config. 
Running
```
macOS 10.12.6
clang-900.0.37
brew 1.3.4
xcode 9
```

Thanks for making these great productive tools. much appreciated.

**Comment by chadbay** [comment]
I did some debug on this today because it was driving me nuts. I believe brew is overriding the clang optimization level to `-0s`.

```-Os is like -O2 with extra optimizations to reduce code size.  ``` from [here](https://stackoverflow.com/questions/10290993/optimization-levels-in-llvm-and-clang)

So what I've done to get around this is update your brew formula install function to
```ruby
 def install
    ENV.O2  # OVERRIDE THE OPT LEVEL TO O2
    (var/"log/skhd").mkpath
    system "make", "install"
    bin.install "#{buildpath}/bin/skhd"
    (pkgshare/"examples").install "#{buildpath}/examples/skhdrc"
  end
```

Now brew will install `skhd` just fine and no more segfault. I hope this helps others.

-----
Here is why I believe brew is using `-Os` for the optimization level. Edit the formula's install function to
```ruby
 def install
    raise # force homebrew to give the shell option, among others
    (var/"log/skhd").mkpath
    system "make", "install"
    bin.install "#{buildpath}/bin/skhd"
    (pkgshare/"examples").install "#{buildpath}/examples/skhdrc"
  end
```
brew will give you some options to choose from once it hits `raise`, choose `5. shell`. Then check your env variables with `ENV`. I saw `HOMEBREW_OPTIMIZATION_LEVEL=Os`.

**Comment by crisidev** [comment]
You are right, brew override optimization with Os. The same happened to chunkwm during initial development.

**Comment by koekeishiya** [comment]
I can compile with `-Os`and `-Ofast` just fine, so the brew install must be doing something else that causes the problem.

The issue with chunkwm was actually code-related, but that is not the case here.

**Comment by chadbay** [comment]
i took brew out of the loop. `-O3 -O2 -Ofast`all start fine. `-Os` doesn't.

setup
```
git clone https://github.com/koekeishiya/skhd.git
cd skhd
```

`-Os` failing
```
rm -rf bin/skh
clang src/skhd.c -std=c99 -Os -framework Carbon -o bin/skh
./bin/skh -c ~/.skhdrc
skhd: using config '/Users/Chad/.skhdrc'
(#35) hotkey :: {
	mod: 'alt'
Segmentation fault: 11
```

passing with other optimizations, such as `-O3`
```
rm -rf bin/skh
clang src/skhd.c -std=c99 -Os -framework Carbon -o bin/skh
./bin/skh -c ~/.skhdrc
skhd: using config '/Users/Chad/.skhdrc'
(#35) hotkey :: {
	mod: 'alt'
	key: 'w' (0x0d)
	cmd: 'chunkc tiling::window --close'
}
(#38) hotkey :: {
	mod: 'alt'
	key: 'h' (0x04)
	cmd: 'chunkc tiling::window --focus west'
}
...
(#150) hotkey :: {
	mod: 'ctrl'
	mod: 'alt'
	key: 'w' (0x0d)
	cmd: 'chunkc tiling::desktop --deserialize ~/.chunkwm_layouts/dev_1'
}
hotload: watching file '.skhdrc' in directory '/Users/Chad'
```

It's only brew related on my macbook pro early 2013 in so far as `-Os` is used while doing `brew install`.

**Comment by chadbay** [comment]
I get the same result on a mpb mid-2015 core i7. both macs running
```
macOS 10.12.6
clang-900.0.37
```

**Comment by chadbay** [comment]
👍 😎  fix works here

**Comment by robertkeizer** [comment]
I was getting segfaults using `-O3` as well as `-Os`. Building removing the entire flag worked for me though.

Currently on `10.11.6`; clang `800.0.42.1`.
