### ISSUE TITLE
Shortcut to enable/disable all other commands of skhd

### ISSUE THREAD

**Issue by jbharat** [koekeishiya/skhd#71]
I faced this issue twice. There will be times when your skhd bindings will conflict with other bindings of some other tool. To use the other tool, we have to disable skhd with `brew services stop skhd` and once done restart the service again.

Is there a way to toggle all keys off/on. Like one key binding that disables all the keys of skhd and once the task is done I can toggle back the keys again. 

I am not sure if there is a better way to this then the one I thought of(toggling).

**Comment by dominiklohmann** [comment]
You should be able to use modes for that. There is a small example at the top of the example config which should help you setting this up.

**Comment by jbharat** [comment]
Thanks I will have a look.

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/skhd/issues/53 in particular for how to do this.

**Comment by jbharat** [comment]
Awesome. It worked for me. Thanks @koekeishiya @dominiklohmann 

```
:: passthrough
cmd + ctrl - t ; passthrough
passthrough < cmd + ctrl - t; default
```
