### ISSUE TITLE
Feature Request: i3 modes

### ISSUE THREAD

**Issue by EvanCarroll** [koekeishiya/skhd#72]
i3 has the ability to create modes, for example I could put this in my conf

```
mode "apps" {
	bindsym p exec --no-startup-id projectM-pulseaudio, mode "default"
	bindsym v exec --no-startup-id vlc, mode "default"
	bindsym m exec --no-startup-id vlc, exec --no-startup-id projectM-pulseaudio; mode "default"
	bindsym Return mode "default"
	bindsym Escape mode "default"
}
bindsym $mod+a mode "apps"
```

This would set up a mode when I hit a, followed by p, or a followed by v. or a followed by m. Shy of that I can exit or enter the mode. This makes it easy to create visual feed back (for what mode you're in), and to organize your conf. It would be nice if skhd provided for this. I take the skhd definition of "mode" is different though

**Comment by koekeishiya** [comment]
You can do this with the current system, but the syntax differs quite a bit.

```
#define mode called 'apps'
:: apps

# add binds inside apps mode that enters default mode
apps < return ; default
apps < escape ; default

# add some binds to launch stuff, and return to default mode after
apps < p : --no-startup-id projectM-pulseaudio; skhd -k "return"
apps < v : --no-startup-id vlc; skhd -k "return"
apps < m : --no-startup-id vlc; --no-startup-id projectM-pulseaudio; skhd -k "return"

# enter mode 'apps'
cmd - a ; apps
```

This syntax doesn't allow you to group binds the way you do in i3, so it may not be as concise, but it does the same thing in the end. If you want some command to run as you enter a mode, you can define that when declaring the mode, e.g: 
```
:: my_mode : echo "my_mode was activated"
```

I currently don't intend to make any changes to the modal system as of now.

**Comment by EvanCarroll** [comment]
That didn't seem to work for me. I don't have the time to troubleshoot it now. Will check later.

**Comment by jkorinth** [comment]
Does not work for me either; it seems the keypresses synthesized this way do not get processed by skhd? I tried both the code above, as well as other variants, like `skhd --reload` etc. Maybe a good compromise would be a syntax to specify both and action and a mode change?

**Comment by jkorinth** [comment]
Nevermind - the problem was just that skhd was not in the path for the subprocess shell; using an absolute path fixed the problem.
