### ISSUE TITLE
Feature Request: NOOP

### ISSUE THREAD

**Issue by EvanCarroll** [koekeishiya/skhd#73]
I'm using 

    cmd - h : /bin/echo "foo"

To stop the native Hide Window. It would be nice if there was a NOOP method to do this, explicitly. Maybe, as a suggestion,

    cmd -h : __NOOP__

Or we could do something like blacklist,

```
.dump {

}
```

**Comment by dominiklohmann** [comment]
Your shell has a built-in noop, it's called `true`.

```
cmd - h : true
```

**Comment by EvanCarroll** [comment]
Is this a shell script, or does it compile to something that calls `execve('/bin/true')`

**Comment by dominiklohmann** [comment]
`skhd` just does `$SHELL -c <command>"` when you press a key associated with a command, where the command is everything after the `:`.

**Comment by koekeishiya** [comment]
I don't think we need special syntax for this. Closing for now.
