### ISSUE TITLE
skhd: could not lock pid-file! abort..

### ISSUE THREAD

**Issue by testandset** [koekeishiya/skhd#74]
Hello,

I installed skhd via brew. I have enabled accessibility access and brew shows skhd service is running. Secure keyboard entry is disabled. When I run `skhd -V` it says

```
skhd: could not lock pid-file! abort..
```

When I stop the service and restart it with `sudo`, it woks and I can see it reacting to my defined hotkeys.  What am I missing?

**Comment by dominiklohmann** [comment]
See commit ef2e8ce7.

> **skhd** uses a pid-file to make sure that only one instance is running at any moment in time. This also allows for the ability to trigger a manual reload of the config file by invoking `skhd --reload` at any time while an instance of **skhd** is running. The pid-file is saved as `/tmp/skhd.pid` and so the user that is running **skhd** must have write permission to said path.

The inability to lock the pid-file means that you are either running skhd twice or that the user does not have write permission to `/tmp/skhd.pid`

**Comment by testandset** [comment]
Ah I see 🤦‍♂️. So running `skhd -V` runs it again which ofcourse can't get the lock file as it already locked when its running as brew service. 

thanks @dominiklohmann , appreciate it!

**Comment by essingen123** [comment]
Works just fine with my MacOS Ventura 13.5 (if you get the error message you should probably first run a `skhd --stop-service`  or  `brew services stop skhd` do the    `skhd -c ./skhdrc`  (or wherever the config file is) again restart the service with `skhd --start-service`   or  `brew services start skhd`. It works perfectly fine here anyways 👍

**Comment by ktrrbypass** [comment]
<img width="838" alt="image" src="https://github.com/user-attachments/assets/b27ec700-3e9a-4618-9521-fdeddadc6131" />

It just sits like this indefinitely

**Comment by nicolas-martin** [comment]
@ktrrbypass I'm having the same issue, did you manage to solve this?

**Comment by GregHilston** [comment]
Same question

**Comment by Nahuel-47** [comment]
> [@ktrrbypass](https://github.com/ktrrbypass) I'm having the same issue, did you manage to solve this?

Deleting all three /tmp/skhd_* files worked for me.
