### ISSUE TITLE
how does this compare to karabiner-elements

### ISSUE THREAD

**Issue by theonlygusti** [koekeishiya/skhd#78]

**Comment by koekeishiya** [comment]
I never really used karabiner-elements, but it is my understanding that the main purpose of karabiner-elements was key remapping and other ways to customize the keyboard / multiple different keyboards?

**skhd** is developed with one goal in mind, running an arbitrary command(s) when pressing a combination of keys.

**Comment by theonlygusti** [comment]
Yeah karabiner is less specialised, I (and maybe quite a few others?) happen to have it installed already because it's useful for some other things I need to customise.

I would like to set up `chunkwm`, I just wonder whether karabiner can be used instead of `skhd`, or if `skhd` is many more times more performant or some other reason.

**Comment by koekeishiya** [comment]
I'm not familiar enough with *karabiner* to comment on its performance, but if all you want is some way to create keybindings, I think *skhd* is superior for that purpose.

If you already use *karabiner* for other purposes you can probably use it for this as well without issues.

**Comment by capaldo** [comment]
> Yeah karabiner is less specialised, I (and maybe quite a few others?) happen to have it installed already because it's useful for some other things I need to customise.
> 
> I would like to set up `chunkwm`, I just wonder whether karabiner can be used instead of `skhd`, or if `skhd` is many more times more performant or some other reason.

You technically could per the documentation [here](https://pqrs.org/osx/karabiner/document.html#configuration-complex-modifications) although I can't say I've tried, I dont see why it wouldn't work

**Comment by aidan-gibson** [comment]
Not to necrobump, but for future lurkers: I am starting to use yabai and love it, naturally I bumped into skhd and wanted to learn about it. If I am not mistaken, there is nothing it can do that karabiner can't. I use karabiner with goku for config, so admittedly it's a mess, but I use it to run arbit scripts with keybinds just fine. If skhd has capabilities that karabiner doesn't I'd love to know, but I can't find any.
