### ISSUE TITLE
Razer keyboard alt doesn't work

### ISSUE THREAD

**Issue by joshmedeski** [koekeishiya/skhd#80]
![Screen Shot 2019-05-11 at 6 12 27 PM](https://user-images.githubusercontent.com/2036594/57575857-5bd16f00-7418-11e9-8e07-64882654f2e0.png)

skhd doesn't recognized the alt key at all. I've tried switching the command and alt key but it still doesn't do anything.

Do you know how to troubleshoot this or force skhd to register whatever keycode the Razer keyboard is sending to as an `alt` key for my configuration?

**Comment by dominiklohmann** [comment]
Can you run either `skhd --observe` (if you're on master) or `cev` (installed from [here](https://github.com/koekeishiya/cev)), press some alt + key combination and show the output?

I have not had issues with swapping modifier keys on my external keyboard and `skhd`, so I think this may be an issue with your configuration file. Please also post your `~/.skhdrc` file.

**Comment by joshmedeski** [comment]
Following your steps I realized something about the system was just ignoring that key all together. I uninstalled the Razer app for MacOS, restarted the computer and now the key is being registered again so it's working (I just don't get to control the lights or macro keys 😥️)
