### ISSUE TITLE
Replace carbon API upon deprecation

### ISSUE THREAD

**Issue by BlueDrink9** [koekeishiya/skhd#84]
[According to WWDC 2019](https://appleinsider.com/articles/19/05/22/wwdc-2019-schedule-teases-replaykit-for-macos-hearing-tech-in-healthkit), "macOS 10.15 should see the culling of QuickTime, Carbon, and Ink, the end of 32-bit application support, plus the introduction of Siri Shortcuts and standalone Music, Podcasts, and TV apps."

Looking through the source, I see you `#include carbon.h`. Is this going to be a problem with running this application under Catalina?

**Comment by dominiklohmann** [comment]
> Is this going to be a problem with running this application under Catalina?

No. Maybe future versions of macOS. 

Apple will have a hard time removing Carbon since so many tools depend on it and they still have not released a good replacement. They can deprecate all they want, but actually removing is another story.

**Comment by koekeishiya** [comment]
So the common misconception here arises from the fact that Carbon was a huge suite of different frameworks. When they say that Carbon has been deprecated, they usually refer to the higher level APIs that used to let you interface with 32bit applications. The actual core of Carbon is still very much a part of the OS foundation and is unlikely to disappear any time soon.

**Comment by BlueDrink9** [comment]
It's been "deprecated" for a while though, no? I was under the impression they were going to get rid of it totally, although I'd have to re-watch for the details.

If it is just part of it they are removing though, then I can sleep once more.

**Comment by koekeishiya** [comment]
I wouldn't worry much about this. I have a way to reimplement most, if not all all the deprecated functions that skhd rely on if necessary. Ie the carbon functon `GetFrontProcess(&psn);` that we use is simply a warpper call around a function called `_SLPSGetFrontProcess(&front_psn);`. This function again is implemented by looking up internal structures in the running macOS services. So at its core these functions still remain as an important part of the system. 

The other function `GetProcessForPID` can also be reimplemented by combining the following functions: `SLSGetConnectionPSN(..);`and `SLSConnectionGetPID(..);`.
