### ISSUE TITLE
Hotkeys using arrows not detected

### ISSUE THREAD

**Issue by wdanilo** [koekeishiya/skhd#86]
Hi! I'm trying to use the following config, however, it is not working properly. All other options are detected in the right way. The keycodes refer to arrow buttons.

```
fn - 0x7B : chunkc tiling::window --focus west
fn - 0x7D : chunkc tiling::window --focus south
fn - 0x7E : chunkc tiling::window --focus north
fn - 0x7C : chunkc tiling::window --focus east
```

**Comment by wdanilo** [comment]
I just realized that with the above config the arrow keys are captured even if the `fn` modifier is not pressed!

**Comment by dominiklohmann** [comment]
See https://github.com/koekeishiya/skhd/issues/10#issuecomment-421411872.

This should probably be documented somewhere. It's default system behaviour, and there's nothing you can do to change it.

> <kbd>fn</kbd> + <kbd>left</kbd> / <kbd>right</kbd> / <kbd>up</kbd> / <kbd>down</kbd> is  translated to <kbd>home</kbd> / <kbd>end</kbd> / <kbd>pageup</kbd> / <kbd>pagedown</kbd> respectively by macOS. 
> 
> ```
> home     : terminal-notifier -message "fn-left"
> end      : terminal-notifier -message "fn-right"
> pageup   : terminal-notifier -message "fn-up"
> pagedown : terminal-notifier -message "fn-down"
> ```

Also, you don't need to use hex codes for the arrow keys, left/right/up/down works just fine.

**Comment by wdanilo** [comment]
@dominiklohmann oh, I did not know about it. It's ugly :( Thanks for the explanation! <3
