### ISSUE TITLE
How to use caps lock as escape when pressing alone, as control when pressing with others

### ISSUE THREAD

**Issue by qhuyduong** [koekeishiya/skhd#87]
Thank you for great app! 
I’m quite new to it and don’t know is it possible to configure Caps Lock as Escape when pressing alone, as Ctrl when pressing with others? (I can do this with Karabiner)

**Comment by koekeishiya** [comment]
*skhd* does not support the caps-lock key. It is not really available to us in the API we use, unfortunately.

**Comment by qhuyduong** [comment]
Thank you very much @koekeishiya .
