### ISSUE TITLE
bind ctrl - HYPEN and ctrl - PLUS_KEY

### ISSUE THREAD

**Issue by victor-lund** [koekeishiya/skhd#89]
Is it possible to bind `PLUS` and `HYPHEN`? I want ctrl - plus to be mapped to cmd - plus

Something like this:

ctrl - PLUS_KEY : skhd -k "cmd - PLUS_KEY"
ctrl - HYPHEN_KEY : skhd -k "cmd - HYPHEN_KEY"

(Obviously this example wont work as PLUS_KEY and HYPHEN_KEY are not recognized.

**Comment by dominiklohmann** [comment]
Take a look at #1. 

For example it's `ctrl - 0x1E` for <kbd>ctrl</kbd> <kbd>+</kbd> on my german keyboard layout.
