### ISSUE TITLE
Keybinding with F* does not work anymore

### ISSUE THREAD

**Issue by crisidev** [koekeishiya/skhd#9]
Hello,
after the cleanup you did, all my keybinding using F* are not working anymore. I usually move through desktops with cmd + f[1-8] and they stopped working when I switched from stable 0.0.8 to HEAD.

I think there has been a regression. 0.0.8 works fine.

If I start HEAD version, the keystrokes are printed on the terminal. It seems skhd is not able to grab the keybinding when f* is involved.

If I change the keybinding to use numbers, like cmd + [1-8], everything works properly also with HEAD version.

**Comment by koekeishiya** [comment]
This is likely related to #8, and not the cleaup that came after.

**Comment by koekeishiya** [comment]
Confirmed this is related to the fn key. By default on MBP, the function keys are gated by the fn modifier. Thus, to bind a function key, you need to do the following: `fn - f1 : say hello`
This was not needed in previous versions, as the `fn` flag was not checked.

The sample bind above works fine. Now having to press fn every time to use a function key is annoying, so I assume you have enabled the "Use F1, F2, etc. keys as standard function keys" option in Keyboard settings. This option causes the system to silently add the `fn` flag to automatically generate the function key event. The binds must thus be registered in *skhd* with the fn modifier.

If you want `alt - f1 : something`, you need to register it in *skhd* as `alt + fn - f1 : something`.
I'm not sure if we could read the value of this setting during runtime and automatically add the flag at parsetime.

**Comment by crisidev** [comment]
Ah, cool, fair enough. I'll update and change my configs as soon as I have some time.

**Comment by koekeishiya** [comment]
See #10 for proposed solution.

**Comment by crisidev** [comment]
I can confirm, everything works fine adding the "fn" modifier.

**Comment by koekeishiya** [comment]
The latest version automatically supplies the fn flag for key-literals that have this set implicitly.

**Comment by crisidev** [comment]
Does it also work if I have the fn modifier set  in my config or should I remove it?

**Comment by koekeishiya** [comment]
That will work just fine as well.

**Comment by crisidev** [comment]
Cool! Thanks
