### ISSUE TITLE
XDG_CONFIG_HOME on default config search path

### ISSUE THREAD

**Issue by OJFord** [koekeishiya/skhd#90]
Would be good to be symmetric with yabai, and look in `$XDG_CONFIG_HOME/skhd/skhdrc`, then `.config/skhd/skhdrc`, then `$HOME/.skhdrc`.

I know the `-c` arg is available, but to use that with brew services means modifying the generated plist file...

**Comment by koekeishiya** [comment]
Implemented on master.

**Comment by OJFord** [comment]
Cracking, thanks.

**Comment by Hum4n01d** [comment]
This is a great new feature, but there's one issue: I just spent 10 minutes trying to figure out why it wasn't working only to find that the latest version published on brew doesn't support the new configuration file location. Could you update the README to reflect the currently published version or update brew please?

**Comment by OJFord** [comment]
As much as I'd like to see this released, I do think the readme on master should reflect the code on master, and leave compatibility with latest release to the state of the readme at that ref.

GitHub could certainly do with making that easier to see though.

**Comment by Hum4n01d** [comment]
Agreed, I spent too much time trying to figure out why my skhdrc wouldn't load :smile:

**Comment by capaldo** [comment]
> Agreed, I spent too much time trying to figure out why my skhdrc wouldn't load

I believe they mentioned that the wiki is open to editing. If you want the changes to reflect quickly you could always edit it if this is the case.

**Comment by bd12** [comment]
I still find that `$HOME/.config/skhd/skhdrc` is not evaluated in a vanilla and fresh install of skhd. Can someone confirm that?
When interactively invoking `shkd -c $HOME/.config/skhd/skhdrc` the config is loaded and my hotkeys work - but when starting through brew sevices (without any `-c` flag) the config seams not to be loaded. Note that in both cases my skhd can observe keys being pressed though.

spec: 
skhd version 0.3.4
sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103

**Comment by koekeishiya** [comment]
That's why the issue is tagged with *addressed-not-released*.

**Comment by bd12** [comment]
well, true, thanks! Sorry, I didn't look into the commit because the message only references XDG.
