### ISSUE TITLE
Issue remapping keys within just the Preview app

### ISSUE THREAD

**Issue by kennyworkman** [koekeishiya/skhd#93]
Hi, I've read through all the documentation and issues and have not been able to solve my problem. 

I'm simply trying to remap the "j" and "k" keys to the "Up" and "Down" menu commands with in the Preview app. What is the best way to go about setting up mappings to application specific menu commmands?

Sorry, not well versed in *nix quite yet.

Thanks for your time.
```

**Comment by dominiklohmann** [comment]
You can configure shortcuts for menu bar entries in the system preferences for any app, but you're not allowed to set just `j` and `k` without any modifier keys.

![image](https://user-images.githubusercontent.com/4488655/64084435-d3127200-cd2b-11e9-9dfd-9d23db2d47b7.png)

With `skhd`, you can add this to your config, emulating a <kbd>&darr;</kbd> keypress whenever <kbd>J</kbd> is pressed for just Preview.app.

```
j [
    "Preview" : skhd --key "down"
]
```

**Comment by kennyworkman** [comment]
Thank you! Solved it perfectly.
