### ISSUE TITLE
Bind F-keys to media keys

### ISSUE THREAD

**Issue by victor-lund** [koekeishiya/skhd#97]
I was wondering if there is a way to bind an F-key to a media-key without any modifiers. Like so:

```
f5 : skhd -k "NX_KEYTYPE_PREVIUOS"
f6 : skhd -k "NX_KEYTYPE_NEXT"
```

(The example above obviously do not work)

**Comment by koekeishiya** [comment]
skhd cannot synthesize a media-key press.

**Comment by dominiklohmann** [comment]
I quickly want to expand on this: You cannot synthesize a media-key press when not posting the event directly to an application. What the system does for you when you press a media key is to re-route the event to the application that currently should receive media key events.

If you know the application you want to send the event to you can always do this:

```osascript
tell application "Music"
    next track
end tell
```

Or from `skhd`:

```sh
f6 : osascript -e 'tell application "Music" to next track'
```

**Comment by grugnog** [comment]
For anyone finding this, I discovered that Shortcuts can generate media keys - see https://apple.stackexchange.com/a/429948. I assigned a shortcut directly, but I expect there is a way to trigger from a command if needed.
I was trying to send them to Google Music in Firefox, which doesn't support "next track", and sending keys via a browser extension was slow and unreliable.
