### ISSUE TITLE
Media keys not working

### ISSUE THREAD

**Issue by mvanderkroon** [koekeishiya/skhd#98]
I'm trying to bind media keys to commands, but unfortunately it either doesn't work, or I'm not fully grasping the syntax.

Some variations I tried:

`ctrl + NX_KEYTYPE_NEXT : cmus-remote -u` gives: `#167:8 expected key-literal`

`NX_KEYTYPE_NEXT : cmus-remote -u` gives: `#167:1 undeclared identifier`

Version I use is 0.3.4 (homebrew installed)

**Comment by dominiklohmann** [comment]
See also: #1.

```
ctrl - sound_up : <command>
```

**Comment by mvanderkroon** [comment]
Thanks, that does work - I'm not sure how I missed this in the docs though - sorry for that.

I am dealing with a touchbar here, so I'll probably follow your recommendation on the F-keys as well, many thanks
