### ISSUE TITLE
hotkey buffer lag

### ISSUE THREAD

**Issue by haze** [koekeishiya/skhd#99]
Recently I updated to mac OS 10.15.1 Catalina Beta (19B86a) and noticed a huge delay in reading inputs from skhd. I tried reinstalling, restarting the service but have had limited success in getting keystrokes to be responsive. One odd behavior I noticed was that between swapping windows quickly, sometimes it would select the wrong window.

**Comment by dominiklohmann** [comment]
I cannot reproduce this. What's your shell startup time? 

```sh
# measure time to start a non-interactive shell and exit it again
time $SHELL -c exit
```

The reason why I'm asking this is because this is how `skhd` runs your commands: it spawns a new, non-interactive shell for every single one of them.

**Comment by haze** [comment]
```
 ~ time $SHELL -c exit                                                 
$SHELL -c exit  0.00s user 0.00s system 71% cpu 0.005 total
```
I ended up leaving and using my computer later and it seems to be fixed, will re-open if I either find out how to reproduce or encounter again. Thanks!

**Comment by aSapien** [comment]
@dominiklohmann I'm experiencing the same issue and your comment was huge help. Thanks!
